#pragma once

typedef enum {
	COLOR_SPACE_INNVALID = -1,
	COLOR_SPACE_CMYK = 0,
	COLOR_SPACE_RGB,
	COLOR_SPACE_MAX_TYPES
}eCOLOR_SPACE_TYPE;


typedef enum {
	COLOR_CORRECT_INPUT,
	COLOR_CORRECT_SPACE_POPUP,
	COLOR_CORRECT_SLIDER1,
	COLOR_CORRECT_SLIDER2,
	COLOR_CORRECT_SLIDER3,
	COLOR_CORRECT_SLIDER4,
	COLOR_CORRECT_SLIDER5,
	COLOR_CORRECT_SLIDER6,
	COLOR_CORRECT_SLIDER7,
	COLOR_CORRECT_SLIDER8,
	COLOR_CORRECT_TOTAL_PARAMS
}Item;

