import datetime
from colour.models.rgb.transfer_functions.arri import CONSTANTS_ARRILOGC4 as C

a=float(C['a']); b=float(C['b']); c=float(C['c']); s=float(C['s']); t=float(C['t'])
now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
def fnum(v): return repr(float(v))
L=[]; w=L.append
w("/*")
w(" * ARRI_LogC4.hpp")
w(" *")
w(" * !!! GENERATED FILE - DO NOT EDIT MANUALLY !!!")
w(" *")
w(" * ARRI LogC4 curve decode (inverse OETF). Unlike LogC3, LogC4 is")
w(" * EI-INDEPENDENT: a single curve for all exposure indices (only an internal")
w(" * hardware gain changes with EI, not the encoding curve). Hence no EI table.")
w(" *")
w(" * Decode (encoded E_p, normalized float -> relative scene-linear E_scene):")
w(" *     E_scene = (E_p >= 0) ? (2^(14*((E_p - c)/b) + 6) - 64) / a")
w(" *                          :  E_p * s + t")
w(" *")
w(" * Scene-referred: 18%% mid grey encodes to E_p ~= 0.2784 and decodes to ~0.18.")
w(" * The E_p < 0 branch is the linear extension for sub-black (negative) code")
w(" * values; it is rarely exercised but included for exactness.")
w(" *")
w(" * Base-2 exponial: uses std::exp2 (C++11).")
w(" *")
w(" * Constants (a,b,c,s,t): ARRI LogC4 Specification, as tabulated in")
w(" * colour-science (authoritative reproduction). Provenance of a,b,c,t:")
w(" *     a = (2^18 - 16) / 117.45")
w(" *     b = (1023 - 95) / 1023")
w(" *     c = 95 / 1023")
w(" *     t = (2^(14*(-c/b)+6) - 64) / a")
w(" * Generated on: " + now)
w(" * Standard    : C++14 (no newer features used)")
w(" */")
w("")
w("#ifndef __GENERATED_ARRI_LOGC4_HPP__")
w("#define __GENERATED_ARRI_LOGC4_HPP__")
w("")
w("#include <cmath>")
w("")
w("namespace ARRI_LogC4")
w("{")
w("    // LogC4 curve constants (single set; EI-independent).")
w("    constexpr double a = " + fnum(a) + ";")
w("    constexpr double b = " + fnum(b) + ";")
w("    constexpr double c = " + fnum(c) + ";")
w("    constexpr double s = " + fnum(s) + ";  // slope of sub-black linear segment")
w("    constexpr double t = " + fnum(t) + ";  // offset of sub-black linear segment")
w("")
w("    // Decode a LogC4 encoded value E_p (normalized float) to relative")
w("    // scene-linear, computed in type T (use float or double).")
w("    template<typename T>")
w("    inline T decode(T E_p) noexcept")
w("    {")
w("        if (E_p >= static_cast<T>(0))")
w("        {")
w("            const T expo = static_cast<T>(14) *")
w("                           ((E_p - static_cast<T>(c)) / static_cast<T>(b))")
w("                           + static_cast<T>(6);")
w("            return (std::exp2(expo) - static_cast<T>(64)) / static_cast<T>(a);")
w("        }")
w("        return E_p * static_cast<T>(s) + static_cast<T>(t);")
w("    }")
w("")
w("} // namespace ARRI_LogC4")
w("")
w("#endif // __GENERATED_ARRI_LOGC4_HPP__")
open("ARRI_LogC4.hpp","w").write("\n".join(L)+"\n")
print("written")
