#ifndef __IMAGE_LAB_VIDEO_STABILIZATION_ITEMS_ENUMERATORS__
#define __IMAGE_LAB_VIDEO_STABILIZATION_ITEMS_ENUMERATORS__



typedef enum {
    IMAGE_STABILIZATION_INPUT,
    IMAGE_STYLE_TOTAL_PARAMS
}Item;


#endif // __IMAGE_LAB_VIDEO_STABILIZATION_ITEMS_ENUMERATORS__
