#ifndef __PERCEPTUAL_COLOR_CORRECTION_ENUMERATOR__
#define __PERCEPTUAL_COLOR_CORRECTION_ENUMERATOR__



typedef enum {
    PERCOLOR_CORRECTION_INPUT,
    PERCOLOR_CORRECTION_TOTAL_PARAMS
}Item;


#endif // __PERCEPTUAL_COLOR_CORRECTION_ENUMERATOR__