#ifndef __IMAGE_LAB_PRISMA_ENUMERATORS_VIDEO_FILTER__
#define __IMAGE_LAB_PRISMA_ENUMERATORS_VIDEO_FILTER__


typedef enum {
    PRISMA_VIDEO_INPUT,
    PRISMA_VIDEO_TOTAL_PARAMS
}Item;


#endif // __IMAGE_LAB_PRISMA_ENUMERATORS_VIDEO_FILTER__