#ifndef __IMAGE_LAB_COLOR_SUBSTITUTION_FILTER_ENUMERATORS__
#define __IMAGE_LAB_COLOR_SUBSTITUTION_FILTER_ENUMERATORS__

#include "AE_Effect.h"

typedef enum {
    eCOLOR_SUBSTITUTION_INPUT,
    eCOLOR_SUBSTITUTION_CONTROLS
}eAVERAGE_FILTER_ITEMS;


#endif // __IMAGE_LAB_COLOR_SUBSTITUTION_FILTER_ENUMERATORS__