#ifndef __IMAGE_LAB_IMAGE_GEOMETRY_ENUMERATORS_FILTER__
#define __IMAGE_LAB_IMAGE_GEOMETRY_ENUMERATORS_FILTER__

#include "AE_Effect.h"

typedef enum {
    eIMAGE_AFMEDIAN_INPUT,
    eIMAGE_AFMEDIAN_TOTAL_CONTROLS
}eAVERAGE_FILTER_ITEMS;



#endif // __IMAGE_LAB_IMAGE_GEOMETRY_ENUMERATORS_FILTER__