#ifndef __IMAGE_LAB_RETRO_VISION_FILTER_ENUMERATORS__
#define __IMAGE_LAB_RETRO_VISION_FILTER_ENUMERATORS__

#include "AE_Effect.h"

typedef enum {
    eRETRO_VISION_INPUT,
    eRETRO_VISION_TOTAL_CONTROLS
}eAVERAGE_FILTER_ITEMS;


#endif // __IMAGE_LAB_RETRO_VISION_FILTER_ENUMERATORS__