#ifndef __IMAGE_LAB2_COLOR_ENGINE_CCT_LUT_AGGREGATOR__
#define __IMAGE_LAB2_COLOR_ENGINE_CCT_LUT_AGGREGATOR__

#include "LINEARIZE_LUT_SRGB_8BIT_F64.hpp"
#include "LINEARIZE_LUT_SRGB_10BIT_F64.hpp"
#include "LINEARIZE_LUT_SRGB_16BIT_F64.hpp"

#endif // __IMAGE_LAB2_COLOR_ENGINE_CCT_LUT_AGGREGATOR__
