#pragma once

constexpr int channelSliderMin = 0;
constexpr int channelSliderMax = 40;
constexpr int channelSLiderDef = channelSliderMin;

typedef enum {
	IMAGE_EQ_NONE,
	IMAGE_EQ_LINEAR,
	IMAGE_EQ_BRIGHT,
	IMAGE_EQ_DARK,
	IMAGE_EQ_EXPONENTIAL,
	IMAGE_EQ_SIGMOID,
	IMAGE_EQ_ADVANCED,
	IMAGE_EQ_MANUAL,
	IMAGE_EQ_ALGO_TOTALS
}ImageEqPopupAlgo;

typedef enum {
	IMAGE_EQUALIZATION_FILTER_INPUT,
	IMAGE_EQUALIZATION_POPUP_PRESET,
	IMAGE_EQUALIZATION_BLACKS_SLIDER,
	IMAGE_EQUALIZATION_SHADOWS_SLIDER,
	IMAGE_EQUALIZATION_MIDTONES_SLIDER,
	IMAGE_EQUALIZATION_WHITES_SLIDER,
	IMAGE_EQUALIZATION_HIGHLIGHTS_SLIDER,
	IMAGE_EQUALIZATION_DARK_PEDESTAL_SLIDER,
	IMAGE_EQUALIZATION_FLICK_REMOVE_CHECKBOX,
	IMAGE_EQUALIZATION_FILTER_TOTAL_PARAMS
}Item;

