#ifndef __IMAGE_LAB_IMAGE_ART_MOSAIC_ENUMERATORS__
#define __IMAGE_LAB_IMAGE_ART_MOSAIC_ENUMERATORS__

#include <cstdint>

enum class eART_MOSAIC_ITEMS : int32_t
{
    eIMAGE_ART_MOSAIC_INPUT,
    eIMAGE_ART_MOSAIC_TOTAL_CONTROLS
};



#endif // __IMAGE_LAB_IMAGE_ART_MOSAIC_ENUMERATORS__