#pragma once

typedef enum
{
	eSTYLE_NONE = 0,
	eSTYLE_NEWS_PAPER_OLD,
	eSTYLE_NEWS_PAPER_COLOR,
	eSTYLE_GLASSY_EFFECT,
	eSTYLE_OIL_PAINT,
	eSTYLE_CARTOON,
	eSTYLE_SKETCH_PENCIL,
	eSTYLE_SKETCH_CHARCOAL,
	eSTYLE_TOTAL_EFFECTS
}eSTYLIZATION;