#ifndef __IMAGE_LAB_AUTOMATIC_WHITE_BALANCE_PS2017_PLUGIN__
#define __IMAGE_LAB_AUTOMATIC_WHITE_BALANCE_PS2017_PLUGIN__

#include "ImageLabCommon.hpp"

#endif /* __IMAGE_LAB_AUTOMATIC_WHITE_BALANCE_PS2017_PLUGIN__ */