// ---------------------------------------------------------------------------
//  Copyright (c) 2026 Marat Shchuchinsky. All rights reserved.
//
//  PROPRIETARY. The schema, the derived values, the provenance records and the
//  documentation in this database are the intellectual property of Marat
//  Shchuchinsky, and represent substantial investment in obtaining, verifying
//  and presenting the contents.
//
//  No part of this database, nor any individual value, fragment, extract or
//  derivative work, may be copied, reproduced, distributed, published,
//  transmitted, modified, incorporated into another work or otherwise used, in
//  whole or in part, without the prior written permission of Marat
//  Shchuchinsky. Unauthorised use, reproduction, distribution or disclosure of
//  any portion is strictly prohibited.
//
//  Published manufacturer data cited in this file remains the property of the
//  respective rights holders; every such value carries its own source record.
// ---------------------------------------------------------------------------
// Generated by cpp_codegen.py -- do not edit by hand.
// generated: 2026-09-10  18:48:33Z
// schema_version 30
// See LoadFilmDataBase.h for the design constraints this implements.
#include "LoadFilmDataBase.h"
#include "film_profiles_detail.hpp"

#include <atomic>
#include <cstdint>
#include <mutex>
#include <new>

namespace film {
namespace {

std::vector<FilmProfile>& storage()
{
    // Function-local magic static: constructed (empty, trivial) on first
    // touch inside the loader -- NOT at DLL load. C++11 semantics make the
    // construction race-free; VS2015 implements this ("magic statics") and
    // AlgoMemHandler.cpp already relies on the same guarantee.
    // Requires /Zc:threadSafeInit (the default) -- do not disable it.
    static std::vector<FilmProfile> s;
    return s;
}

std::once_flag g_once;                     // constant-initialised
std::atomic<bool> g_loaded{false};        // constant-initialised

}  // namespace

bool LoadFilmDataBase(void)
{
    if (g_loaded.load(std::memory_order_acquire))
        return true;                        // fast path for repeat calls
    try
    {
        std::call_once(g_once, []
        {
            const std::size_t kCount = static_cast<std::size_t>(
                eFILM_PROFILE::eTOTAL_FILMS_PROFILES);
            std::vector<FilmProfile> v;
            v.reserve(kCount);
        detail::AppendProfiles_01(v);
        detail::AppendProfiles_02(v);
        detail::AppendProfiles_03(v);
        detail::AppendProfiles_04(v);
        detail::AppendProfiles_05(v);
        detail::AppendProfiles_06(v);
        detail::AppendProfiles_07(v);
        detail::AppendProfiles_08(v);
        detail::AppendProfiles_09(v);
        detail::AppendProfiles_10(v);
        detail::AppendProfiles_11(v);
        detail::AppendProfiles_12(v);
        detail::AppendProfiles_13(v);
        detail::AppendProfiles_14(v);
        detail::AppendProfiles_15(v);
        detail::AppendProfiles_16(v);
        detail::AppendProfiles_17(v);
        detail::AppendProfiles_18(v);
        detail::AppendProfiles_19(v);
        detail::AppendProfiles_20(v);
        detail::AppendProfiles_21(v);
        detail::AppendProfiles_22(v);
        detail::AppendProfiles_23(v);
        detail::AppendProfiles_24(v);
            if (v.size() != kCount)
                throw std::bad_alloc();     // slot/count mismatch: fail, retry
            storage().swap(v);
            // Pre-warm the two small magic-static tables too, so GlobalSetup
            // pays ALL one-time construction and the render path never does.
            (void)GetPrintStocks();
            (void)GetFilmFormats();
            g_loaded.store(true, std::memory_order_release);
        });
    }
    catch (...)
    {
        // bad_alloc (or the count guard). call_once does NOT consume the
        // flag on an exceptional run, so the next call retries the build
        // instead of leaving the plugin permanently without its database.
        return false;
    }
    return g_loaded.load(std::memory_order_acquire);
}

bool IsFilmDataBaseLoaded(void) noexcept
{
    return g_loaded.load(std::memory_order_acquire);
}

const FilmProfile* GetFilmProfile(eFILM_PROFILE filmId) noexcept
{
    if (!g_loaded.load(std::memory_order_acquire))
        return nullptr;
    const std::int32_t idx = static_cast<std::int32_t>(filmId);
    if (idx < 0 || idx >= static_cast<std::int32_t>(
            eFILM_PROFILE::eTOTAL_FILMS_PROFILES))
        return nullptr;
    return &storage()[static_cast<std::size_t>(idx)];
}

const std::vector<FilmProfile>& GetFilmDatabase()
{
    LoadFilmDataBase();                    // idempotent lazy safety net
    return storage();                      // empty vector if load failed
}

}  // namespace film
