#ifndef __IMAGE_LAB_LIGHTROOM_PRESETS_ENUMS_FILTER__
#define __IMAGE_LAB_LIGHTROOM_PRESETS_ENUMS_FILTER__


typedef enum {
    ART_POINTILISM_INPUT,
    ART_POINTILISM_TOTAL_PARAMS
}Item;


#endif // __IMAGE_LAB_LIGHTROOM_PRESETS_ENUMS_FILTER__