#ifndef __IMAGE_LAB_ART_POINTILISM_ENUMERATORS__
#define __IMAGE_LAB_ART_POINTILISM_ENUMERATORS__


typedef enum {
    ART_POINTILISM_INPUT,
    ART_POINTILISM_TOTAL_PARAMS
}Item;


#endif // __IMAGE_LAB_ART_POINTILISM_ENUMERATORS__