#!/usr/bin/env python3
"""Python vs C++ parity for `batchPosition`, the schema-v52 control.

WHAT IS BEING COMPARED
----------------------
`film_sim.resolve_batch_position` against `AlgoResolveBatchPosition`
(AlgoBatchPosition.hpp), on every stock that carries an acceptance band, at
five positions including both edges and the OFF default.

⚠⚠ THE INTERESTING PROPERTY HERE IS NEGATIVE, AND IT IS WHY THIS AUDIT IS
SHORT. The header contains NO `AlgoType`, no intrinsics and no pixel loop --
it rewrites two floats per layer on a copy of the profile. So the scalar and
the vector builds do not merely agree, they compile THE SAME CODE, and the
class of defect that has cost this project three engine bugs (the Schraudolph
white point, the unread `anisotropy`, the NaN-to-white clamp) cannot arise.
The probe is still built twice, against each project's own include path, and
still prints `sizeof(AlgoType)` -- because "cannot arise" is a claim about the
source as it stands today and this file is what keeps it true tomorrow.

⚠ THE OFF PATH IS TESTED AS CAREFULLY AS THE MOVED ONE. At position 0 the
resolver must return the profile BY REFERENCE with no copy, and Python must
return the identical object -- that is what makes a v52 render at defaults
bit-identical to a v51 one. A resolver that produced an equal-but-copied
profile would pass a value comparison and still be wrong, so the C++ side
prints the ADDRESS and the Python side checks object identity.

WHAT THE NUMBERS SHOULD LOOK LIKE
---------------------------------
The two halves of the band are deliberately ASYMMETRIC on the four masked
Soviet cine negatives, whose ТУ print «+0,06 / -0,04» on every layer. And one
cell is one-sided on purpose: Фото ЦНД-32's middle layer reads «0,60 + 0,08»
in ГОСТ 25120-82 табл. 6 where the cells above and below it read «±». Until
2026-09-30 the stored green sat ON that floor and could not move toward -1;
since the owner adopted Гурлев 1986's drawn curve (green 0.643) the batch zero
is the drawn roll, and -1 lands exactly ON the printed floor 0.60 and never
below it. Both are asserted here, because both look like bugs to anyone who
has not read the documents.
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import film_profiles as FP            # noqa: E402
import film_sim as FS                 # noqa: E402
import engine_env  # noqa: E402,F401 -- owner FFT include path for engine compiles (2026-10-06)

#: The positions probed. 0.0 is the OFF case and is checked for identity
#: rather than for equality; the rest must agree numerically.
POSITIONS = (0.0, 1.0, -1.0, 0.5, -0.25)

#: Float32 round-trip is the only difference either side can legitimately
#: have: Python computes in double and stores into a float32 dataclass field,
#: C++ computes in double and stores into a float. 1e-6 is three orders above
#: that and two below the smallest band width in the corpus (0.04).
TOL = 1.0e-6

PROBE = r"""
// Generated by batch_position_parity.py -- not part of the shipped plugin.
#include "film_profiles.hpp"
#include "LoadFilmDataBase.h"
#include "AlgoBatchPosition.hpp"
#include "AlgoTypes.hpp"
#include <cstdio>
#include <cstddef>
#include <string>

static const char* kNames[] = { %(NAMES)s };
static const double kPos[] = { %(POS)s };

int main()
{
    std::printf("SIZEOF %%d\n", (int)sizeof(AlgoType));
    if (false == film::LoadFilmDataBase()) { std::printf("NOLOAD\n"); return 1; }
    const std::vector<film::FilmProfile>& db = film::GetFilmDatabase();
    for (std::size_t n = 0; n < %(NSTOCK)u; ++n)
    {
        const film::FilmProfile* base = nullptr;
        for (std::size_t i = 0; i < db.size(); ++i)
            if (db[i].name == kNames[n]) { base = &db[i]; break; }
        if (nullptr == base) { std::printf("MISSING %%s\n", kNames[n]); continue; }

        for (std::size_t k = 0; k < %(NPOS)u; ++k)
        {
            film::FilmProfile store;
            const film::FilmProfile& out =
                AlgoResolveBatchPosition(*base, kPos[k], store);
            // SAME 1 means the resolver returned the base BY REFERENCE, which
            // is the no-copy default path.
            std::printf("ROW %%s %%.17g %%d %%.9g %%.9g %%.9g %%.9g %%.9g %%.9g\n",
                        kNames[n], kPos[k], (&out == base) ? 1 : 0,
                        (double)out.curves.r.gamma,
                        (double)out.curves.g.gamma,
                        (double)out.curves.b.gamma,
                        (double)out.curves.r.dmin,
                        (double)out.curves.g.dmin,
                        (double)out.curves.b.dmin);
        }
    }
    return 0;
}
"""


def banded() -> list[str]:
    return sorted(p.name for p in FP.FILM_PROFILES if p.tolerance)


def build_probe(root: Path, tmp: Path, avx2: bool):
    """Compile the probe against one project's include path.

    ⚠ THE AVX2 BUILD NEEDS ITS OWN `AlgoTypes.hpp` FIRST, exactly as
    `bromide_parity.py` documents: the two projects each ship one, scalar sets
    AlgoType to double and AVX2 to float, and the vector sources carry a
    static_assert on the size. A staging directory of symlinks reproduces what
    the real two-project build does.
    """
    cxx = os.environ.get("CXX") or shutil.which("g++") or shutil.which("clang++")
    if not cxx:
        raise SystemExit("[!] no g++/clang++ on PATH (set CXX to override)")

    names = banded()
    src = tmp / ("probe_avx2.cpp" if avx2 else "probe_scalar.cpp")
    src.write_text(PROBE % dict(
        NAMES=", ".join('"%s"' % s for s in names),
        NSTOCK=len(names),
        POS=", ".join("%.17g" % v for v in POSITIONS),
        NPOS=len(POSITIONS),
    ), encoding="utf-8")

    inc = [str(root), str(HERE)]
    flags = ["-std=c++17", "-O1"]
    if avx2:
        stage = tmp / "avx2inc"
        if not stage.exists():
            stage.mkdir()
            for f in list(root.glob("*.hpp")):
                (stage / f.name).symlink_to(f.resolve())
            hdr = root / "AVX2" / "AlgoTypes.hpp"
            if not hdr.is_file():
                return None
            (stage / "AlgoTypes.hpp").unlink()
            (stage / "AlgoTypes.hpp").symlink_to(hdr.resolve())
        inc = [str(stage), str(root), str(HERE)]
        flags += ["-mavx2", "-mfma"]

    tus = [str(src), str(HERE / "film_profiles.cpp"),
           str(HERE / "LoadFilmDataBase.cpp")]
    tus += [str(p) for p in sorted(HERE.glob("film_profiles_data_*.cpp"))]

    exe = tmp / ("probe_avx2" if avx2 else "probe_scalar")
    cmd = [cxx] + flags
    for i in inc:
        cmd += ["-I", i]
    cmd += ["-o", str(exe)] + tus
    r = subprocess.run(cmd, cwd=tmp, capture_output=True, text=True)
    if r.returncode != 0:
        tail = (r.stderr or r.stdout).strip().splitlines()
        raise SystemExit("[!] %s probe did not compile:\n  %s"
                         % ("AVX2" if avx2 else "scalar",
                            "\n  ".join(tail[:14])))
    return exe


def run_probe(exe: Path):
    r = subprocess.run([str(exe)], capture_output=True, text=True)
    if r.returncode != 0:
        raise SystemExit("[!] probe failed: %s" % (r.stderr or r.stdout)[:400])
    size, rows = None, {}
    for line in r.stdout.splitlines():
        f = line.split()
        if f and f[0] == "SIZEOF":
            size = int(f[1])
        elif f and f[0] == "ROW":
            rows[(f[1], float(f[2]))] = (int(f[3]),
                                         tuple(float(x) for x in f[4:10]))
        elif f and f[0] == "MISSING":
            raise SystemExit("[!] the probe could not find %s" % f[1])
    return size, rows


def python_rows():
    out = {}
    for name in banded():
        base = next(p for p in FP.FILM_PROFILES if p.name == name)
        for pos in POSITIONS:
            q = FS.resolve_batch_position(base, pos)
            out[(name, pos)] = (
                1 if q is base else 0,
                (q.curves.r.gamma, q.curves.g.gamma, q.curves.b.gamma,
                 q.curves.r.dmin, q.curves.g.dmin, q.curves.b.dmin))
    return out


def run(do_assert: bool = True) -> int:
    root = Path(os.environ.get("FILMSIM_ROOT", "/root/work/proot"))
    if not (root / "AlgoBatchPosition.hpp").is_file():
        print("[SKIP] batch_position_parity.py -- AlgoBatchPosition.hpp is not "
              "in the engine tree at %s" % root)
        return 0

    names = banded()
    py = python_rows()
    fail: list[str] = []
    print("=== batchPosition parity: %d banded stocks x %d positions ==="
          % (len(names), len(POSITIONS)))

    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td)
        for avx2 in (False, True):
            exe = build_probe(root, tmp, avx2)
            tag = "AVX2" if avx2 else "scalar"
            if exe is None:
                print("  [SKIP] %s -- project not present" % tag)
                continue
            size, cpp = run_probe(exe)
            print("  %-6s sizeof(AlgoType) = %d" % (tag, size))
            worst, worst_at = 0.0, ""
            for key, (psame, pvals) in py.items():
                if key not in cpp:
                    fail.append("%s: %s at %+g missing from the probe"
                                % (tag, key[0], key[1]))
                    continue
                csame, cvals = cpp[key]
                if psame != csame:
                    fail.append(
                        "%s: %s at %+g -- Python %s the base object, C++ %s"
                        % (tag, key[0], key[1],
                           "returns" if psame else "copies",
                           "returns" if csame else "copies"))
                for a, b in zip(pvals, cvals):
                    d = abs(a - b)
                    if d > worst:
                        worst, worst_at = d, "%s at %+g" % (key[0], key[1])
                    if d > TOL:
                        fail.append("%s: %s at %+g -- %.9g vs %.9g"
                                    % (tag, key[0], key[1], a, b))
            print("     worst |python - c++| = %.3g  (%s), tolerance %g"
                  % (worst, worst_at or "-", TOL))

    # -- the two things that look like bugs and are the documents ------------
    ds5 = next(p for p in FP.FILM_PROFILES if p.name == "SVEMA_DS_5M")
    up = FS.resolve_batch_position(ds5, 1.0).curves.b.gamma - ds5.curves.b.gamma
    dn = ds5.curves.b.gamma - FS.resolve_batch_position(ds5, -1.0).curves.b.gamma
    print("  ДС-5М blue gamma: +1 moves %+.3f, -1 moves %+.3f "
          "(the ТУ prints «+0,06 / -0,04»)" % (up, -dn))
    if abs(up - 0.06) > 1e-6 or abs(dn - 0.04) > 1e-6:
        fail.append("the asymmetric ТУ deviation is not reproduced: "
                    "+%.4f / -%.4f against the printed +0,06 / -0,04"
                    % (up, dn))

    c32 = next(p for p in FP.FILM_PROFILES if p.name == "SVEMA_CND_32")
    lo = FS.resolve_batch_position(c32, -1.0)
    print("  Фото ЦНД-32 at -1: green gamma %.3f (lands ON the floor -- ГОСТ "
          "prints «0,60 + 0,08», one-sided), red %.3f and blue %.3f move too"
          % (lo.curves.g.gamma, lo.curves.r.gamma, lo.curves.b.gamma))
    if abs(lo.curves.g.gamma - 0.60) > 1e-9:
        fail.append("Фото ЦНД-32's green gamma at -1 is %.6f, not the printed "
                    "floor 0.60 of «0,60 + 0,08»" % lo.curves.g.gamma)
    if abs(lo.curves.r.gamma - c32.curves.r.gamma) < 1e-9:
        fail.append("Фото ЦНД-32's red gamma did NOT move toward -1; its cell "
                    "is two-sided and should")

    if fail:
        print("\n".join(["", "FAILURES:"] + ["  " + f for f in fail]))
        return 1
    print("\n[OK] batch_position_parity.py -- Python, scalar and AVX2 agree on "
          "%d stocks x %d positions; the OFF path returns the base object in "
          "all three" % (len(names), len(POSITIONS)))
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=None)
    ap.add_argument("--assert", dest="do_assert", action="store_true")
    a = ap.parse_args()
    if a.root:
        os.environ["FILMSIM_ROOT"] = a.root
    return run(a.do_assert)


if __name__ == "__main__":
    raise SystemExit(main())
