"""
C++ table generation for the film profile database.

Emits ``film_profiles.hpp`` / ``film_profiles.cpp`` mirroring the Python
dataclasses one-for-one, so a C++ renderer consumes exactly the same physical
parameters the Python reference implementation used. Nothing here computes
anything -- it is a serialiser, and the Python side stays the single source of
truth.

Notes carried over from earlier revisions, still true:

* ``features`` is a real ``enum class`` bitmask, not a string. The old string
  form invited ``features.find("HALATION")``, which also matches
  ``HAS_BLUE_HALATION`` -- a live bug in the original script.
* Every field carries its physical unit in the comment, because a bare
  ``float freq_r`` is impossible to use correctly without knowing whether it is
  pixels, micrometres or cycles per millimetre.
* The header ships the reference formulae for the characteristic curve, the
  MTF and the grain spectrum, so a C++ port cannot silently diverge from the
  Python implementation.

Schema version 2 additions (2026-07 domain review):

* New structs TemporalSpec / ReciprocitySpec / AgingSpec / Provenance and the
  calibration metadata fields on FilmProfile; extended GrainSpec, MTFSpec,
  PrintStock and FilmFormat. All appended after the existing fields, so the
  aggregate initialiser order of the v1 prefix is unchanged.
* Floats are emitted with ``np.format_float_positional(np.float32(x),
  unique=True)`` -- the shortest decimal that round-trips through float32 --
  instead of the previous 6-significant-digit ``%.6g`` (audit finding PY-01,
  which truncated values such as 3.321928).
* Every emitted profile literal is preceded by a data-source comment block
  (official document title, publisher and year from Provenance.sources, plus
  the evidence tier), so the generated .cpp is auditable without the Python
  side. Print stocks get a one-line equivalent.

Requires Python 3.12+ and numpy (for exact float32 literal formatting).
"""

import re
from pathlib import Path

import numpy as np

from film_profiles import (
    PERFS_PER_FRAME,
    FILM_PROFILES,
    FORMAT_GEOM,
    PRINT_STOCKS,
    SCHEMA_VERSION,
    Feature,
    FilmProfile,
    PrintStock,
    StockKind,
    ToneCurve,
)

__all__ = ["generate"]


HPP_TEMPLATE = """\
// Generated by cpp_codegen.py -- do not edit by hand.
// Physical film stock parameters. Regenerate after changing film_profiles.py.
//
// generated: @GENERATED@
// schema_version @SCHEMA_VERSION@ (v2: 2026-07 domain review; v3: 2026-08
// spectral sensitivity curves; v4: CoatingSpec + default_vignette -- coating
// unevenness in web coordinates, gate buckling, narrow-gauge edge fog;
// v5: InterimageSpec -- cross-layer development inhibition).
// Mirrors film_profiles.SCHEMA_VERSION; see
// kSchemaVersion below.
//
// FEATURE FLAGS ARE DERIVED AND NON-AUTHORITATIVE (DM-20). The Feature
// bitmask is a convenience summary of the numeric fields for UI and tooling.
// A renderer must key its behaviour on the numeric fields themselves
// (halation gains, coupler strengths, has_reseau, ...), never on the flags.
// The Python validate_all() only warns on flag/numeric disagreements.
//
// Densitometry (DM-06/DM-18): every curve and granularity figure is expressed
// in the metric named by its density_metric field -- "status_m" for colour
// negative, "status_a" for colour reversal and print stocks, "visual_iso"
// for B&W silver. Do not mix metrics when comparing stocks.
//
// Trim semantics (DM-06): for reversal stocks the curve abscissa is
//     x = -log10(relative exposure) - trim.
// The stored trim is a *static* calibration value (currently 0.0 for every
// stock); the reference renderer refines it per render with a per-channel
// anchor solve (solve_anchors in film_sim.py), and a C++ port should do the
// same or accept mid-grey landing slightly off target.
//
// Reference formulae, so a C++ port cannot drift from the Python original:
//
//   Characteristic curve, with sp(x,k) = k*log1p(exp(x/k)):
//       D(x) = dmin + gamma * ( sp(x - toe_x, toe_k)
//                             - sp(x - shoulder_x, shoulder_k) )
//       negative stocks: x =  log10(relative exposure)
//       reversal stocks: x = -log10(relative exposure) - trim
//
//   Modulation transfer, f in cycles/mm (legacy Gaussian core; see MTFSpec
//   for the optional v2 tail term):
//       MTF(f) = exp(-ln2 * (f/f50)^2) * lift(f)
//       lift(f) = 1 + adjacency * (G(0.4*adjacency_um) - G(2.0*adjacency_um))
//       G(sigma_um) = exp(-2*pi^2 * (sigma_um/1000)^2 * f^2)
//
//   Grain power spectrum shape, f_hi = 1000/(2*clump_um):
//       H(f) = exp(-(f/f_hi)^2) * (1 + clump_gain*exp(-(f/(f_hi/6))^2)), H(0)=0
//     then scaled so that sigma(D) through a 48 um aperture equals
//     rms_granularity/1000 at density 1.0, and modulated per pixel by
//       sqrt(max(D - dmin, 0) + fog_grain)
//     (the legacy law; GrainSpec sigma_shape_* describes the v2 refinement).
//
//   All spatial quantities are converted to pixels with
//       px_per_mm = image_width_px / format_width_mm
//   which is what makes a profile look identical at any scan resolution.
#pragma once

#include <array>
#include <cmath>        // FilmGrainSigma(): std::sqrt
#include <cstdint>
#include <string>
#include <vector>

namespace film {

/// Data-model schema version, mirrored from film_profiles.SCHEMA_VERSION.
constexpr int kSchemaVersion = @SCHEMA_VERSION@;

/// Whether the developed film is a negative (needs printing) or already a
/// positive. Reversal stocks skip the print stage entirely.
enum class StockKind : std::uint8_t {
    Negative = 0,
    Reversal = 1
};

/// Optional per-stock behaviour. Bitmask: test with has(), never by name.
///
/// DERIVED AND NON-AUTHORITATIVE (DM-20): a summary of the numeric fields.
/// Renderers must key on the numeric fields, never on these flags.
enum class Feature : std::uint32_t {
    None               = 0,
    Halation           = 1u << 0,  ///< weak or absent anti-halation layer
    StrongDirCouplers  = 1u << 1,  ///< modern stock, strong inter-image effect
    UnevenEmulsion     = 1u << 2,  ///< loose QC, slow large-scale sensitivity drift
    OrthoResponse      = 1u << 3,  ///< reduced red sensitivity
    NoRemjet           = 1u << 4,  ///< remjet removed: extreme halation
    ThreeStrip         = 1u << 5,  ///< beam-splitter camera, three separate records
    TabularGrain       = 1u << 6,  ///< T-grain crystals rather than cubic
    MosaicReseau       = 1u << 7,  ///< additive colour via a physical filter grid
    NitrateBase        = 1u << 8   ///< cellulose nitrate support, pre-1951
};

inline Feature operator|(Feature a, Feature b) {
    return static_cast<Feature>(static_cast<std::uint32_t>(a) |
                               static_cast<std::uint32_t>(b));
}
inline bool has(Feature set, Feature flag) {
    return (static_cast<std::uint32_t>(set) &
            static_cast<std::uint32_t>(flag)) != 0u;
}

using Matrix3 = std::array<std::array<float, 3>, 3>;
using Vec3    = std::array<float, 3>;

/// One channel of a characteristic (Hurter-Driffield) curve. See the formula
/// block at the top of this file.
///
/// Monotonic provided shoulder_x > toe_x and shoulder_k <= 2 * toe_k.
/// For reversal stocks toe_x governs the *highlight* end, not the shadow end.
struct ToneCurve {
    float dmin;        ///< base + fog density, dimensionless
    float gamma;       ///< straight-line slope, density per decade of exposure
    float toe_x;       ///< toe position, in the curve's own x units
    float toe_k;       ///< toe softness
    float shoulder_x;  ///< shoulder position
    float shoulder_k;  ///< shoulder softness

    /// Asymptotic maximum density.
    float dmax() const { return dmin + gamma * (shoulder_x - toe_x); }
    /// Exposure range between toe and shoulder, in stops.
    float latitudeStops() const { return (shoulder_x - toe_x) * 3.321928f; }
};

/// Three characteristic curves, one per dye layer. Their divergence in the toe
/// and shoulder (crossover) is what produces a stock's colour signature -- it
/// is the real mechanism behind "Fuji cyan shadows", not an output tint.
struct RGBCurves {
    ToneCurve r;
    ToneCurve g;
    ToneCurve b;
};

/// Silver-halide grain description. Grain variance scales as sqrt(density)
/// because developed crystal counts are Poisson distributed; the renderer
/// applies that, this struct describes the emulsion.
///
/// Schema-v2 fields (DM-09/DM-10) follow the v1 block; their defaults in the
/// database were chosen so that ignoring them reproduces v1 output exactly.
struct GrainSpec {
    float rms_granularity;  ///< sigma(D)*1000 through a 48 um aperture at D=1.0
    float clump_um_r;       ///< mean developed clump diameter, micrometres
    float clump_um_g;       ///< micrometres
    float clump_um_b;       ///< micrometres
    float clump_gain;       ///< low-frequency lobe: cubic ~1.0, tabular ~0.2
    float fog_grain;        ///< grain floor at zero exposure, fraction of D=1.0
    float anisotropy;       ///< vertical/horizontal correlation, 1.0 = isotropic
    // -- schema v2 ----------------------------------------------------------
    float rms_r;            ///< per-channel RMS, same metric as rms_granularity;
                            ///< 0 = use rms_granularity (v1 rule). Colour
                            ///< negative: b ~1.3x, r ~1.1x of green. [tier 2]
    float rms_g;            ///< 0 = use rms_granularity
    float rms_b;            ///< 0 = use rms_granularity
    float sigma_shape_toe;  ///< sigma multiplier at D = dmin. The triple
                            ///< (0,1,0) means "legacy sqrt(D-dmin) law".
                            ///< CORRECTED 2026-08-17: colour NEGATIVES turn
                            ///< over too -- the four KODAK VISION3 sheets trace
                            ///< to 0.39-0.67 / 1.00 / 0.55-0.63, i.e. sigma
                            ///< FALLS to ~0.58 of its D=1.0 value by dmax, four
                            ///< sheets agreeing within +/-7 %. Kodak's SMPTE
                            ///< Journal July 1985 paper (Sehlin, Kennel et al.,
                            ///< p 728, Figs 8-9) prints the same: "overexposing
                            ///< either film significantly decreases
                            ///< granularity". So a turning-over triple is NOT a
                            ///< reversal signature; reversal (~0.7/1.0/0.5)
                            ///< differs in the REASON, not the direction.
                            ///< Those four stocks are [tier 1], traced from the
                            ///< vendor plot; all other triples stay [tier 3].
                            ///< Known limit: sigma peaks at D ~ 0.78, BELOW the
                            ///< mid anchor, at 1.24-1.32x the D=1.0 value, and
                            ///< three anchors cannot carry an interior peak --
                            ///< the triple understates the maximum by ~1/4.
                            ///< RESOLVED in schema v8 -- see sigma_shape_peak.
    float sigma_shape_mid;  ///< sigma multiplier at D = 1.0
    float sigma_shape_dmax; ///< sigma multiplier at D = dmax
    // -- schema v8 (2026-08-18, queue item C1) ------------------------------
    float sigma_shape_peak;    ///< the INTERIOR maximum multiplier; 0 = none.
                               ///< Measured against seven sigma(D) samples per
                               ///< VISION3 sheet, the carrier forms score:
                               ///< legacy sqrt law 245 % max error, three
                               ///< anchors 41 %, three anchors + this peak 20 %,
                               ///< a 12-sample array 3.8 %. The array wins on
                               ///< paper and is over-parameterised against seven
                               ///< measured points, so two floats buy most of
                               ///< the available accuracy at no structural cost.
    float sigma_shape_peak_at; ///< absolute density of that maximum; 0 = none
    float sigma_shape_toe_at;  ///< absolute density of the TOE anchor as traced;
                               ///< 0 = use the curve's dmin. It is NOT the same
                               ///< number: on the VISION3 sheets the granularity
                               ///< plot's own plateau reads a mean +0.051 D above
                               ///< the sensitometric dmin, which Kodak's footnote
                               ///< explains ("produced on different equipment").
    float sigma_shape_dmax_at; ///< absolute density of the DMAX anchor as traced
                               ///< (where the trace stopped, not the curve
                               ///< model's asymptote); 0 = use the curve's dmax
    bool  sigma_shape_measured; ///< ⚠ WHETHER A RENDERER MAY USE THE SHAPE.
                               ///< false for 150 of the 155 stocks, and that is
                               ///< deliberate: the Python generator fills the
                               ///< anchors heuristically for 137 profiles and
                               ///< BOTH branches of that heuristic are known
                               ///< wrong in SIGN (colour negative gets rising
                               ///< where four vendor sheets say falling;
                               ///< reversal gets falling where EKTACHROME 100D
                               ///< 5285's sheet says rising ~20-fold). Honour
                               ///< the shape only when this is true; otherwise
                               ///< use the legacy law. FilmGrainSigma() below
                               ///< does exactly that.
    float size_sigma_log;   ///< log-normal grain-size dispersion: 0.35 typical
                            ///< cubic, 0.55 fast/pushed, 0.25 T-grain. [tier 3]
    float cluster_um;       ///< super-clump correlation length, um; 0 = disabled
    float dye_cloud_um;     ///< dye-cloud diameter, um; 0 for B&W silver,
                            ///< ~1.5-2.5 for colour stocks. [tier 2]
};

/// Grain-sigma multiplier at a given density -- THE ONE DEFINITION (schema v9).
///
/// Mirrors film_profiles.grain_sigma() exactly. If the two ever disagree, the
/// C++ render and the Python reference render different grain, which is the kind
/// of divergence that is very hard to see and very hard to explain, so keep them
/// in step or delete one of them.
///
/// Returns 1.0 at NET density 1.0 -- that is, at absolute density dmin + 1.0 --
/// by construction, for both laws below. That is what makes
/// GrainSpec::rms_granularity mean the figure the datasheets print. The
/// convention is printed on the sheets themselves: "Read at a NET diffuse visual
/// density of 1.0, using a 48-micrometre aperture" (Kodak 5248 p1, 5222 p1).
///
/// TWO LAWS, chosen by the data and not by the caller:
///   * sigma_shape_measured == true -> piecewise-linear through the stored
///     anchors, HELD FLAT outside the traced range. Extrapolating a traced curve
///     past its own endpoints turns a measurement into an invention; holding it
///     flat says "we stop knowing here", which is true. NOTE the stored anchors
///     are ratios to the ABSOLUTE 1.0 value, because that is how they were
///     traced; this function re-bases them to net 1.0 itself.
///   * otherwise -> the legacy sqrt(max(D - dmin, 0) + fog_grain) law, divided by
///     sqrt(1 + fog_grain). 144 of the 155 stocks take this path.
///
/// ⚠ CALLING CONVENTION -- CHANGED 2026-08-18 (queue item C1b), READ THIS.
/// Multiply this result by the stock's rms field and NOTHING ELSE. Earlier
/// revisions of this header told an existing renderer to multiply by its own
/// sqrt(D - dmin + fog) evaluated at D = 1.0, to preserve the pre-C1b level; that
/// instruction is now WRONG and applying it double-counts the correction. The
/// factor it preserved was the legacy law's value at ABSOLUTE 1.0, which for a
/// masked colour negative is net 0.42 in green and net 0.16 in blue -- a shadow,
/// not the midtone the datasheet figure is measured at.
inline float FilmGrainSigma(const GrainSpec& g, float dmin, float dmax, float D)
{
    if (g.sigma_shape_measured && g.sigma_shape_mid > 0.0f) {
        const float dToe = (g.sigma_shape_toe_at > 0.0f) ? g.sigma_shape_toe_at : dmin;
        const float dTop = (g.sigma_shape_dmax_at > 0.0f) ? g.sigma_shape_dmax_at : dmax;
        const float dRef = dmin + 1.0f;      // NET density 1.0 -- see the note above
        if (dTop > dToe && dRef < dTop) {
            // At most four anchors, kept sorted by density. Small and fixed, so
            // an insertion sort is both clearer and faster than anything general.
            float xs[4], ys[4];
            int n = 0;
            xs[n] = dToe;  ys[n++] = g.sigma_shape_toe;
            xs[n] = 1.0f;  ys[n++] = g.sigma_shape_mid;
            xs[n] = dTop;  ys[n++] = g.sigma_shape_dmax;
            if (g.sigma_shape_peak > 0.0f && g.sigma_shape_peak_at > 0.0f) {
                xs[n] = g.sigma_shape_peak_at;  ys[n++] = g.sigma_shape_peak;
            }
            for (int i = 1; i < n; ++i) {
                const float kx = xs[i], ky = ys[i];
                int j = i - 1;
                while (j >= 0 && xs[j] > kx) { xs[j+1] = xs[j]; ys[j+1] = ys[j]; --j; }
                xs[j+1] = kx; ys[j+1] = ky;
            }
            // held flat outside, linear inside -- and normalised at NET density
            // 1.0 (dmin + 1.0), which is the density Kodak's own footnote names
            // for the rms figure. The stored anchors are ratios to the ABSOLUTE
            // 1.0 value because that is how they were traced, so the reference is
            // recomputed here rather than baked into the data.
            float v = ys[n-1], mid = ys[n-1];
            if (D <= xs[0]) { v = ys[0]; }
            else {
                for (int i = 1; i < n; ++i) {
                    if (D <= xs[i]) {
                        const float t = (xs[i] > xs[i-1])
                                      ? (D - xs[i-1]) / (xs[i] - xs[i-1]) : 0.0f;
                        v = ys[i-1] + t * (ys[i] - ys[i-1]);
                        break;
                    }
                }
            }
            if (dRef <= xs[0]) { mid = ys[0]; }
            else {
                for (int i = 1; i < n; ++i) {
                    if (dRef <= xs[i]) {
                        const float t = (xs[i] > xs[i-1])
                                      ? (dRef - xs[i-1]) / (xs[i] - xs[i-1]) : 0.0f;
                        mid = ys[i-1] + t * (ys[i] - ys[i-1]);
                        break;
                    }
                }
            }
            return (mid > 0.0f) ? (v / mid) : v;
        }
    }
    // Legacy law, normalised at net density 1.0: dmin cancels in the
    // denominator, which is exactly why this correction carries no per-channel
    // term. den = sqrt(1 + fog).
    const float num = std::sqrt(((D - dmin) > 0.0f ? (D - dmin) : 0.0f) + g.fog_grain);
    const float den = std::sqrt(1.0f + g.fog_grain);
    return (den > 0.0f) ? (num / den) : num;
}

/// Per-layer modulation transfer. Blue is the top layer and therefore
/// sharpest; red sits at the bottom of the stack behind two layers of gelatin
/// and is the softest. That ordering is physical, not stylistic.
///
/// Schema-v2 fields (DM-11): datasheet resolving power (0 = not published --
/// deliberately not invented) and an optional non-Gaussian tail,
///   MTF(f) = a*exp(-ln2*(f/f50)^2) + (1-a)*exp(-(f/f50)^p)
/// with a = mtf_tail_a (1.0 = pure Gaussian legacy) and p = mtf_tail_f_exp.
struct MTFSpec {
    float f50_r;         ///< cycles/mm at 50% modulation
    float f50_g;         ///< cycles/mm
    float f50_b;         ///< cycles/mm
    float adjacency;     ///< development adjacency overshoot, 0 disables
    float adjacency_um;  ///< spatial scale of that overshoot, micrometres
    // -- schema v2 ----------------------------------------------------------
    float resolving_power_lp_mm_lowc;   ///< lp/mm at 1.6:1 TOC; 0 = unknown
    float resolving_power_lp_mm_highc;  ///< lp/mm at 1000:1 TOC; 0 = unknown
    // -- schema v10 (C2, 2026-08-19): the rolloff the renderer READS ----------
    float mtf_rolloff_q;    ///< exponent q in 1/(1+(f/f50)^q); 0 = not measured
    bool  mtf_measured;     ///< may a renderer use mtf_rolloff_q? See
                            ///< FilmMtfResponse() for why this gate exists.
    float mtf_tail_a;                   ///< Gaussian-core weight; 1.0 = legacy
    float mtf_tail_f_exp;               ///< tail exponent; 0.0 = unused
};

/// Modulation transfer at a spatial frequency -- THE ONE DEFINITION (schema v10).
///
/// Mirrors film_profiles.mtf_response() exactly; the same warning applies as for
/// FilmGrainSigma -- if the two drift, the plugin and the reference render
/// different sharpness and nothing in a frame will say why.
///
/// channel: 0 = r, 1 = g, 2 = b.
///
/// TWO LAWS, chosen by the data:
///   * mtf_measured && mtf_rolloff_q > 0 -> 1/(1 + (f/f50)^q), adopted by
///     measurement. Scored against the 35 samples above 8 cycles/mm of the one
///     vector MTF curve traced from the corpus (PLUS-X 5231): power law rms
///     0.0375, single Gaussian 0.0878, the older mtf_tail_a/_f_exp form 0.0583.
///   * otherwise -> the legacy Gaussian exp(-ln2 (f/f50)^2), unchanged.
///
/// ⚠ BOTH LAWS PASS THROUGH 0.5 AT f50 EXACTLY. That is deliberate and it is what
/// makes this safe to switch per stock: turning a measured rolloff on changes the
/// SHAPE away from f50 and never the level at it. (Contrast the grain work, where
/// the two laws disagreed at the reference density and the level decision had to
/// be taken separately -- queue item C1b.)
///
/// Adjacency overshoot is NOT included here: it is a separate development effect,
/// applied by the renderer as a band-pass lift.
inline float FilmMtfResponse(const MTFSpec& m, int channel, float f)
{
    const float f50 = (channel == 0) ? m.f50_r : (channel == 2) ? m.f50_b : m.f50_g;
    if (f50 <= 0.0f) {
        return 1.0f;
    }
    const float x = f / f50;
    if (m.mtf_measured && m.mtf_rolloff_q > 0.0f) {
        return 1.0f / (1.0f + std::pow(x, m.mtf_rolloff_q));
    }
    return std::exp(-0.6931471805599453f * x * x);
}


/// Base-reflection glow. Must be added to linear exposure before the
/// characteristic curve, never to output pixels afterwards, and must conserve
/// energy: light scattered away from a point is removed from it.
struct HalationSpec {
    Vec3  radii_um;          ///< three Gaussian sigmas, micrometres, small to large
    Vec3  weights;           ///< relative energy, normalised by the renderer
    float gain_r;            ///< red penetrates deepest, so dominates
    float gain_g;
    float gain_b;
    float threshold_stops;   ///< soft knee position above mid grey
    // -- schema v11 (C21, 2026-08-23): PER-CHANNEL RADIUS SCALES ---------------
    // The gains already say how MUCH each record scatters; these say how FAR.
    // Every stock in the file ships 1.0, so a v11 database renders bit-identically
    // to a v10 one -- but the struct GREW, so a v10 reader would walk off the end
    // of every HalationSpec, which is why kSchemaVersion moved with it.
    // ⚠ WHY THEY ARE ALL 1.0 AND NOT "DERIVED FROM GEOMETRY": the base is
    // 100-150 um thick against an 11-16 um pack, so the path-length ratio between
    // the record nearest the base and the one furthest from it is about 1.1. A
    // geometry-derived set would therefore LOOK measured while moving a render by
    // roughly 1 %. What would fill these honestly is a per-channel edge trace
    // across a specular highlight; until then the renderer takes the shared-radius
    // fast path whenever all three are equal.
    float radius_scale_r;
    float radius_scale_g;
    float radius_scale_b;
};

/// Development-Inhibitor-Releasing coupler behaviour: raises saturation without
/// raising gamma, and adds a local adjacency edge effect. Zero for Kodachrome,
/// whose dyes were formed in the processing machine rather than in the film, and
/// zero for every pre-1950 stock because the chemistry did not exist yet.
struct CouplerSpec {
    float strength;       ///< cross-layer inhibition, 0 disables
    float radius_um;      ///< inhibitor diffusion distance, micrometres
    float edge_strength;  ///< short-range adjacency component
    float edge_um;        ///< micrometres
};

/// Additive colour filter grid ruled onto the film base (Dufaycolor and kin).
///
/// Not a variant of the layered model but a different imaging system: one
/// panchromatic emulsion behind a microscopic colour grid. Consequences the
/// layered path cannot express -- colour resolution capped by the grid pitch
/// rather than the emulsion, a single grain field with no inter-layer effects of
/// any kind, about two stops lost to filter absorption, and the grid itself
/// faintly visible as texture.
///
/// Geometry for pattern "dufay": continuous red lines with blue and green
/// squares chequered between them, each colour about a third of the area.
/// Applied to linear EXPOSURE (the light passes the grid before reaching the
/// emulsion); reconstructed at viewing time by a mask-weighted local average,
/// num = blur(record * mask_c), den = blur(mask_c), out_c = num / den.
///
/// Requires at least 3 pixels per cell to represent at all; below that the
/// reference implementation disables the mosaic and warns rather than emit
/// aliasing noise.
struct ReseauSpec {
    float lines_per_mm;   ///< grid pitch on the film
    /// What each filter passes: rows in R/G/B filter order, columns in R/G/B
    /// light order, so filter_matrix[0][1] is green light through the red filter.
    /// The off-diagonal terms are why additive colour looks pastel -- ruled
    /// gelatin filters have broad overlapping passbands. Model them as pure and
    /// the process comes out more saturated than Kodachrome, which is backwards.
    Matrix3 filter_matrix;
    std::string pattern;           ///< only "dufay" is defined
    float reconstruction_pitches;  ///< reconstruction blur radius, in grid pitches
};

/// Per-stock temporal behaviour for moving-image rendering (schema v2, DM-13).
///
/// ALL VALUES ARE TIER-3 ESTIMATES: era-typical figures for the camera /
/// printer / projector chain a stock normally passed through, not
/// measurements of a specific emulsion. Still renders ignore this struct.
struct TemporalSpec {
    float weave_amp_x_um;   ///< RMS horizontal gate weave, um on the negative
                            ///< (silent era ~20, 1950s ~10, modern ~3)
    float weave_amp_y_um;   ///< RMS vertical gate weave, micrometres
    float weave_hz_corner;  ///< corner frequency of the weave spectrum, Hz
    float flicker_pct;      ///< RMS exposure flicker, percent (early 4-6,
                            ///< 1950s ~1.5, modern ~0.2)
    float flicker_hz;       ///< corner frequency of the flicker spectrum, Hz
    float grain_frame_correlation;      ///< 0 = fresh grain field every frame
    float dirt_events_per_frame;        ///< expected visible dirt events/frame
    float scratch_persistence_frames;   ///< mean running-scratch lifetime
    float fps_native;       ///< native shooting/projection frame rate
};

/// Which development condition the stored curve represents (schema v6,
/// 2026-08-14). DESCRIPTIVE ONLY -- nothing in the renderer reads this.
///
/// Every characteristic curve in this database is the curve for ONE processing
/// condition, and until schema v6 nothing recorded which. The size of that
/// ambiguity is measurable: for Ilford Pan F the manufacturer publishes six
/// development conditions spanning ASA 32 to ASA 80 and contrast index 0.55 to
/// 0.70 -- 1 1/3 stops of speed and 27 percent of contrast, all of them correct
/// for the same film. A curve with no processing statement is therefore
/// ambiguous by more than a stop.
///
/// Empty strings and zeros mean NOT STATED BY THE SOURCE, which is the honest
/// value for most stocks: datasheets usually print a curve without naming the
/// developer, and inventing one would be fabrication.
struct ProcessingSpec
{
    std::string developer;      ///< as printed, e.g. "ID-11"; "" = not stated
    std::string dilution;       ///< as printed, e.g. "1+1"; "" = not stated
    float       minutes;        ///< 0.0 = not stated
    float       celsius;        ///< 0.0 = not stated
    std::string agitation;      ///< e.g. "intermittent"; "" = not stated
    /// Contrast-index aim the time targets. 0.0 = not stated. NOT automatically
    /// equal to the curve's gamma: contrast index is an average gradient over a
    /// stated log-exposure interval, gamma is a straight-line slope.
    float       contrast_index;
};


/// Schwarzschild reciprocity failure (schema v2, DM-07). Effective exposure
/// past onset: E_eff = I * t^p, p <= 1. p = 1.0 means no failure (correct for
/// normal cine exposure times and the v1 behaviour). Tier-2/3 estimates
/// except where a datasheet documents them (Acros: no correction to 120 s).
struct ReciprocitySpec {
    float schwarzschild_p_r;  ///< per-channel exponent; 1.0 = no failure
    float schwarzschild_p_g;
    float schwarzschild_p_b;  ///< channel spread = long-exposure colour cast
    float onset_s;            ///< seconds below which no correction applies
};

/// Storage-age damage model (schema v2, DM-01). ALL ZEROS = FRESH STOCK.
/// Data hooks only for now: every profile ships fresh and the reference
/// renderer does not yet consume this struct.
struct AgingSpec {
    float dye_fade_c;          ///< fractional cyan dye fade, 0-1
    float dye_fade_m;          ///< magenta (usually survives longest)
    float dye_fade_y;          ///< yellow
    float base_yellowing_d;    ///< base yellowing, blue-density lift
    float dmin_lift;           ///< uniform fog growth, density
    float shrinkage_pct;       ///< base shrinkage, percent
    float scratch_rate_base_per_m;      ///< base-side scratches per metre
    float scratch_rate_emulsion_per_m;  ///< emulsion-side scratches per metre
    float dust_area_ppm;       ///< dust coverage, ppm of frame area
    float mottle_amplitude;    ///< storage mottle amplitude, density fraction
    float mottle_scale_mm;     ///< storage mottle spatial scale, millimetres
};

/// Sampled spectral sensitivity curves digitised from manufacturer datasheet
/// plots (schema v3). Empty vectors = no digitised data; consumers must fall
/// back to spectral_weights / taking_matrix (the v2 behaviour).
///
/// Values are RELATIVE log10 sensitivity, peak-normalised so each populated
/// layer's maximum is exactly 0.0; linear relative sensitivity = 10^value.
/// The sentinel -4.0 means "at or below the measurement floor of the source
/// plot". Wavelength of sample i = lambda_start_nm + i * lambda_step_nm;
/// all populated layers of one stock share one grid, but grid length varies
/// per stock (IR stocks extend past 800 nm).
///
/// log_s_r/g/b are the SENSITIVE LAYERS (red-sensitive / cyan-forming,
/// green-sensitive / magenta-forming, blue-sensitive / yellow-forming), not
/// output channels. Monochrome and reseau stocks fill log_s_pan only.
///
/// Representation note: std::vector<double> rather than std::array or float.
/// Vector because grid length is per stock (a fixed-size array would force
/// padding); double because these tables are generated offline where storage
/// is free, so the transcription is preserved beyond any question of literal
/// rounding -- while measurement accuracy (+/-0.05..0.1 log, stated per
/// stock in `source`) remains the true precision bound. Treat instances as
/// immutable after load (e.g. hold them const).
///
/// `criterion` names the source plot's y-axis convention (the sheets differ):
/// "relative_log", "log_reciprocal_erg_cm2_D0.2_above_dmin",
/// "iso_speed_D0.3_above_fog", "relative_linear_assumed".
/// `source` is the full citation: author/publisher, document title and code,
/// and the ORIGINAL release date of the document; Russian-language sources
/// keep the original title with an English translation alongside.
/// Cross-layer development inhibition -- interimage effects (schema v5).
///
/// Developing silver in one layer releases inhibitor. It diffuses two ways,
/// and the two directions are two visible effects from one chemistry:
/// LATERALLY within a layer -> edge effects and micro-contrast, already
/// modelled as CouplerSpec; VERTICALLY into the neighbours -> this struct.
///
/// Model, applied to log exposure before the characteristic curve:
///     logE_i' = logE_i + sum_{j != i} a_ij * (D_j - d_ref_j)
/// Off-diagonals are NEGATIVE (inhibition); the diagonal is structurally zero
/// because a layer's effect on itself is already inside its own curve.
/// Referencing to the mid-grey density d_ref is what makes this a COLOUR
/// effect and not a tone effect: on a neutral every (D_j - d_ref) is ~0, the
/// correction vanishes, and the grey scale is untouched -- while a saturated
/// colour, where the layers disagree, develops against unequal inhibition and
/// separates further. Saturation rising WITHOUT gamma rising is precisely
/// what no per-channel curve can produce, and it is the core of why Portra
/// holds skin separation and Velvia saturates as it does.
///
/// The equation is implicit, so it is solved by fixed-point iteration seeded
/// with the uncorrected densities. Each pass costs a full curve evaluation
/// per channel and the curve stage is the most expensive in the chain, hence
/// `iterations` being data rather than a hardcoded loop. 1 captures most of
/// the effect; 0 disables the stage.
///
/// PROVENANCE: tier 3 throughout, unavoidably. A 395-document datasheet
/// library was searched on 2026-08-03 and NO manufacturer sheet publishes
/// interimage data -- the omission is systematic, because camera negative is
/// characterised with a single white-light exposure series and the
/// colour-separation series that would reveal these effects is only printed
/// for print stocks. The one authoritative quantification located is a
/// citation, not a document in hand: Gschwind, Rosselet and Buser,
/// "Investigation and quantification of inter-image effects", J. Photographic
/// Science 41 (1993), p. 86. To measure: neutral step wedge plus the same
/// wedge through red (W25), green (W58) and blue (W47B) filters on one roll,
/// with an empty-gate reference.
struct InterimageSpec {
    double a_rg;  ///< green layer's development inhibiting the red layer
    double a_rb;  ///< blue  layer -> red   layer (far pair, weaker)
    double a_gr;  ///< red   layer -> green layer
    double a_gb;  ///< blue  layer -> green layer
    double a_br;  ///< red   layer -> blue  layer (far pair, weaker)
    double a_bg;  ///< green layer -> blue  layer
    int    iterations;  ///< fixed-point passes; 0 disables
    /// Where along the curve the coupling acts. 0 = uniformly, the
    /// negative-film case (US4729943A: interimage effects "are always
    /// obtained during chromogenic development"). Above 0 the correction is
    /// scaled by the neighbouring layer's density relative to the mid-grey
    /// reference, concentrating it in dense areas -- the reversal case, whose
    /// effects come from iodide released in the FIRST black-and-white
    /// developer and land in "high dye-density areas". Normalised at mid grey,
    /// so a neutral stays untouched under either mechanism.
    double density_weighting;

    bool active (void) const noexcept {
        return iterations > 0
            && (a_rg != 0.0 || a_rb != 0.0 || a_gr != 0.0
                || a_gb != 0.0 || a_br != 0.0 || a_bg != 0.0);
    }
};


/// Emulsion coating and camera-gate defects (schema v4).
///
/// The geometry is the whole point and the easiest thing to get wrong. Film is
/// coated as a web up to ~1.4 m wide and slit into strips afterwards; the
/// coating machine has no idea where frame boundaries will fall, because the
/// camera gate decides that later. So coating thickness variation CANNOT
/// produce a defect locked to frame corners -- that is the lens
/// (default_vignette). In WEB coordinates it produces:
///   * across the web (the frame's HORIZONTAL axis on 35 mm): streaks at fixed
///     x, laid down by fixed hopper hardware, identical on every frame of the
///     roll -- these do not flicker;
///   * along the web (vertical): the film advances one frame pitch per frame,
///     so each frame samples a different stretch. This is the one real
///     emulsion-driven frame-to-frame blink -- spatially smooth and sliding,
///     never white noise.
/// Hence two correlation lengths, and hence a renderer that advances the field
/// by the format's frame pitch instead of redrawing it. A consequence worth
/// knowing: because 8 mm advances only ~0.45 correlation lengths per frame
/// while 35 mm advances ~2.2, the same emulsion reads as slow drifting mottle
/// on 8 mm and as per-frame mottle on 35 mm.
struct CoatingSpec {
    /// RMS fractional sensitivity variation, 0.035 = 3.5 % one sigma.
    /// 0 disables the coating field. QC-driven, NOT date-driven: trough
    /// coating (pre-1950s) was worst, slide/extrusion hoppers (1950s) much
    /// better, multi-slot simultaneous (1970s+) better again -- but Soviet,
    /// GDR and budget plants lagged by decades and some show it to this day.
    double coating_sigma;
    double coating_corr_across_mm;  ///< correlation length across the web, mm
    double coating_corr_along_mm;   ///< correlation length along the web, mm
    /// Fraction of f50 lost at the frame corners from film buckling in the
    /// gate: the pressure plate holds the centre flat while a curling base
    /// lifts the corners out of the focal plane. Corner SOFTNESS, never corner
    /// darkening -- the two are constantly conflated and are different
    /// mechanisms. Driven by base stiffness (thick nitrate and early acetate
    /// curl; modern PET does not) times gate size, so small gauges suffer
    /// worst and for longest.
    double buckle_mtf_loss;
    /// Extra density at the film edge: light leaking past the edge of the roll
    /// plus development edge effects. Purely a GAUGE matter, not an era one --
    /// Standard 8 is 16 mm slit down the middle after processing, so its frame
    /// sits at the film edge permanently, while 35 mm margins carry the
    /// perforations and get trimmed away.
    double edge_fog_density;
    double edge_fog_mm;             ///< decay length inward from the edge, mm

    bool hasCoatingField (void) const noexcept { return coating_sigma > 0.0; }
    bool hasBuckle       (void) const noexcept { return buckle_mtf_loss > 0.0; }
    bool hasEdgeFog      (void) const noexcept {
        return edge_fog_density > 0.0 && edge_fog_mm > 0.0;
    }
};


struct SpectralSensitivity {
    double lambda_start_nm;
    double lambda_step_nm;
    std::vector<double> log_s_r;
    std::vector<double> log_s_g;
    std::vector<double> log_s_b;
    std::vector<double> log_s_pan;
    std::string criterion;
    std::string source;

    bool hasData() const {
        return !log_s_pan.empty()
            || (!log_s_r.empty() && !log_s_g.empty() && !log_s_b.empty());
    }
};

/// Where a profile's numbers come from (schema v2, DM-19). Machine-readable
/// form of the [T1]/[T2]/[T3] tags in the descriptions.
struct Provenance {
    int tier;  ///< 1 datasheet-grounded, 2 partially grounded, 3 reconstruction
    std::vector<std::string> sources;  ///< full citations, "Document title,
                                       ///< Publisher, year"; or an explicit
                                       ///< "No official manufacturer
                                       ///< datasheet available" placeholder
    std::string fitted_from;   ///< "datasheet_curve"|"secondary_sources"|"analogy"
    std::string last_reviewed; ///< ISO date of the last data review
};

/// -- schema v7 (2026-08-16): four INERT data carriers -----------------------
///
/// STORAGE ONLY. Nothing in the renderer reads any of these, by design: the
/// risk in this data was never in carrying it but in wiring it in, where dye
/// density curves in particular would change every colour image. Wiring is a
/// separate, individually reviewed stage. Populating these fields must leave
/// rendered output bit-identical, and a verify.py guard asserts exactly that.

/// Spectral density of the developed image dyes. Printed on every Kodak and
/// Fuji colour sheet; currently approximated project-wide by the 3x3
/// dye_matrix, which cannot express an off-band unwanted absorption.
/// Densities are as printed, NOT normalised -- absolute level is meaningful.
struct SpectralDyeDensity {
    double lambda_start_nm;
    double lambda_step_nm;
    std::vector<double> d_cyan;
    std::vector<double> d_magenta;
    std::vector<double> d_yellow;
    std::vector<double> d_neutral;
    std::string normalisation;  ///< "peak_1.0"|"midscale_neutral"|"as_printed_status_a"
    std::string source;

    bool hasData() const {
        return !d_cyan.empty() && !d_magenta.empty() && !d_yellow.empty();
    }
};

/// Physical coating order and per-LAYER resolving power. Distinct from the
/// R/G/B records in MTFSpec: several 1950s films stack their layers
/// unconventionally, so a per-layer measurement is meaningless without the
/// order stored beside it. `order` is top-to-bottom by sensitisation.
struct LayerStack {
    std::vector<std::string> order;   ///< permutation of "blue","green","red"
    double resolving_top;             ///< lines/mm, layers in `order`
    double resolving_mid;
    double resolving_bot;
    std::string test_object_contrast;
    std::string source;

    bool hasData() const { return !order.empty(); }
};

/// One (developer, dilution, time, temperature) -> contrast measurement.
struct DevelopmentPoint {
    std::string developer;
    std::string dilution;
    double minutes;
    double celsius;
    double contrast_index;
    double gamma;
    int    exposure_index;
};

/// The whole published processing axis, not the single condition recorded in
/// ProcessingSpec. Flat array so no developer name needs to become an enum.
struct ProcessingFamily {
    std::vector<DevelopmentPoint> points;
    std::string source;

    bool hasData() const { return !points.empty(); }
};

/// Measured reciprocity correction against exposure time. ReciprocitySpec
/// holds one Schwarzschild exponent, which is exact for Ilford (they publish
/// Ta = Tm^k) but provably insufficient for Kodak, whose effective exponent
/// walks from ~0.85 to ~0.70 across successive decades. A populated
/// cc_filters entry documents CHROMATIC failure; its absence, achromatic.
struct ReciprocityTable {
    std::vector<double> times_s;
    std::vector<double> stops_correction;
    std::vector<std::string> cc_filters;
    std::string source;

    bool hasData() const { return !times_s.empty(); }
};

/// One measured unwanted/useful density ratio. Soviet TU specifications print
/// these as K with a superscript naming the DYE and a subscript naming the
/// MEASURING BAND, i.e. the off-diagonal structure of a dye-crosstalk matrix,
/// measured rather than assumed. NEGATIVE VALUES ARE LEGAL: LN-8 prints
/// "minus 0.05-0.10" for magenta in blue, an interlayer effect, not an error.
struct DyeImpurityRatio {
    std::string dye;        ///< "y"|"m"|"c"
    std::string band;       ///< "b"|"g"|"r"
    double lo;
    double hi;
    std::string criterion;  ///< distinguishes two criteria for one dye/band pair
};

/// Measured dye crosstalk as named ratios. The renderer's dye_matrix is built
/// from a single saturation scalar and cannot express independent measured
/// terms; this carries them losslessly. INERT -- nothing reads it.
struct DyeImpurity {
    std::vector<DyeImpurityRatio> ratios;
    std::string source;

    bool hasData() const { return !ratios.empty(); }
};

/// Complete film stock.
struct FilmProfile {
    std::string name;
    std::vector<std::string> aliases;  ///< catalogue numbers and common names
    std::string description;
    std::string era;
    StockKind kind;
    bool  is_monochrome;      ///< single silver image instead of three dye layers
    int   exposure_index;     ///< ISO / EI rating
    int   balance_kelvin;     ///< colour temperature the stock is balanced for
    RGBCurves    curves;
    GrainSpec    grain;
    MTFSpec      mtf;
    HalationSpec halation;
    CouplerSpec  couplers;
    /// 3x3 applied to *linear exposure*: the spectral sensitivity of each
    /// record. Identity for an integral tripack; strongly off-diagonal for a
    /// Technicolor beam-splitter camera, whose broad overlapping taking filters
    /// are the origin of its famous reds. It must be applied before the
    /// characteristic curve -- the curve is nonlinear, so a later matrix cannot
    /// reproduce it.
    Matrix3 taking_matrix;
    /// 3x3 applied to the *density* vector: impure dye absorption plus scanner
    /// crosstalk. Negative off-diagonals sharpen colour separation
    /// (Kodachrome, Technicolor imbibition dyes); positive off-diagonals muddy
    /// it (ORWOcolor). Row-major, near identity.
    Matrix3 dye_matrix;
    /// Scene RGB to single-layer exposure weights for monochrome stocks.
    /// NOT video luma -- panchromatic film has its own spectral sensitivity,
    /// which is why B&W renders red dark and blue sky light.
    Vec3 spectral_weights;
    /// Residual film base cast after printer lights neutralise the mask.
    Vec3 base_tint;
    /// RMS channel registration error on the negative, micrometres, so it
    /// scales with resolution like every other spatial quantity. Tens of
    /// micrometres for three-strip Technicolor: hence its coloured fringing.
    float misregistration_um;
    /// Print stock used when the caller does not choose one. Ignored for
    /// reversal stocks.
    std::string default_print;
    /// Gauge this stock was sold on. Used when the host does not specify one.
    /// Every spatial quantity here is physical (um, cycles/mm), so this is the
    /// number that converts emulsion physics into pixels.
    std::string default_format;
    /// True if this stock uses an additive colour filter grid, in which case
    /// `reseau` is meaningful and the layered colour path does not apply.
    bool has_reseau;
    ReseauSpec reseau;
    /// Veiling flare fraction of the *lens* normally used with this stock, not a
    /// property of the emulsion. Uncoated pre-1940 glass scattered 6-14% of
    /// incoming light into a broad haze across the frame; anti-reflection
    /// coating cut that below 1%. Stored here because era of stock and era of
    /// glass go together in practice. It lifts the black floor and compresses
    /// contrast globally, and nothing in the emulsion model substitutes for it:
    /// without it a 1930s stock still renders with modern blacks.
    /// Monochrome image tone: >0 warm/brown-black, <0 cool/blue-black.
    /// Applied after the printer-light solve, weighted toward the light tones.
    float silver_tone;
    float default_flare;
    /// Corner falloff of the LENS typically used with this stock, in stops.
    /// A lens property, deliberately NOT part of CoatingSpec: cos^4(theta) is
    /// geometry and applies in every era. Emulsion coating variation cannot
    /// produce a frame-corner-locked defect at all -- film is coated as a wide
    /// web and slit afterwards, so the coating never knew where the frames
    /// would fall.
    float default_vignette;
    Feature features;  ///< DERIVED, non-authoritative -- see enum note
    // -- schema v2 (2026-07 domain review) ------------------------------------
    TemporalSpec    temporal;     ///< gate weave / flicker / dirt (tier 3)
    ReciprocitySpec reciprocity;  ///< Schwarzschild failure (tier 2/3)
    AgingSpec       aging;        ///< storage damage hooks; all zeros = fresh
    // -- schema v6 (2026-08-14) ----------------------------------------------
    /// Manufacturer exposure index under TUNGSTEN where the source prints one
    /// alongside the daylight figure; 0 = not stated. NOT redundant with
    /// exposure_index: for a monochrome film the pair states the emulsion's
    /// spectral weighting. Measured across this database, ordinary
    /// panchromatic stocks sit at a ratio near 1.25, ILFORD_HP4 is flat at
    /// 1.00, and the blue-sensitive-only POLAROID_51 is 3.2.
    int32_t         exposure_index_tungsten;
    ProcessingSpec  processing;   ///< development condition of the curve
    Provenance      provenance;   ///< sources and confidence tier
    /// Static reversal exposure trim in x = -log10(E) - trim. 0.0 for every
    /// stock: the reference renderer solves per-channel trims per render.
    float trim;
    /// Densitometry of the curve/grain numbers: "status_m" (colour negative),
    /// "status_a" (colour reversal), "visual_iso" (B&W silver).
    std::string density_metric;
    /// "scan" when calibrated against the SCAN_DI transform, "print" when the
    /// default_print is a real print stock (Technicolor).
    std::string referred;
    /// Curve-abscissa position of metered mid-grey. 0.0 = mid grey at
    /// logE = 0, the convention the reference renderer bakes in.
    float speed_point_x;
    /// How exposure_index was assigned: "iso6" (B&W), "iso5800" (colour
    /// negative), "iso2240" (colour reversal), "manufacturer_ei" (historic).
    std::string speed_criterion;
    /// Orange-mask encoding: "dmin_ladder" (per-channel dmin IS the mask,
    /// r << g << b), "neutral_dmin" (mask in base_tint/dye data), "none"
    /// (B&W and reversal). Documents the audit split; render output unchanged.
    std::string mask_encoding;
    /// Callier coefficient (specular/diffuse density seen by a condenser):
    /// 1.0 dye images, ~1.3 B&W silver negative, ~1.25 B&W reversal.
    float callier_q;
    // -- schema v3 (2026-08) --------------------------------------------------
    /// Digitised spectral sensitivity; empty = fall back to spectral_weights
    /// / taking_matrix. See the struct documentation above.
    SpectralSensitivity spectral;
    // -- schema v4 (2026-08-03) ----------------------------------------------
    /// Coating field / gate buckling / edge fog. All zeros = clean modern
    /// stock in a well-designed gate: the renderer skips every one of them.
    CoatingSpec coating;
    // -- schema v5 (2026-08-03) ----------------------------------------------
    /// Cross-layer interimage effects. All zeros = the v4 behaviour exactly.
    InterimageSpec interimage;
    // -- schema v7 (2026-08-16), ALL INERT -----------------------------------
    /// Carried, validated and reported; never read by the renderer. Empty on
    /// every stock until the extraction batches fill them.
    SpectralDyeDensity dye_density;
    LayerStack         layer_stack;
    ProcessingFamily   processing_family;
    ReciprocityTable   reciprocity_table;
    DyeImpurity        dye_impurity;

    bool isReversal() const { return kind == StockKind::Reversal; }
};

/// Positive stock, or a digital-intermediate print-emulating transform.
/// System gamma is negative gamma times print gamma: ~0.6 * 1.75 for a scan
/// look, ~0.6 * 2.7 for a theatrical release print.
struct PrintStock {
    std::string name;
    std::string description;
    RGBCurves curves;
    float mtf_f50;         ///< cycles/mm, print plus scanner optics combined
    float grain_rms;       ///< print stock adds its own finer grain
    float grain_clump_um;  ///< micrometres
    Matrix3 dye_matrix;    ///< print dye impurity / gamut
    // -- schema v2 (DM-15): additive printer-light calibration ---------------
    float printer_light_r;   ///< lamp points; 25.0 = LAD-neutral mid-scale
    float printer_light_g;
    float printer_light_b;
    float log_e_per_point;   ///< logE per printer point (0.025 = 1/12 stop)
    std::string density_metric;  ///< print stocks are read in Status A
    // -- schema v7 (2026-08-17), INERT ------------------------------------
    /// Spectral dye density of the print dyes. Carried, never read.
    SpectralDyeDensity dye_density;

};

/// Film gauge geometry (schema v2, DM-17). width_mm is the v1 field; grain,
/// halation, MTF and registration scale from it plus the render width in px.
struct FilmFormat {
    std::string name;
    float width_mm;            ///< image width on the negative, millimetres
    float height_mm;           ///< image height, millimetres
    float anamorphic_squeeze;  ///< horizontal squeeze factor; 1.0 = spherical
    float perf_pitch_mm;       ///< perforation pitch; 0 = not perforated

    /// Perforations advanced per frame. Multiplied by perf_pitch_mm this gives the
    /// distance the film web travels between successive frames, which is what the
    /// coating field needs in order to slide by exactly one frame. 0 for
    /// unperforated formats - sheet film and instant - where a single exposure means
    /// no advance at all.
    int   perfs_per_frame;

    /// Web travel between successive frames, millimetres. Emitted rather than left
    /// to the caller so there is exactly one definition of it, and so a format with
    /// no perforations reports 0 without any special case at the call site.
    float FramePitchMm (void) const noexcept
    {
        return perf_pitch_mm * static_cast<float>(perfs_per_frame);
    }
};

/// @return The complete film-stock table, by const reference.
///
/// SIGNATURE CHANGED 2026-08-18 (owner decision): was by value, which forced
/// a deep copy of every profile -- strings, spectral vectors, everything --
/// on every call. The table is immutable after construction, so callers now
/// share one instance. Existing call sites keep compiling: copy-initialising
/// a vector from this reference (AlgoMemHandler.cpp's static tables) still
/// works and still takes its own copy; binding a const reference is now free.
///
/// Ensures the database is built (thread-safe, idempotent) before returning
/// -- a lazy safety net for call sites that run before GlobalSetup. The
/// EXPLICIT initialisation point is film::LoadFilmDataBase() in
/// LoadFilmDataBase.h; render code wanting one stock should use
/// film::GetFilmProfile(filmId) -- O(1), no lock, no allocation.
/// Returns a reference to an EMPTY vector if the build failed (bad_alloc).
const std::vector<FilmProfile>& GetFilmDatabase();

/// @return All print stocks, by const reference (was by value; same
/// reasoning as GetFilmDatabase). Built on first call as a function-local
/// static; pre-warmed by LoadFilmDataBase().
const std::vector<PrintStock>& GetPrintStocks();

/// @return All film gauges, by const reference. Same pattern.
const std::vector<FilmFormat>& GetFilmFormats();

}  // namespace film
"""


def _f(x: float) -> str:
    """Format a float as an exact C++ float literal.

    ``np.format_float_positional(np.float32(x), unique=True)`` emits the
    shortest decimal that round-trips through IEEE float32 (up to 9
    significant digits), fixing audit finding PY-01 -- the old ``%.6g``
    truncated values such as 3.321928. The decimal point is not optional:
    numpy renders 36.0 as ``36.``, which is a valid literal but ugly, and a
    bare ``36`` would make ``36f`` invalid, so both cases are normalised.
    """
    s = np.format_float_positional(np.float32(x), unique=True)
    if s.endswith("."):
        s += "0"
    elif "." not in s:
        s += ".0"
    return s + "f"


def _d(x: float) -> str:
    """Format a float as an exact C++ double literal.

    Same shortest-roundtrip idea as ``_f`` but through IEEE float64 and
    without the ``f`` suffix. Used for the schema-v3 spectral tables, which
    are declared ``double`` (offline generation, storage free; measurement
    accuracy, stated per stock, remains the real precision bound).
    """
    s = np.format_float_positional(np.float64(x), unique=True)
    if s.endswith("."):
        s += "0"
    elif "." not in s:
        s += ".0"
    return s


def _dvec(vals) -> str:
    """A ``std::vector<double>`` initialiser; ``{}`` when empty."""
    if not vals:
        return "{}"
    return "{ " + ", ".join(_d(v) for v in vals) + " }"


def _interimage(ii) -> str:
    return (
        "{ "
        + f"{_d(ii.a_rg)}, {_d(ii.a_rb)}, {_d(ii.a_gr)}, "
        + f"{_d(ii.a_gb)}, {_d(ii.a_br)}, {_d(ii.a_bg)}, {ii.iterations}, "
        + f"{_d(ii.density_weighting)}"
        + " }"
    )


def _coating(cs) -> str:
    return (
        "{ "
        + f"{_d(cs.coating_sigma)}, {_d(cs.coating_corr_across_mm)}, "
        + f"{_d(cs.coating_corr_along_mm)}, {_d(cs.buckle_mtf_loss)}, "
        + f"{_d(cs.edge_fog_density)}, {_d(cs.edge_fog_mm)}"
        + " }"
    )


def _spectral(sp) -> str:
    return (
        "{ "
        + f"{_d(sp.lambda_start_nm)}, {_d(sp.lambda_step_nm)}, "
        + f"{_dvec(sp.log_s_r)}, {_dvec(sp.log_s_g)}, "
        + f"{_dvec(sp.log_s_b)}, {_dvec(sp.log_s_pan)}, "
        + f'"{_escape(sp.criterion)}", "{_escape(sp.source)}"'
        + " }"
    )


def _svec(vals) -> str:
    """A ``std::vector<std::string>`` initialiser; ``{}`` when empty."""
    if not vals:
        return "{}"
    return "{ " + ", ".join(f'"{_escape(v)}"' for v in vals) + " }"


def _dye_impurity(di) -> str:
    if not di.ratios:
        return '{ {}, "" }'
    rs = ", ".join(
        "{ "
        + f'"{_escape(r.dye)}", "{_escape(r.band)}", {_d(r.lo)}, {_d(r.hi)}, '
        + f'"{_escape(r.criterion)}"'
        + " }"
        for r in di.ratios)
    return "{ { " + rs + f' }}, "{_escape(di.source)}"' + " }"


def _dye_density(dd) -> str:
    return (
        "{ "
        + f"{_d(dd.lambda_start_nm)}, {_d(dd.lambda_step_nm)}, "
        + f"{_dvec(dd.d_cyan)}, {_dvec(dd.d_magenta)}, "
        + f"{_dvec(dd.d_yellow)}, {_dvec(dd.d_neutral)}, "
        + f'"{_escape(dd.normalisation)}", "{_escape(dd.source)}"'
        + " }"
    )


def _layer_stack(ls) -> str:
    return (
        "{ "
        + f"{_svec(ls.order)}, {_d(ls.resolving_top)}, "
        + f"{_d(ls.resolving_mid)}, {_d(ls.resolving_bot)}, "
        + f'"{_escape(ls.test_object_contrast)}", "{_escape(ls.source)}"'
        + " }"
    )


def _processing_family(pf) -> str:
    if not pf.points:
        return '{ {}, "" }'
    pts = ", ".join(
        "{ "
        + f'"{_escape(q.developer)}", "{_escape(q.dilution)}", '
        + f"{_d(q.minutes)}, {_d(q.celsius)}, "
        + f"{_d(q.contrast_index)}, {_d(q.gamma)}, {q.exposure_index}"
        + " }"
        for q in pf.points)
    return "{ { " + pts + f' }}, "{_escape(pf.source)}"' + " }"


def _reciprocity_table(rt) -> str:
    return (
        "{ "
        + f"{_dvec(rt.times_s)}, {_dvec(rt.stops_correction)}, "
        + f'{_svec(rt.cc_filters)}, "{_escape(rt.source)}"'
        + " }"
    )


def _spectral_comment(p: FilmProfile) -> str:
    """One comment line naming the spectral-curve source document, emitted
    directly above the profile literal for stocks that carry curves."""
    if not p.spectral.has_data:
        return ""
    return (
        f"        // Spectral curve source ({p.spectral.criterion}): "
        f"{p.spectral.source}\n"
    )


def _curve(c: ToneCurve) -> str:
    return (
        "{ "
        + ", ".join(
            _f(v)
            for v in (c.dmin, c.gamma, c.toe_x, c.toe_k, c.shoulder_x, c.shoulder_k)
        )
        + " }"
    )


def _curves(c) -> str:
    return f"{{ {_curve(c.r)}, {_curve(c.g)}, {_curve(c.b)} }}"


def _vec3(vals) -> str:
    """A ``std::array<float,3>`` initialiser.

    Doubled braces are required, not stylistic: ``std::array`` is a struct
    wrapping a C array, so brace elision is not available once it is nested
    inside a larger aggregate initialiser and GCC rejects the single-brace form.
    """
    return "{{ " + ", ".join(_f(v) for v in vals) + " }}"


def _matrix(m) -> str:
    """A ``std::array<std::array<float,3>,3>`` initialiser."""
    return "{{ " + ", ".join(_vec3(row) for row in m) + " }}"


def _escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _strvec(items) -> str:
    if not items:
        return "{}"
    return "{ " + ", ".join(f'"{_escape(s)}"' for s in items) + " }"


_FEATURE_CPP = {
    Feature.HALATION: "Feature::Halation",
    Feature.STRONG_DIR_COUPLERS: "Feature::StrongDirCouplers",
    Feature.UNEVEN_EMULSION: "Feature::UnevenEmulsion",
    Feature.ORTHO_RESPONSE: "Feature::OrthoResponse",
    Feature.NO_REMJET: "Feature::NoRemjet",
    Feature.THREE_STRIP: "Feature::ThreeStrip",
    Feature.TABULAR_GRAIN: "Feature::TabularGrain",
    Feature.MOSAIC_RESEAU: "Feature::MosaicReseau",
    Feature.NITRATE_BASE: "Feature::NitrateBase",
}


def _reseau(r) -> str:
    """A ReseauSpec initialiser; a zeroed one stands in for 'no grid'."""
    if r is None:
        return (
            '{ 0.0f, {{ {{ 0.0f, 0.0f, 0.0f }}, {{ 0.0f, 0.0f, 0.0f }}, '
            '{{ 0.0f, 0.0f, 0.0f }} }}, "", 0.0f }'
        )
    return (
        f"{{ {_f(r.lines_per_mm)}, {_matrix(r.filter_matrix)}, "
        f'"{_escape(r.pattern)}", {_f(r.reconstruction_pitches)} }}'
    )


def _temporal(t) -> str:
    return (
        "{ "
        + ", ".join(
            _f(v)
            for v in (
                t.weave_amp_x_um,
                t.weave_amp_y_um,
                t.weave_hz_corner,
                t.flicker_pct,
                t.flicker_hz,
                t.grain_frame_correlation,
                t.dirt_events_per_frame,
                t.scratch_persistence_frames,
                t.fps_native,
            )
        )
        + " }"
    )


def _reciprocity(r) -> str:
    return (
        "{ "
        + ", ".join(
            _f(v)
            for v in (
                r.schwarzschild_p_r,
                r.schwarzschild_p_g,
                r.schwarzschild_p_b,
                r.onset_s,
            )
        )
        + " }"
    )


def _processing(x) -> str:
    """ProcessingSpec initialiser. Strings are quoted; absent = empty/zero."""
    return (
        "{ "
        + ", ".join(
            [
                f'"{_escape(x.developer)}"',
                f'"{_escape(x.dilution)}"',
                _f(x.minutes),
                _f(x.celsius),
                f'"{_escape(x.agitation)}"',
                _f(x.contrast_index),
            ]
        )
        + " }"
    )


def _aging(a) -> str:
    return (
        "{ "
        + ", ".join(
            _f(v)
            for v in (
                a.dye_fade_c,
                a.dye_fade_m,
                a.dye_fade_y,
                a.base_yellowing_d,
                a.dmin_lift,
                a.shrinkage_pct,
                a.scratch_rate_base_per_m,
                a.scratch_rate_emulsion_per_m,
                a.dust_area_ppm,
                a.mottle_amplitude,
                a.mottle_scale_mm,
            )
        )
        + " }"
    )


def _provenance(pv) -> str:
    return (
        f"{{ {pv.tier}, {_strvec(pv.sources)}, "
        f'"{_escape(pv.fitted_from)}", "{_escape(pv.last_reviewed)}" }}'
    )


def _feature_expr(f: Feature) -> str:
    active = [cpp for flag, cpp in _FEATURE_CPP.items() if flag in f]
    return " | ".join(active) if active else "Feature::None"


def _kind_expr(k: StockKind) -> str:
    return (
        "StockKind::Reversal" if k is StockKind.REVERSAL else "StockKind::Negative"
    )


#: Human-readable meaning of the provenance confidence tiers, for the
#: generated data-source comments.
_TIER_TEXT = {
    1: "manufacturer datasheet",
    2: "secondary sources",
    3: "estimated/reconstruction",
}


def _provenance_comment(p: FilmProfile) -> str:
    """A per-profile data-source comment block for the generated .cpp.

    States which official document the numbers were taken from, who
    published it and (where the document carries a date) when -- or says
    explicitly that no official manufacturer document is on file. The
    citations live in film_profiles._PROVENANCE_SOURCES; this only formats
    what the Provenance struct already carries.
    """
    pv = p.provenance
    lines = [f"        // --- {p.name} " + "-" * 46]
    if pv.sources:
        for src in pv.sources:
            lines.append(f"        // Data source: {src}")
    else:  # unreachable with the current database, kept for safety
        lines.append("        // Data source: (none on file)")
    lines.append(
        f"        // Evidence tier: T{pv.tier} ({_TIER_TEXT[pv.tier]}); "
        f"fitted from: {pv.fitted_from}; reviewed: {pv.last_reviewed}"
    )
    return "\n".join(lines) + "\n"


def _print_stock_comment(s: PrintStock) -> str:
    """A short data-source comment for a print stock / print transform.

    Print stocks cite a manufacturer document only when their description
    already names one (none currently does); real historic stocks ([T*]
    tag) get the no-datasheet wording, and the rest are synthetic
    transforms with no manufacturer document by construction.
    """
    if "2383" in s.description and "datasheet" in s.description.lower():
        src = (
            "KODAK VISION Color Print Film 2383 Technical Data, "
            "Eastman Kodak Company"
        )
    elif s.description.startswith("[T"):
        src = (
            "no official manufacturer datasheet available -- values "
            "estimated from secondary/historical sources"
        )
    else:
        src = "synthetic transform, no manufacturer document"
    return (
        f"        // --- {s.name} " + "-" * 46 + "\n"
        f"        // Data source: {src}\n"
    )


def _profile_block(p: FilmProfile) -> str:
    g, m, hal, cp = p.grain, p.mtf, p.halation, p.couplers
    return _provenance_comment(p) + _spectral_comment(p) + f"""        {{
            "{_escape(p.name)}",
            {_strvec(p.aliases)},
            "{_escape(p.description)}",
            "{_escape(p.era)}",
            {_kind_expr(p.kind)},
            {"true" if p.is_monochrome else "false"},
            {p.exposure_index},
            {p.balance_kelvin},
            {_curves(p.curves)},
            {{ {_f(g.rms_granularity)}, {_f(g.clump_um_r)}, {_f(g.clump_um_g)}, {_f(g.clump_um_b)}, {_f(g.clump_gain)}, {_f(g.fog_grain)}, {_f(g.anisotropy)}, {_f(g.rms_r)}, {_f(g.rms_g)}, {_f(g.rms_b)}, {_f(g.sigma_shape_toe)}, {_f(g.sigma_shape_mid)}, {_f(g.sigma_shape_dmax)}, {_f(g.sigma_shape_peak)}, {_f(g.sigma_shape_peak_at)}, {_f(g.sigma_shape_toe_at)}, {_f(g.sigma_shape_dmax_at)}, {"true" if g.sigma_shape_measured else "false"}, {_f(g.size_sigma_log)}, {_f(g.cluster_um)}, {_f(g.dye_cloud_um)} }},
            {{ {_f(m.f50_r)}, {_f(m.f50_g)}, {_f(m.f50_b)}, {_f(m.adjacency)}, {_f(m.adjacency_um)}, {_f(m.resolving_power_lp_mm_lowc)}, {_f(m.resolving_power_lp_mm_highc)}, {_f(m.mtf_rolloff_q)}, {"true" if m.mtf_measured else "false"}, {_f(m.mtf_tail_a)}, {_f(m.mtf_tail_f_exp)} }},
            {{ {_vec3(hal.radii_um)}, {_vec3(hal.weights)}, {_f(hal.gain_r)}, {_f(hal.gain_g)}, {_f(hal.gain_b)}, {_f(hal.threshold_stops)}, {_f(hal.radius_scale_r)}, {_f(hal.radius_scale_g)}, {_f(hal.radius_scale_b)} }},
            {{ {_f(cp.strength)}, {_f(cp.radius_um)}, {_f(cp.edge_strength)}, {_f(cp.edge_um)} }},
            {_matrix(p.taking_matrix)},
            {_matrix(p.dye_matrix)},
            {_vec3(p.spectral_weights)},
            {_vec3(p.base_tint)},
            {_f(p.misregistration_um)},
            "{_escape(p.default_print)}",
            "{_escape(p.default_format)}",
            {"true" if p.has_reseau else "false"},
            {_reseau(p.reseau)},
            {_f(p.silver_tone)},
            {_f(p.default_flare)},
            {_f(p.default_vignette)},
            {_feature_expr(p.features)},
            {_temporal(p.temporal)},
            {_reciprocity(p.reciprocity)},
            {_aging(p.aging)},
            {p.exposure_index_tungsten},
            {_processing(p.processing)},
            {_provenance(p.provenance)},
            {_f(p.trim)},
            "{_escape(p.density_metric)}",
            "{_escape(p.referred)}",
            {_f(p.speed_point_x)},
            "{_escape(p.speed_criterion)}",
            "{_escape(p.mask_encoding)}",
            {_f(p.callier_q)},
            {_spectral(p.spectral)},
            {_coating(p.coating)},
            {_interimage(p.interimage)},
            {_dye_density(p.dye_density)},
            {_layer_stack(p.layer_stack)},
            {_processing_family(p.processing_family)},
            {_reciprocity_table(p.reciprocity_table)},
            {_dye_impurity(p.dye_impurity)}
        }},
"""


def _print_block(s: PrintStock) -> str:
    return _print_stock_comment(s) + f"""        {{
            "{_escape(s.name)}",
            "{_escape(s.description)}",
            {_curves(s.curves)},
            {_f(s.mtf_f50)}, {_f(s.grain_rms)}, {_f(s.grain_clump_um)},
            {_matrix(s.dye_matrix)},
            {_f(s.printer_light_r)}, {_f(s.printer_light_g)}, {_f(s.printer_light_b)},
            {_f(s.log_e_per_point)},
            "{_escape(s.density_metric)}",
            {_dye_density(s.dye_density)}
        }},
"""




# ===========================================================================
# Split emission (2026-08-18, owner-approved "Option C")
#
# WHY. film_profiles.cpp had grown to 676 KB of which 656 KB (97%) was ONE
# function: GetFilmDatabase() returning a std::vector<FilmProfile> built from
# a single braced-init-list of 155 elements. FilmProfile holds std::string and
# std::vector members, so that list is not constant data -- the compiler must
# emit constructor code and EH cleanup states for every element inside one
# function, PLUS a const std::initializer_list backing array of 155 full
# FilmProfile temporaries on that function's stack, PLUS a deep COPY of every
# element (initializer_list gives only const access, so the vector cannot
# move from it). MSVC 2015's hard limits (C1060 out of heap, C1026 parser
# stack, pathological optimiser time) are all PER-FUNCTION, and the Intel
# compiler's optimiser degrades the same way, so the owner's VS2015 SP3 + ICC
# environment could not reliably compile it. The primary axis to bound is
# bytes-per-function; bytes-per-TU is secondary (memory headroom, /MP).
#
# WHAT. The database is emitted as:
#   film_profiles_data_01.cpp .. _NN.cpp   consecutive, size-balanced slices
#                                          of FILM_PROFILES; each defines
#                                          detail::AppendProfiles_NN(v) doing
#                                          one v.push_back(FilmProfile{...})
#                                          per profile. push_back of an rvalue
#                                          MOVES -- no init-list backing array,
#                                          no element copies, bounded function
#                                          size.
#   film_profiles_detail.hpp               declares the NN append functions.
#   LoadFilmDataBase.h / .cpp              the explicit-initialisation API the
#                                          owner calls from the effect's
#                                          GlobalSetup (see the .h docstring).
#   film_profiles.cpp                      now small: print stocks, formats,
#                                          and the legacy GetFilmDatabase()
#                                          copy-returning wrapper kept for
#                                          AlgoMemHandler.cpp compatibility.
#
# THE SLOT COUNT IS FIXED at N_DATA_SLOTS and every slot file is ALWAYS
# emitted, empty ones as a no-op function. That is deliberate: the owner's
# VS2015 .vcxproj lists a fixed set of filenames ONCE and never changes as
# the database grows. If the database outgrows the slots, generation FAILS
# LOUDLY telling the owner to raise N_DATA_SLOTS and add the new file to the
# project -- a deliberate manual step, never a silent regression back into
# one giant translation unit.
#
# Enum order is preserved by construction: slots are consecutive slices of
# the emission order, the loader calls the slots in fixed numeric order, and
# film_names.txt / film_enum.hpp are derived by parsing the emitted slot
# files back in that same order (parse_vector_names), so vector index ==
# enum value == names-file line, exactly as before the split.
# ===========================================================================

N_DATA_SLOTS = 16          #: fixed; the .vcxproj lists these files once
SLOT_SOURCE_LIMIT = 112_000  #: bytes of emitted source per slot, hard error


def _wrap_push_back(block: str) -> str:
    """One _profile_block() entry -> a v.push_back(FilmProfile{...}) statement.

    The aggregate literal itself is untouched; only the frame changes:
        "        {"    (the entry's opening line)  -> "        v.push_back(FilmProfile{"
        "        },"   (the entry's closing line)  -> "        });"
    Statement-per-profile is the load-bearing property: a sequence of
    independent full-expressions compiles in bounded memory where one
    676 KB braced-init-list expression does not, and each temporary is an
    rvalue so the vector MOVES it (strings and spectral vectors transfer
    their heap blocks instead of duplicating them).
    """
    open_key = "\n        {\n"
    if not block.startswith("        {"):
        i = block.index(open_key)
        block = (block[:i] + "\n        v.push_back(FilmProfile{\n"
                 + block[i + len(open_key):])
    else:
        block = "        v.push_back(FilmProfile{\n" + block[len("        {\n"):]
    if not block.endswith("        },\n"):
        raise ValueError("profile block does not end with '},' -- emitter "
                         "layout changed, update _wrap_push_back")
    return block[:-len("        },\n")] + "        });\n"


def _distribute(blocks: list) -> list:
    """Assign consecutive blocks to N_DATA_SLOTS size-balanced slots.

    Cumulative-size partitioning: block i goes to slot
    floor(bytes_before_i / total * N). Order is preserved (consecutive
    slices), balance is near-optimal, and the mapping is deterministic --
    the same database always produces the same files.
    """
    sizes = [len(b.encode("utf-8")) for b in blocks]
    total = sum(sizes) or 1
    slots = [[] for _ in range(N_DATA_SLOTS)]
    cum = 0
    for b, sz in zip(blocks, sizes):
        idx = min(cum * N_DATA_SLOTS // total, N_DATA_SLOTS - 1)
        slots[idx].append(b)
        cum += sz
    return slots


def _data_slot_source(nn: int, blocks: list, stamp: str) -> str:
    head = (
        f"// Generated by cpp_codegen.py -- do not edit by hand.\n"
        f"// generated: {stamp}\n"
        f"// schema_version {SCHEMA_VERSION}\n"
        f"// Data slot {nn:02d} of {N_DATA_SLOTS:02d} -- a consecutive slice of the film-profile\n"
        f"// table. Called exactly once, in slot order, by LoadFilmDataBase();\n"
        f"// see film_profiles_detail.hpp for why the table is split.\n"
        f'#include "film_profiles_detail.hpp"\n\n'
        f"namespace film {{\nnamespace detail {{\n\n"
        f"void AppendProfiles_{nn:02d}(std::vector<FilmProfile>& v)\n{{\n"
    )
    if not blocks:
        body = ("    // Empty slot, reserved capacity. The file exists so the\n"
                "    // VS project file never has to change as the database grows.\n"
                "    (void)v;\n")
    else:
        body = "".join(blocks)
    return head + body + "}\n\n}  // namespace detail\n}  // namespace film\n"


def _detail_hpp_source(stamp: str) -> str:
    decls = "\n".join(
        f"void AppendProfiles_{i:02d}(std::vector<FilmProfile>& v);"
        for i in range(1, N_DATA_SLOTS + 1))
    return f"""\
// Generated by cpp_codegen.py -- do not edit by hand.
// generated: {stamp}
// schema_version {SCHEMA_VERSION}
//
// INTERNAL header for the split film-profile table. The table is emitted as
// {N_DATA_SLOTS} translation units (film_profiles_data_01.cpp ..) because a single
// 676 KB braced-init-list function was beyond what VS2015 SP3 / ICC compile
// reliably -- their limits are per-function. Each slot appends a consecutive
// slice of the table; LoadFilmDataBase() calls them in numeric order, so
// vector index == eFILM_PROFILE value == film_names.txt line, unchanged.
//
// Nothing outside LoadFilmDataBase.cpp should include this header.
#pragma once
#include "film_profiles.hpp"

namespace film {{
namespace detail {{

{decls}

}}  // namespace detail
}}  // namespace film
"""


def _loader_h_source(stamp: str) -> str:
    return f"""\
// Generated by cpp_codegen.py -- do not edit by hand.
// generated: {stamp}
// schema_version {SCHEMA_VERSION}
//
// Explicit film-database initialisation for the AE/PR plugin (owner request,
// 2026-08-18). Design constraints this file satisfies, in the owner's order:
//
//   * NOTHING happens at DLL load. No namespace-scope object in the generated
//     code has a dynamic initialiser that does work: the storage vector is a
//     function-local static (touched first inside the loader), the once-flag
//     and the loaded-flag are constant-initialised. Host startup cost: zero.
//   * The plugin calls LoadFilmDataBase() from the effect's GlobalSetup. It
//     builds the COMPLETE table exactly once and reports success/failure.
//   * Initialise-exactly-once and concurrent-GlobalSetup safety come from
//     std::call_once (supported by VS2015's runtime; the Intel compiler uses
//     the same MSVC standard library). A FAILED load (bad_alloc) does NOT
//     latch: the once-flag is only consumed by a successful run, so a later
//     call retries instead of wedging the plugin permanently unloaded.
//   * Rendering accesses ONE profile at a time, so the access API is
//     GetFilmProfile(id): O(1) index into the built table, no allocation,
//     no lock, noexcept, nullptr on not-loaded or bad id. The engine already
//     passes const film::FilmProfile& into its stages, so this is the shape
//     it actually consumes.
//   * Storage: one std::vector sized with reserve(eTOTAL_FILMS_PROFILES) --
//     a single allocation for the element array, no growth reallocation.
//     Fully static allocation is IMPOSSIBLE with the current schema, stated
//     rather than fudged: FilmProfile owns std::string / std::vector members,
//     which heap-allocate by nature. Eliminating those allocations would
//     need a parallel POD schema (const char* + pointer/count spans) -- a
//     much larger change, kept as a recorded option if ever justified.
//   * Deliberately NO UnloadFilmDataBase(): GetFilmProfile() hands out raw
//     pointers into the storage, so an unload API would be a dangling-pointer
//     factory. Lifetime is process lifetime, same as the engine's existing
//     static tables in AlgoMemHandler.cpp.
//
// Threading note for the curious: g_loaded uses release/acquire so that even
// a reader that skips call_once's own synchronisation (GetFilmProfile on a
// render thread) observes a fully-built table or nullptr, never a torn one.
#pragma once
#include "film_profiles.hpp"
#include "film_enum.hpp"

namespace film {{

/// Build the complete film-profile table. Idempotent, thread-safe, callable
/// from GlobalSetup. Returns true when the table is (already) fully built;
/// false on failure (out of memory), in which case a later call retries.
bool LoadFilmDataBase(void);

/// True once LoadFilmDataBase() has completed successfully.
bool IsFilmDataBaseLoaded(void) noexcept;

/// O(1) access to one profile. No allocation, no lock, noexcept.
/// Returns nullptr when the database is not loaded or filmId is out of
/// range -- the caller decides the failure policy (skip effect, error UI).
const FilmProfile* GetFilmProfile(eFILM_PROFILE filmId) noexcept;

// The whole-table accessor is film::GetFilmDatabase() -- declared in
// film_profiles.hpp, now returning const std::vector<FilmProfile>& and
// defined next to the storage in LoadFilmDataBase.cpp. Prefer
// GetFilmProfile() in render code.

}}  // namespace film
"""


def _loader_cpp_source(stamp: str) -> str:
    calls = "\n".join(
        f"        detail::AppendProfiles_{i:02d}(v);"
        for i in range(1, N_DATA_SLOTS + 1))
    return f"""\
// Generated by cpp_codegen.py -- do not edit by hand.
// generated: {stamp}
// schema_version {SCHEMA_VERSION}
// See LoadFilmDataBase.h for the design constraints this implements.
#include "LoadFilmDataBase.h"
#include "film_profiles_detail.hpp"

#include <atomic>
#include <cstdint>
#include <mutex>
#include <new>

namespace film {{
namespace {{

std::vector<FilmProfile>& storage()
{{
    // Function-local magic static: constructed (empty, trivial) on first
    // touch inside the loader -- NOT at DLL load. C++11 semantics make the
    // construction race-free; VS2015 implements this ("magic statics") and
    // AlgoMemHandler.cpp already relies on the same guarantee.
    // Requires /Zc:threadSafeInit (the default) -- do not disable it.
    static std::vector<FilmProfile> s;
    return s;
}}

std::once_flag g_once;                     // constant-initialised
std::atomic<bool> g_loaded{{false}};        // constant-initialised

}}  // namespace

bool LoadFilmDataBase(void)
{{
    if (g_loaded.load(std::memory_order_acquire))
        return true;                        // fast path for repeat calls
    try
    {{
        std::call_once(g_once, []
        {{
            const std::size_t kCount = static_cast<std::size_t>(
                eFILM_PROFILE::eTOTAL_FILMS_PROFILES);
            std::vector<FilmProfile> v;
            v.reserve(kCount);
{calls}
            if (v.size() != kCount)
                throw std::bad_alloc();     // slot/count mismatch: fail, retry
            storage().swap(v);
            // Pre-warm the two small magic-static tables too, so GlobalSetup
            // pays ALL one-time construction and the render path never does.
            (void)GetPrintStocks();
            (void)GetFilmFormats();
            g_loaded.store(true, std::memory_order_release);
        }});
    }}
    catch (...)
    {{
        // bad_alloc (or the count guard). call_once does NOT consume the
        // flag on an exceptional run, so the next call retries the build
        // instead of leaving the plugin permanently without its database.
        return false;
    }}
    return g_loaded.load(std::memory_order_acquire);
}}

bool IsFilmDataBaseLoaded(void) noexcept
{{
    return g_loaded.load(std::memory_order_acquire);
}}

const FilmProfile* GetFilmProfile(eFILM_PROFILE filmId) noexcept
{{
    if (!g_loaded.load(std::memory_order_acquire))
        return nullptr;
    const std::int32_t idx = static_cast<std::int32_t>(filmId);
    if (idx < 0 || idx >= static_cast<std::int32_t>(
            eFILM_PROFILE::eTOTAL_FILMS_PROFILES))
        return nullptr;
    return &storage()[static_cast<std::size_t>(idx)];
}}

const std::vector<FilmProfile>& GetFilmDatabase()
{{
    LoadFilmDataBase();                    // idempotent lazy safety net
    return storage();                      // empty vector if load failed
}}

}}  // namespace film
"""


def _timestamp() -> str:
    """UTC generation timestamp for the generated C++ headers.

    Date and time are separated by TWO SPACES rather than the ISO-8601 "T",
    on the owner's request, because the run-together form is hard to read in a
    comment banner. Still UTC, still Zulu-suffixed, so it remains unambiguous.
    Tabs are deliberately not used.

    Emitted into film_profiles.hpp, film_profiles.cpp and film_enum.hpp ONLY --
    never into film_names.txt, which must stay pure data (owner requirement).
    """
    from datetime import datetime, timezone

    return datetime.now(timezone.utc).strftime("%Y-%m-%d  %H:%M:%SZ")


def _cpp_source(stamp: str) -> str:
    out = [
        "// Generated by cpp_codegen.py -- do not edit by hand.\n",
        f"// generated: {stamp}\n",
        f"// schema_version {SCHEMA_VERSION}\n",
        '#include "film_profiles.hpp"\n\nnamespace film {\n\n',
        "// GetFilmDatabase() is defined in LoadFilmDataBase.cpp -- it returns a\n"
        "// const reference into the storage that LoadFilmDataBase() builds. The\n"
        "// 155-profile data lives in the film_profiles_data_NN.cpp slots; see\n"
        "// film_profiles_detail.hpp for why the table is split.\n"
        "// This file carries only the two small tables below.\n\n",
    ]

    out.append(
        "// Function-local magic static: built on FIRST CALL, not at DLL load\n"
        "// (owner requirement: no substantial work in static initialisers).\n"
        "// LoadFilmDataBase() pre-warms it from GlobalSetup so the render path\n"
        "// never pays the construction.\n"
        "const std::vector<PrintStock>& GetPrintStocks() {\n"
        "    static const std::vector<PrintStock> table = {\n")
    out.extend(_print_block(s) for s in PRINT_STOCKS)
    out.append("    };\n    return table;\n}\n\n")

    out.append(
        "const std::vector<FilmFormat>& GetFilmFormats() {\n"
        "    static const std::vector<FilmFormat> table = {\n")
    out.extend(
        f'        {{ "{name}", {_f(w)}, {_f(h)}, {_f(sq)}, {_f(pp)}, '
        f'{PERFS_PER_FRAME.get(name, 0)} }},\n'
        for name, (w, h, sq, pp) in sorted(FORMAT_GEOM.items())
    )
    out.append("    };\n    return table;\n}\n\n")

    out.append("}  // namespace film\n")
    return "".join(out)



_ENTRY_RX = re.compile(r'^        // --- ([A-Z0-9_]+) -', re.M)
_NAME_RX = re.compile(r'^            "([A-Z0-9_]+)",$', re.M)


def write_film_names(cpp_path: Path, txt_path: Path,
                     separator: bool = True) -> int:
    """Emit the film-name list consumed by the C++ effect-panel listbox.

    Order is taken by parsing the ALREADY-WRITTEN film_profiles.cpp rather than
    by re-walking FILM_PROFILES. That is deliberate: the listbox indexes into
    GetFilmDatabase()'s std::vector, so line N here must be element N-1 there.
    Re-deriving from FILM_PROFILES would only be *assumed* equal; reading the
    emitted table back makes it equal by construction, so a future reordering
    inside the emitter cannot silently desynchronise panel and database.

    Must therefore be called after the .cpp is on disk.

    Parsing is deliberately belt-and-braces: entry boundaries come from the
    per-entry header comment, the name from the first quoted upper-case token
    inside each entry, and the two lists must agree. A bare scan of quoted
    upper-case tokens would NOT work -- other fields (StockKind, SCAN_DI, ...)
    are emitted in the same shape at the same indent.

    Format: display name (underscores turned into spaces) in double quotes,
    one per line, LF endings, plain ASCII, no comments.

    Separator (2026-08-13, owner request): by DEFAULT every line except the
    LAST carries a trailing "|" INSIDE the closing quote -- "NAME|". The file
    is consumed as adjacent C++ string literals, and concatenation then
    yields the single "A|B|...|Z" string an After Effects popup expects,
    with no separator after the final item. ``separator=False`` (the
    --no_separator command-line flag) restores the previous pipe-free
    format. Line order is the GetFilmDatabase() vector order in BOTH modes;
    only the trailing character differs.
    """
    names = parse_vector_names(cpp_path)
    out = []
    for i, n in enumerate(names):
        disp = n.replace("_", " ")
        try:
            disp.encode("ascii")
        except UnicodeEncodeError:
            raise ValueError(f"{n}: name is not ASCII, cannot go in the "
                             f"plain-ASCII listbox file")
        # "|" after the name, inside the quotes, on every line but the last.
        sep = "|" if (separator and i < len(names) - 1) else ""
        out.append('"%s%s"' % (disp, sep))
    txt_path.write_text("\n".join(out) + "\n", encoding="ascii", newline="\n")
    return len(out)


def parse_vector_names(cpp_path: Path) -> list:
    """Return the profile names in GetFilmDatabase() std::vector order.

    Single source of truth for every index-bearing artefact (listbox TXT and
    film_enum.hpp), read back out of the emitted .cpp so their indices cannot
    drift from the database.
    """
    # The table now lives in the fixed data-slot files; read them back in
    # slot order. Concatenating in that order IS the vector order, because
    # the loader calls AppendProfiles_01..NN in the same fixed sequence.
    d = Path(cpp_path).parent
    parts = []
    for i in range(1, N_DATA_SLOTS + 1):
        p = d / f"film_profiles_data_{i:02d}.cpp"
        if not p.is_file():
            raise FileNotFoundError(f"data slot missing: {p.name} -- "
                                    f"generate() must write all slots first")
        parts.append(p.read_text(encoding="utf-8"))
    table = "".join(parts)

    bounds = [(m.start(), m.group(1)) for m in _ENTRY_RX.finditer(table)]
    offsets = [b[0] for b in bounds] + [len(table)]

    names = []
    for i, (_, declared) in enumerate(bounds):
        chunk = table[offsets[i]:offsets[i + 1]]
        found = _NAME_RX.search(chunk)
        if found is None:
            raise ValueError(f"{declared}: no name field found in its entry")
        if found.group(1) != declared:
            raise ValueError(
                f"entry header says {declared} but its first name field says "
                f"{found.group(1)} -- emitter layout changed")
        names.append(declared)

    expected = len(FILM_PROFILES)
    if len(names) != expected:
        raise ValueError(
            f"parsed {len(names)} entries from the emitted vector but "
            f"FILM_PROFILES holds {expected}")
    return names


ENUM_TEMPLATE = """// Generated by cpp_codegen.py on @GENERATED@ -- DO NOT EDIT BY HAND.
// film_profiles schema version @SCHEMA_VERSION@; @COUNT@ profiles.
//
// Film profile indices. Values are positions in the std::vector returned by
// film::GetFilmDatabase(), so a value here may be used directly as that
// vector's subscript, and it matches line (value + 1) of film_names.txt.
//
// Underlying type is fixed at int32_t so the values are stable across
// compilers and safe to serialise into project files and plugin parameters.
// Appending a stock renumbers nothing; INSERTING one renumbers everything
// after it, which would invalidate saved projects -- add at the end.
#pragma once

#include <cstdint>

namespace film {

enum class eFILM_PROFILE : int32_t
{
@ENTRIES@
    eTOTAL_FILMS_PROFILES = @COUNT@
};

}  // namespace film
"""


def write_film_enum(cpp_path: Path, hpp_path: Path, stamp: str) -> int:
    """Emit film_enum.hpp: one enumerator per profile, database order, from 0.

    Order comes from parse_vector_names() -- the emitted vector itself -- for
    the same reason the names file does: the enum is an index into that vector.
    """
    names = parse_vector_names(cpp_path)
    width = max(len(n) for n in names) + 1
    lines = []
    for i, n in enumerate(names):
        ident = "e" + n
        lines.append("    %-*s = %d," % (width, ident, i))
    hpp_path.write_text(
        ENUM_TEMPLATE.replace("@GENERATED@", stamp)
                     .replace("@SCHEMA_VERSION@", str(SCHEMA_VERSION))
                     .replace("@ENTRIES@", "\n".join(lines))
                     .replace("@COUNT@", str(len(names))),
        encoding="utf-8", newline="\n")
    return len(names)


def generate(outdir: Path | str = ".",
             names_separator: bool = True) -> tuple[Path, Path, Path, Path]:
    """Write film_profiles.hpp and film_profiles.cpp into ``outdir``.

    Returns:
        Paths of every emitted file: header, legacy source, listbox name
        list, enum header, the detail header, the LoadFilmDataBase pair,
        and the N_DATA_SLOTS data-slot sources.
    """
    d = Path(outdir)
    d.mkdir(parents=True, exist_ok=True)
    hpp = d / "film_profiles.hpp"
    cpp = d / "film_profiles.cpp"
    stamp = _timestamp()
    hpp_text = HPP_TEMPLATE.replace("@GENERATED@", stamp).replace(
        "@SCHEMA_VERSION@", str(SCHEMA_VERSION))
    hpp.write_text(hpp_text, encoding="utf-8", newline="\n")

    # -- the data slots: consecutive, size-balanced slices ------------------
    blocks = [_wrap_push_back(_profile_block(p)) for p in FILM_PROFILES]
    slots = _distribute(blocks)
    slot_paths = []
    for i, slot_blocks in enumerate(slots, 1):
        src = _data_slot_source(i, slot_blocks, stamp)
        n = len(src.encode("utf-8"))
        if n > SLOT_SOURCE_LIMIT:
            raise RuntimeError(
                f"data slot {i:02d} is {n} bytes (> {SLOT_SOURCE_LIMIT}). The "
                f"database has outgrown {N_DATA_SLOTS} slots. Raise "
                f"N_DATA_SLOTS in cpp_codegen.py AND add the new "
                f"film_profiles_data_NN.cpp file(s) to the VS project -- a "
                f"deliberate manual step, never a silent regression.")
        p = d / f"film_profiles_data_{i:02d}.cpp"
        p.write_text(src, encoding="utf-8", newline="\n")
        slot_paths.append(p)

    detail = d / "film_profiles_detail.hpp"
    detail.write_text(_detail_hpp_source(stamp), encoding="utf-8", newline="\n")
    loader_h = d / "LoadFilmDataBase.h"
    loader_h.write_text(_loader_h_source(stamp), encoding="utf-8", newline="\n")
    loader_cpp = d / "LoadFilmDataBase.cpp"
    loader_cpp.write_text(_loader_cpp_source(stamp), encoding="utf-8",
                          newline="\n")
    cpp.write_text(_cpp_source(stamp), encoding="utf-8", newline="\n")

    # names file last: it reads the emitted slots back to lock
    # listbox index == vector index == enum value
    names = d / "film_names.txt"
    write_film_names(cpp, names, separator=names_separator)
    enum = d / "film_enum.hpp"
    write_film_enum(cpp, enum, stamp)
    return (hpp, cpp, names, enum, detail, loader_h, loader_cpp,
            *slot_paths)


if __name__ == "__main__":
    import argparse

    ap = argparse.ArgumentParser(description="Emit C++ film profile tables.")
    ap.add_argument("-o", "--outdir", type=Path, default=Path("."))
    ap.add_argument("--no_separator", action="store_true",
                    help="emit film_names.txt WITHOUT the trailing '|' "
                         "separators (the pre-2026-08-13 format)")
    ns = ap.parse_args()
    for path in generate(ns.outdir, names_separator=not ns.no_separator):
        print(f"[INFO] wrote {path}")
