"""
Generates doc/FilmCurves.md: per-stock spectral-curve status table.

Columns (owner request 2026-08-02): official film name, official datasheet
document (from Provenance.sources), whether the digitised spectral curve is
used, number of curve points, curve resolution. Regenerate after every
digitisation pass:  python gen_film_curves_md.py
"""

from pathlib import Path

from film_profiles import FILM_PROFILES, _NO_DATASHEET
from gen_film_names import official_name

#: Stocks whose archive datasheet carries a spectral-sensitivity plot that
#: is NOT yet digitised (see doc/DIGITIZATION_QUEUE.md). Maintained by hand
#: on each pass.
QUEUED_PLOT_ON_FILE = {
    # Remaining after the 2026-08-02 batch passes. AGFA_VISTA_200 and the
    # two KENTMERE stocks were checked: NO spectral plot exists in their
    # sheets on file (moved to the no-plot category).
    # (empty 2026-08-02 evening: H-1-5219 supplied by owner and digitised;
    # KODAK/5239.pdf turned out to be a mislabeled processing manual --
    # a real 5239 sheet would go here.)
}


def _doc_name(p) -> str:
    src = p.provenance.sources
    if not src or src == _NO_DATASHEET or "No official" in src[0]:
        return "—"
    # First citation, up to the first " -- " remark separator.
    s = src[0].split(" -- ")[0]
    return s if len(s) <= 90 else s[:87] + "..."


def _rows():
    for p in FILM_PROFILES:
        sp = p.spectral
        if sp.has_data:
            n_layers = 1 if sp.log_s_pan else 3
            n = len(sp.log_s_pan or sp.log_s_r)
            end = sp.lambda_start_nm + sp.lambda_step_nm * (n - 1)
            used = "**yes** (digitised)"
            pts = f"{n} × {n_layers} layer{'s' if n_layers > 1 else ''} = {n * n_layers}"
            res = (f"{sp.lambda_step_nm:.0f} nm step, "
                   f"{sp.lambda_start_nm:.0f}–{end:.0f} nm")
        elif p.name in QUEUED_PLOT_ON_FILE:
            used, pts, res = "not yet — plot on file (queued)", "—", "—"
        else:
            used, pts, res = "no plot in archive (text/table data)", "—", "—"
        yield (official_name(p.name), _doc_name(p), used, pts, res)


def generate(outdir: Path | str = "doc") -> Path:
    out = Path(outdir) / "FilmCurves.md"
    n_yes = sum(1 for p in FILM_PROFILES if p.spectral.has_data)
    lines = [
        "# FilmCurves.md — spectral sensitivity curve usage per stock",
        "",
        f"Generated by `gen_film_curves_md.py` from `film_profiles.py` "
        f"(schema v3). {n_yes} of {len(FILM_PROFILES)} stocks carry "
        "digitised per-emulsion spectral curves; every curve is that "
        "film's own — never shared across a vendor. "
        "As of 2026-08-13 these curves ARE consumed: they drive colour-temperature "
        "balance in both the Python reference and the C++ engine (AlgoSpectralSensitivity, spectral_balance_gains). The monochrome-weight and taking-matrix derivations built on the same curves remain OFF by default -- projecting a sensitisation onto three visible primaries derives nonsense for extended-red and infrared stocks; see CHANGES_2026-08-13_spectral_path.md.",
        "",
        "Values are relative log10 sensitivity, peak-normalised to 0.0, "
        "sentinel −4.0 = below the source plot's floor. Colour stocks "
        "carry three sensitive-layer curves, B&W/reseau stocks one "
        "panchromatic curve. Full citations (author, document, ORIGINAL "
        "release date) live in each profile's `spectral.source` field and "
        "in the generated C++ comments. Queue and method rules: "
        "`DIGITIZATION_QUEUE.md`.",
        "",
        "| Film (official name) | Official datasheet | Spectral curve used | Curve points | Curve resolution |",
        "|---|---|---|---|---|",
    ]
    for r in _rows():
        lines.append("| " + " | ".join(r) + " |")
    lines += [
        "",
        "## Notes",
        "",
        "- H&D characteristic curves are a separate track: machine-traced "
        "and refitted for the full KODAK VISION3 family (5203/5207/5213/5219, "
        "856-1467 samples/layer), EASTMAN DOUBLE-X 5222 and "
        "FUJI NEOPAN ACROS 100 (1092 samples), stored as the fitted "
        "6-parameter model with residuals quoted in the profile comments.",
        "- 'no plot in archive' stocks follow the owner rule: printed "
        "text/table values are used instead (e.g. the Soviet stocks use "
        "Gurlev/Chibisov sensitization limits: FOTO-32 645 nm, FN-64 "
        "665 nm, FOTO-130 580 nm, FOTO-250 630 nm, OCh-45 660–680 nm).",
    ]
    out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    return out


if __name__ == "__main__":
    path = generate()
    print(f"wrote {path}")
