#!/usr/bin/env python3
"""Python vs C++ parity for the MEASURED characteristic curve (schema v55).

WHAT IS BEING COMPARED
----------------------
`film_sim.density` / `film_sim.density_scalar` against `AlgoMeasuredDensity`
(AlgoCharacteristicCurve.hpp) and against the tabulated path
`AlgoBuildCurveLut` / `AlgoCurveLutEval` (AlgoCurveLut.hpp), on every curve in
the database that carries instrument samples, over a sweep that deliberately
straddles both ends of the sampled range.

⚠⚠ WHY THIS AUDIT EXISTS AT ALL. Until schema v55 every engine evaluated the
SAME CLOSED FORM, so a disagreement could only be floating-point. A measured
curve is different in kind: it is a piecewise cubic over a table, and a
piecewise anything has three separate ways to diverge that a softplus does
not have --

  1. THE INTERVAL SEARCH. Python bisects with `bisect`-style integer halving
     over a Python tuple; C++ bisects over a float array. At a sample point
     exactly, "which interval is this?" has two defensible answers, and the
     two sides must pick the same one or the density steps by the slope
     difference across that knot.
  2. THE DERIVATIVE. Fritsch-Carlson is one formula but three plausible
     spellings, and two of them differ in the last bits at a flat run. This
     project ships the slopes rather than recomputing them, so what is tested
     here is that the SHIPPED numbers reached C++ intact -- the generated
     tables are compared element by element against the Python source.
  3. THE OUTSIDE. Beyond the samples both sides fall back to the softplus,
     OFFSET to meet the table. The offset is a difference of two nearly equal
     quantities and is the one number in this feature that is computed twice.

⚠ AND A FOURTH, PECULIAR TO THE VECTOR BUILD. AVX2 does not evaluate the
cubic per lane: `AlgoBuildCurveLut` bakes the measured curve into the 4097
entry table and the lanes do a clamped linear interpolation of THAT. So the
vector path is allowed a table error the scalar path does not have, and this
file measures it rather than assuming it is small. The domain widening that
makes it possible -- the LUT's range must now cover the samples, not just the
knees -- is checked here too, by probing 0.3 decade BELOW the lowest sample
on a curve whose samples run far below its toe. Without the widening that
probe would return a clamped constant and this audit would fail loudly, which
is the entire point of including it.

WHAT THE NUMBERS SHOULD LOOK LIKE
---------------------------------
Scalar: float64 both sides, so agreement at 1e-12. AVX2: float32 arithmetic
plus the LUT's own interpolation error, which AlgoCurveLut.hpp measures at
4.24e-06 D for a softplus; a monotone cubic sampled every ~0.0012 decade does
not worsen it materially, so 2e-3 is the same tolerance the other AVX2 audits
use and there is three orders of headroom under it.
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import film_profiles as FP            # noqa: E402
import film_sim as FS                 # noqa: E402

#: ⚠ 1e-6 AND NOT 1e-12, AND THE REASON IS STORAGE RATHER THAN ARITHMETIC.
#: The scalar build's AlgoType is double, so the interpolation itself runs in
#: float64 on both sides -- but `film::ToneCurve` holds the samples as `float`,
#: exactly as it holds dmin and gamma, so every abscissa, density and slope is
#: rounded to float32 on the way into C++ while Python keeps the decimal the
#: report printed. 2.18 becomes 2.1800000667572021, and the resulting
#: disagreement is 7.6e-08 at the worst probe -- entirely that rounding, and
#: measured rather than assumed: a first run of this audit at 1e-12 failed at
#: exactly the last sample, which is where the float32 step is largest. 1e-6
#: sits an order above it and four orders below anything a curve error could
#: plausibly be.
TOL_SCALAR = 1.0e-6

#: float32 plus the shared curve table's linear interpolation.
TOL_AVX2 = 2.0e-3

#: How far past each end of the sampled range to probe, in decades. 0.30 is
#: chosen so the low probe on FERRANIA_P30 lands at -3.33, which is 1.4
#: decades below its toe_x and therefore well outside the LUT domain the
#: builder would have chosen from the knees alone.
OUTSIDE_DECADES = 0.30

#: Probes per curve, inside the sampled range. 401 over 3 decades puts a
#: sample every 0.0075 decade, so every one of the 20 intervals is crossed
#: about 20 times and the knots themselves are hit exactly.
N_INSIDE = 401


PROBE = r"""
// Generated by measured_curve_parity.py -- not part of the shipped plugin.
#include "film_profiles.hpp"
#include "LoadFilmDataBase.h"
#include "AlgoCharacteristicCurve.hpp"
#include "AlgoCurveLut.hpp"
#include "AlgoTypes.hpp"
#include <cstdio>
#include <cstddef>
#include <cmath>
#include <string>

static const char*  kNames[] = { %(NAMES)s };
static const int    kChan [] = { %(CHANS)s };
static const double kArgs [] = { %(ARGS)s };

static const film::ToneCurve& chanOf(const film::RGBCurves& c, int k)
{
    return (0 == k) ? c.r : ((1 == k) ? c.g : c.b);
}

// ⚠ AlgoSoftplus IS DEFINED HERE RATHER THAN LINKED, and the definition is
// Algo_05_Sim.cpp's character for character. Linking that TU instead would
// drag in the whole blur and copy layer for one twelve-line function, and the
// probe would then be testing the link graph rather than the interpolant.
// If the engine's softplus is ever changed, this copy must change with it --
// which the closed-form half of the comparison below would catch, because
// both sides would then evaluate different fits outside the samples.
AlgoType AlgoSoftplus (const AlgoType x, const AlgoType k) noexcept
{
    const AlgoType z = x / k;
    if (z > ALGO_SOFTPLUS_LINEAR_LIMIT)
        return x;
    return k * static_cast<AlgoType>(std::log1p(std::exp(
               static_cast<HighPrecType>(z))));
}

static AlgoType fitOf(const film::ToneCurve& c, AlgoType a)
{
    // The closed form spelled exactly as stage 08 spells it, so that what is
    // compared is the MEASURED branch and not a second softplus.
    const AlgoType rise = AlgoSoftplus(a - static_cast<AlgoType>(c.toe_x),
                                       static_cast<AlgoType>(c.toe_k));
    const AlgoType fall = AlgoSoftplus(a - static_cast<AlgoType>(c.shoulder_x),
                                       static_cast<AlgoType>(c.shoulder_k));
    return static_cast<AlgoType>(c.dmin)
         + static_cast<AlgoType>(c.gamma) * (rise - fall);
}

int main()
{
    std::printf("SIZEOF %%d\n", (int)sizeof(AlgoType));
    if (false == film::LoadFilmDataBase()) { std::printf("NOLOAD\n"); return 1; }
    const std::vector<film::FilmProfile>& db = film::GetFilmDatabase();

    for (std::size_t n = 0; n < %(NCURVE)u; ++n)
    {
        const film::FilmProfile* base = nullptr;
        for (std::size_t i = 0; i < db.size(); ++i)
            if (db[i].name == kNames[n]) { base = &db[i]; break; }
        if (nullptr == base) { std::printf("MISSING %%s\n", kNames[n]); continue; }

        const film::ToneCurve& c = chanOf(base->curves, kChan[n]);
        if (false == c.hasMeasured()) { std::printf("NOTABLE %%s\n", kNames[n]); continue; }

        // The shipped table itself, so a transcription error in codegen is
        // caught as data rather than showing up as a curve disagreement.
        for (int i = 0; i < c.meas_n; ++i)
            std::printf("TAB %%u %%d %%.17g %%.17g %%.17g\n",
                        (unsigned)n, i, (double)c.meas_x[i],
                        (double)c.meas_d[i], (double)c.meas_m[i]);

        const AlgoMeasuredCtx mc = AlgoMakeMeasured(c);
        std::printf("OFF %%u %%.17g %%.17g\n",
                    (unsigned)n, (double)mc.offLo, (double)mc.offHi);

        AlgoCurveLut lut;
        AlgoBuildCurveLut(c, lut);
        std::printf("DOM %%u %%.17g %%.17g\n",
                    (unsigned)n, (double)lut.lo,
                    (double)(lut.lo + lut.maxIdx / lut.invStep));

        for (std::size_t k = 0; k < %(NARG)u; ++k)
        {
            const AlgoType a = static_cast<AlgoType>(kArgs[k]);
            const AlgoType d = AlgoMeasuredDensity(mc, a, fitOf(c, a));
            const AlgoType t = AlgoCurveLutEval(a, lut);
            std::printf("ROW %%u %%.17g %%.17g %%.17g\n",
                        (unsigned)n, (double)kArgs[k], (double)d, (double)t);
        }
    }
    return 0;
}
"""


def measured_curves() -> list[tuple[str, int, object]]:
    """Every (profile, channel, ToneCurve) in the database carrying samples.

    ⚠ PROFILE CURVES ONLY, not the per-variant ones. A ProcessVariant's curves
    are not reachable through `FilmProfile::curves` in C++ without resolving
    the variant first, and the variant resolver is audited by its own file;
    what this audit is for is the INTERPOLANT, and the profile curve exercises
    every line of it. The variant tables are still checked as DATA, because
    codegen interns them into the same emitted arrays.
    """
    out = []
    for p in FP.FILM_PROFILES:
        for k, c in enumerate(p.curves.as_tuple()):
            if c.measured.has_data:
                out.append((p.name, k, c))
    return out


def probe_args(curves) -> list[float]:
    """One shared sweep, spanning every curve's samples and beyond both ends."""
    lo = min(c.measured.log_h[0] for _n, _k, c in curves) - OUTSIDE_DECADES
    hi = max(c.measured.log_h[-1] for _n, _k, c in curves) + OUTSIDE_DECADES
    step = (hi - lo) / (N_INSIDE - 1)
    args = [lo + step * i for i in range(N_INSIDE)]
    # The knots themselves, exactly: the interval search is only interesting
    # where it is ambiguous.
    for _n, _k, c in curves:
        args.extend(c.measured.log_h)
    return sorted(set(args))


def build_probe(root: Path, tmp: Path, avx2: bool, curves, args):
    cxx = os.environ.get("CXX") or shutil.which("g++") or shutil.which("clang++")
    if not cxx:
        raise SystemExit("[!] no g++/clang++ on PATH (set CXX to override)")

    src = tmp / ("probe_avx2.cpp" if avx2 else "probe_scalar.cpp")
    src.write_text(PROBE % dict(
        NAMES=", ".join('"%s"' % n for n, _k, _c in curves),
        CHANS=", ".join(str(k) for _n, k, _c in curves),
        NCURVE=len(curves),
        ARGS=", ".join("%.17g" % v for v in args),
        NARG=len(args),
    ), encoding="utf-8")

    inc = [str(root), str(HERE)]
    flags = ["-std=c++14", "-O1"]
    tus = [str(src), str(HERE / "film_profiles.cpp"),
           str(HERE / "LoadFilmDataBase.cpp")]
    if avx2:
        stage = tmp / "avx2inc"
        if not stage.exists():
            stage.mkdir()
            for f in list(root.glob("*.hpp")):
                (stage / f.name).symlink_to(f.resolve())
            hdr = root / "AVX2" / "AlgoTypes.hpp"
            if not hdr.is_file():
                return None
            (stage / "AlgoTypes.hpp").unlink()
            (stage / "AlgoTypes.hpp").symlink_to(hdr.resolve())
        inc = [str(stage), str(root), str(HERE)]
        flags += ["-mavx2", "-mfma"]
    tus += [str(p) for p in sorted(HERE.glob("film_profiles_data_*.cpp"))]

    exe = tmp / ("probe_avx2" if avx2 else "probe_scalar")
    cmd = [cxx] + flags
    for i in inc:
        cmd += ["-I", i]
    cmd += ["-o", str(exe)] + tus
    r = subprocess.run(cmd, cwd=tmp, capture_output=True, text=True)
    if r.returncode != 0:
        tail = (r.stderr or r.stdout).strip().splitlines()
        raise SystemExit("[!] %s probe did not compile:\n  %s"
                         % ("AVX2" if avx2 else "scalar",
                            "\n  ".join(tail[:14])))
    return exe


def run_probe(exe: Path):
    r = subprocess.run([str(exe)], capture_output=True, text=True)
    if r.returncode != 0:
        raise SystemExit("[!] probe failed: %s" % (r.stderr or r.stdout)[:400])
    size = None
    rows: dict[tuple[int, float], tuple[float, float]] = {}
    tab: dict[int, list[tuple[float, float, float]]] = {}
    off: dict[int, tuple[float, float]] = {}
    dom: dict[int, tuple[float, float]] = {}
    for line in r.stdout.splitlines():
        f = line.split()
        if not f:
            continue
        if f[0] == "SIZEOF":
            size = int(f[1])
        elif f[0] == "TAB":
            tab.setdefault(int(f[1]), []).append(
                (float(f[3]), float(f[4]), float(f[5])))
        elif f[0] == "OFF":
            off[int(f[1])] = (float(f[2]), float(f[3]))
        elif f[0] == "DOM":
            dom[int(f[1])] = (float(f[2]), float(f[3]))
        elif f[0] == "ROW":
            rows[(int(f[1]), float(f[2]))] = (float(f[3]), float(f[4]))
        elif f[0] in ("MISSING", "NOTABLE"):
            raise SystemExit("[!] the probe reported %s for %s" % (f[0], f[1]))
    return size, tab, off, dom, rows


def run(do_assert: bool = True) -> int:
    root = Path(os.environ.get("FILMSIM_ROOT", "/root/work/proot"))
    if not (root / "AlgoCharacteristicCurve.hpp").is_file():
        print("[SKIP] measured_curve_parity.py -- AlgoCharacteristicCurve.hpp "
              "is not in the engine tree at %s" % root)
        return 0

    curves = measured_curves()
    if not curves:
        print("[SKIP] measured_curve_parity.py -- no curve in the database "
              "carries instrument samples")
        return 0

    args = probe_args(curves)
    fail: list[str] = []
    print("=== measured-curve parity: %d curve(s), %d probe arguments ==="
          % (len(curves), len(args)))
    for name, k, c in curves:
        m = c.measured
        print("  %-22s %s  %d samples, log H %.3f .. %.3f  (%s)"
              % (name, "rgb"[k], len(m.log_h), m.log_h[0], m.log_h[-1],
                 m.condition))

    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td)
        for avx2 in (False, True):
            exe = build_probe(root, tmp, avx2, curves, args)
            tag, tol = ("AVX2", TOL_AVX2) if avx2 else ("scalar", TOL_SCALAR)
            if exe is None:
                print("  [SKIP] %s -- project not present" % tag)
                continue
            size, tab, off, dom, cpp = run_probe(exe)
            print("  %-6s sizeof(AlgoType) = %d" % (tag, size))

            worst_d, worst_at = 0.0, ""
            worst_lut = 0.0
            for n, (name, k, c) in enumerate(curves):
                m = c.measured

                # -- 1. the shipped table, element by element ----------------
                got = tab.get(n, [])
                if len(got) != len(m.log_h):
                    fail.append("%s: %s %s -- %d samples in C++, %d in Python"
                                % (tag, name, "rgb"[k], len(got), len(m.log_h)))
                else:
                    wx = max(abs(a - b[0]) for a, b in zip(m.log_h, got))
                    wd = max(abs(a - b[1]) for a, b in zip(m.density, got))
                    wm = max(abs(a - b[2]) for a, b in zip(m.slopes, got))
                    # Same float32 storage limit on both builds: the
                    # table is `const float` whatever AlgoType is.
                    lim = 1e-6
                    if max(wx, wd, wm) > lim:
                        fail.append(
                            "%s: %s %s -- the emitted table differs from the "
                            "database: x %.3g, d %.3g, slope %.3g"
                            % (tag, name, "rgb"[k], wx, wd, wm))

                # -- 2. the LUT domain must cover the samples ----------------
                if n in dom:
                    dlo, dhi = dom[n]
                    if dlo > m.log_h[0] + 1e-6 or dhi < m.log_h[-1] - 1e-6:
                        fail.append(
                            "%s: %s %s -- the curve table spans %.4f..%.4f but "
                            "the samples run %.4f..%.4f, so the vector path "
                            "would CLAMP part of the measurement away"
                            % (tag, name, "rgb"[k], dlo, dhi,
                               m.log_h[0], m.log_h[-1]))

                # -- 3. the interpolant itself -------------------------------
                for a in args:
                    key = (n, a)
                    if key not in cpp:
                        fail.append("%s: %s %s at %.6f missing from the probe"
                                    % (tag, name, "rgb"[k], a))
                        continue
                    cd, ct = cpp[key]
                    pd = float(FS.density_scalar(a, c))
                    e = abs(pd - cd)
                    if e > worst_d:
                        worst_d, worst_at = e, "%s %s at %.4f" % (
                            name, "rgb"[k], a)
                    if e > tol:
                        fail.append("%s: %s %s at %.6f -- python %.9g vs "
                                    "c++ %.9g" % (tag, name, "rgb"[k], a,
                                                  pd, cd))
                    worst_lut = max(worst_lut, abs(cd - ct))

            print("     worst |python - c++|  = %.3g  (%s), tolerance %g"
                  % (worst_d, worst_at or "-", tol))
            print("     worst |exact - table| = %.3g   -- the tabulated path "
                  "the vector build uses, against the closed evaluation"
                  % worst_lut)
            if worst_lut > TOL_AVX2:
                fail.append("%s: the curve table is %.3g D from the exact "
                            "evaluation, over the %g limit"
                            % (tag, worst_lut, TOL_AVX2))

    # -- the property that motivated the whole feature ----------------------
    for name, k, c in curves:
        m = c.measured
        acc = 0.0
        for x, d in zip(m.log_h, m.density):
            e = FP._tone_softplus_density(x, c) - d
            acc += e * e
        rms = (acc / len(m.log_h)) ** 0.5
        atsample = max(abs(float(FS.density_scalar(x, c)) - d)
                       for x, d in zip(m.log_h, m.density))
        print("  %-22s %s  fit is %.4f D rms from the table; the renderer "
              "returns the table itself to %.2e"
              % (name, "rgb"[k], rms, atsample))
        if atsample > 1e-6:
            fail.append("%s %s: the renderer does not reproduce its own "
                        "samples (worst %.3g)" % (name, "rgb"[k], atsample))
        if rms < 1e-4:
            fail.append(
                "%s %s: the fit reproduces the table to %.3g D rms, so the "
                "table buys nothing and storing it is not justified -- either "
                "the samples were generated FROM the fit, or this stock does "
                "not need a measured curve" % (name, "rgb"[k], rms))

    if fail:
        print("\n".join(["", "FAILURES:"] + ["  " + f for f in fail]))
        return 1
    print("\n[OK] measured_curve_parity.py -- Python, scalar and AVX2 agree on "
          "%d measured curve(s) over %d arguments; the emitted tables match "
          "the database and every renderer returns the instrument's own "
          "numbers at the sample points" % (len(curves), len(args)))
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=None)
    ap.add_argument("--assert", dest="assert_", action="store_true")
    ns = ap.parse_args()
    if ns.root:
        os.environ["FILMSIM_ROOT"] = ns.root
    return run(ns.assert_)


if __name__ == "__main__":
    raise SystemExit(main())
