#!/usr/bin/env python3
"""Stage and zip the six delivery archives. Strictly separated, by design.

⚠ SIX ARCHIVES, NOT ONE, AND THE SEPARATION IS THE POINT. The owner integrates
each into a different place: the generator into `PYTHON/profile_generator`, the
database into `CPP/Algorithm/FilmProfile`, the two engines into
`CPP/Algorithm/Scalar` and `CPP/Algorithm/AVX2`, the Markdown into the doc
tree, and the mockup and the two parameter PDFs into the UI documentation. A
single archive would make every delivery a merge.

⚠ THE SIXTH IS NEW ON 2026-09-17b AND CARRIES NO CODE. The HTML control-surface
mockup and the English and Russian parameter references were previously handed
over outside the numbered set, which meant the one deliverable describing the
CONTROL SURFACE had no place in the delivery that changed it. It is archive 6
now, on the same rule as the other five.

⚠ AND THE TWO ENGINE ARCHIVES ARE NEVER MERGED INTO ONE GENERIC TREE. The
scalar twin computes in `double` and the AVX2 twin in `float`; they are two
files carrying one law, and the project's own rule is that they stay two files.
`interimage_parity.py` now compiles BOTH and compares each to the Python
reference, which is what makes keeping them separate safe rather than merely
tidy.

What each archive holds is listed in `MANIFEST` below with the reason, so a
future reader does not have to infer the layout from the zip.
"""

from __future__ import annotations

import os
import shutil
import zipfile
from datetime import date
from pathlib import Path

HERE = Path(__file__).resolve().parent
CPP = Path("/root/work/tst")           # the live, editable engine tree
OUT = Path(os.environ.get("FILMSIM_DELIVER_OUT", "/root/work/deliver23"))
#: ⚠ SUFFIXED. A second delivery was cut on the same day at schema v30,
#: and two archives named for one date cannot be told apart on disk. 2026-09-17
#: is the same case again: the 'a' set went out at schema v37 with 186 stocks,
#: this 'b' set has 191 and the six-archive layout.
#: ⚠ 2026-09-28c: overridable, because a third set was cut on 2026-09-28 and the
#: date alone would have overwritten the first set's names in DELIVERY.
STAMP = os.environ.get("FILMSIM_STAMP") or date.today().isoformat()

#: Generator sources: everything needed to REGENERATE the database.
#: ⚠ NOT everything needed to run every audit. Until 2026-09-10d this tuple's
#: output was joined by the generated C++, because `cpp_parity.py`,
#: `interimage_parity.py`, `spectral_mono_parity.py` and `field_coverage.py`
#: compile against it. The owner's directive that day was that the generator
#: archive carries no C++, so those four now need archive 2 unpacked beside
#: this one. See the note at the archive-1 assembly for the full reasoning.
#: ⚠ `*.md` IS ROOT-LEVEL ONLY and picks up Tasks.md. The doc/ TREE is
#: deliberately NOT in this archive: the owner's instruction is five
#: strictly separated components, and shipping the whole doc tree here as
#: well as in archive 5 made every delivery a two-place merge. Previous
#: deliveries did carry it; this one does not, on purpose.
PY_GLOBS = ("*.py", "*.txt", "*.lock", "*.md")

#: The generated database, in the layout the Visual Studio project expects.
DB_FILES = (
    "film_profiles.hpp", "film_profiles_detail.hpp", "film_profiles.cpp",
    # ⚠ NEW 2026-09-18e. The schema version and both of its accessors, in the
    # one generated header that is valid C as well as C++. film_profiles.hpp
    # includes it and restates no digits, so shipping the database without it
    # would not compile.
    "film_schema_version.h",
    "film_enum.hpp", "LoadFilmDataBase.h", "LoadFilmDataBase.cpp",
    # ⚠ NEW 2026-09-19d. Per-film control availability as a compile-time
    # bitmask, one uint64_t per film in database order. It ships with the
    # DATABASE rather than with either engine because it is indexed by
    # film::eFILM_PROFILE and static_asserts against eTOTAL_FILMS_PROFILES --
    # a copy in an engine archive would be a second file to keep in step with
    # the enumerators, which is the thing it exists to make impossible.
    "film_params_mask.hpp",
    # ⚠ NEW 2026-10-05, owner rule. The de-/serialization API of one
    # film::FilmProfile (GPU transfer buffer), generated by serial_codegen.py
    # from film_profiles.hpp on every build. It ships with the DATABASE
    # because its layout is a function of the schema and of nothing else; the
    # engines only include it.
    "film_profile_serial.hpp",
    "film_names.txt", "film_display_order.txt",
    # ⚠ SHIPS WITH THE DATABASE, 2026-09-08. The alphabetical re-sort moved 177
    # of 184 indices; this is the old -> new map, and it is the only thing that
    # can repair a project saved before the cutover. It belongs beside the
    # database it describes, not in a report.
    "film_id_migration.txt",
)

MANIFEST = """\
SEVEN ARCHIVES -- {stamp}
============================

Schema v61. 225 film stocks, 11 print stocks, 2 colour-paper spectral records,
14 gauges. Verify 1045 PASS / 4 baselined FAIL (saturation hierarchy + the
three G-SCRATCH guards whose harness is lost), all 41 translation units (39
data slots) compiling at -Wall -Wextra with zero bytes of output,
cpp_parity / chain_parity (225 stocks, Python = scalar = AVX2) /
spectral_mono_parity (84/84) / interimage / bromide / batch_position parity
green; film_serial_check 989 423 checks, 0 failures. Build failures = the
known 11-item baseline only.

ARCHIVES
--------
  1  python_generator      PYTHON/profile_generator  (no C++)
  2  generated_database    CPP/Algorithm/FilmProfile
  3  algorithm_scalar      CPP/Algorithm/Scalar
  4  algorithm_avx2        CPP/Algorithm/AVX2
  5  documentation_md      doc tree
  6  ui_mockup_and_pdf     UI documentation (mockup rev 14, EN/RU PDFs)
  7  cpp_tests             C++ test harnesses (test_chain_dump.cpp,
                           test_film_serial.cpp), flat

OWNER ACTION IN VISUAL STUDIO / CMAKE (2026-10-08)
--------------------------------------------------
  * NEW DATABASE SOURCE FILE: src/film_profiles_data_39.cpp (archive 2).
    The data slots went 38 -> 39 so that no generated function exceeds the
    112 000-byte limit (largest now 110 069). FilmProfile/CMakeLists.txt
    globs src/*.cpp, so re-run the CMake configure step; if the Visual
    Studio project lists its sources by hand, add film_profiles_data_39.cpp.
  * THREE NEW FILMS change the enumerator values (alphabetical storage):
    AGFA_AVIPHOT_PAN_400S, ROLLEI_PAN_25, ROLLEI_SUPERPAN_200. Saved
    projects map old indices through film_id_migration.txt. film_enum.hpp,
    film_params_mask.hpp, film_names.txt, film_display_order.txt and
    film_id_migration.txt are regenerated together.
  * FFT library: unchanged since FFT_2026-10-06.zip (not re-sent).
  * No new engine source file; no new control.

WHAT CHANGED SINCE 2026-10-06
-----------------------------
  * ENGINES (Scalar and AVX2): stage 9 DIR-coupler sub-pixel gate removed
    (owner decision). Both coupler terms now run whenever their radius is
    positive; the old 0.25 px cut-off switched them off abruptly on small
    frames (about 180-280 px wide for 35 mm). Files: AlgoDirCoupler.hpp,
    AlgoPassThrough.hpp, Algo_09_Sim.cpp, Algo_13_Sim.cpp, AlgorithmMain.cpp.
    VISIBLE only on small frames with couplers.
  * DATABASE, 2026-10-07: Fujifilm AF3-207U provenance corrected on 17 stocks
    (records only); KODAK EKTAR 100 completed from E-4046 (base, dye pair,
    no-correction reciprocity to 1 s).
  * DATABASE, 2026-10-07: HARMAN Dec 2023 reciprocity factors -- HP5 PLUS
    (P 1.31) and DELTA 3200 (P 1.33) onset 1 s with tables; KENTMERE PAN
    100 / 400 tables corrected.
  * DATABASE, 2026-10-07: ROLLEI folder review. ROLLEI_R3 curve traced,
    reciprocity table, polyester base; ROLLEI_INFRARED_400 curve, RMS 11;
    ROLLEI_RETRO_400 base and RMS 14 (from AGFA APX 400, owner decision);
    NEW ROLLEI_PAN_25 and ROLLEI_SUPERPAN_200.
  * DATABASE, 2026-10-07: NEW AGFA_AVIPHOT_PAN_400S (Agfa 01/2006 sheet):
    spectral to 820 nm, MTF, curve, RMS, resolving power, polyester base,
    live development-time family.
  * DATABASE, 2026-10-07: web reciprocity harvest -- CINESTILL_800T
    reciprocity p 1.0 -> 0.7407 (danhawk «Community» P 1.35, tier 3); all
    other web values confirmed stored figures or were not applicable.
  * Database order is strictly alphabetical (natural names) in every
    generated list; film_ids.lock frozen ids 222-224 appended.

Full accounts: doc/RESULT_2026-10-07b_rollei_folder.md (sections A-K),
doc/PROGRESS.md (2026-10-07 entries), doc/FilmDatabase_Charecteristics.MD
D.20.28-D.20.31 (and the Russian twin).

EARLIER CHANGES, ALREADY DELIVERED 2026-10-06
=============================================
WHAT CHANGED SINCE 2026-10-01
-----------------------------
  * Schema v61 (2026-10-01d): PrintingMatrix per negative (16 negatives print
    on 2383 through their own dyes), MTFSpec.combined_* (inert), the
    development_family rework (contrast-index families), temperature law
    keyed on contrast level; «Современные» held tables (786 points), 155
    kinetics curves (1139 points), dye panels, combined MTF on 7 stocks;
    Development Time on 33 stocks; SVEMA FOTO-250 gamma 0.795.
  * 2026-10-01e: NEW STOCK KODAK_HIE (eKODAK_HIE = 122; migrate projects with
    film_id_migration.txt) with six developer / format process variants;
    AGFA SCALA 200x push / pull ladder (five variants); Portra 160NC blue
    f50 60 -> 94; 27 of 28 book sensitivity panels corroborate the makers'
    records; SMPTE ST 2065-2 Academy Printing Density responsivities and 16
    per-negative scanner matrices stored INERT; book citations corrected to
    V. L. Likhachev, SLON-PRESS 2003.
  * Codegen: development points over 8 kB are emitted as helper functions in
    the same slot file (largest function 110 342 bytes, limit 112 000).
  * 2026-10-01f: stage 8b (Algo_08_Sim.cpp, Scalar and AVX2) on COLOUR
    NEGATIVES now leaves every neutral on the stored white-light curves (each
    layer measures a donor against that donor's density under a neutral
    exposure at the layer's own log E); interimage coefficients of all colour
    negatives re-solved. VISIBLE LOOK CHANGE on every colour negative: more
    contrast and saturation, much less grey-scale colour drift. Reversal
    unchanged. AGFA SCALA 200x Push 1-3 now use Agfa's own traced curves.
  * 2026-10-01g/h: FUJICOLOR_PRO_400H cyan (4th) record stored (inert); AVX2
    engine uses FMA at the last six multiply-then-add sites.
  * 2026-10-02: SCAN_DI is balanced PER COLOUR NEGATIVE (equal neutral system
    gamma per channel; Algo_13_Sim.cpp, AlgoDuplication.hpp) -- visible look
    change on colour negatives scanned through SCAN_DI: far less grey-scale
    colour drift. Small frames: the anchor solve and the print chain's mid
    grey now see stage 9's sub-pixel gate (AlgoDirCoupler.hpp,
    AlgorithmMain.cpp, Algo_13_Sim.cpp). Reversal stocks unchanged.
  * 2026-10-03: CONTROLS ARE CLAMPED ON ENTRY. New AlgoControlsClamped
    (AlgoControl.hpp/.cpp), called first in Algorithm_Main: every field is
    clamped to the Min/Max of AlgoControlEnums.hpp, non-finite numbers and
    unknown enumerators become defaults, filmProfile is clamped to the
    database. dupeStock must be an intermediate (DUPE_FINE_GRAIN or
    KODAK_VISION3_DI_2254); anything else becomes DUPE_FINE_GRAIN -- this was
    the black-and-white "binarization" with generations > 0. In-range values
    render bit-identically. Python generator: same dupeStock rule, new gate
    G-DUPE-INTERMEDIATE.
  * 2026-10-03: AVX2 review changes. AVX2/AlgoSeparableBlur.cpp (eight FMA
    accumulators, bit-identical), AVX2/Algo_05_Sim.cpp (vector halation
    softplus, <= 1.25e-6), Algo_04_Sim.cpp Scalar + AVX2 (coating grid
    capped at the frame size: fixes an overrun on frames under 192 px),
    AlgorithmMain.cpp / AlgoMemHandler.hpp (false RESTRICT removed),
    AlgoSpectralSensitivity.cpp (no per-frame heap allocation). Whole frame
    27-29 % faster at 1920 x 1080 on the review machine (not an i7-7700K).
  * 2026-10-04: PASS-THROUGH FORWARDING. AlgorithmMain.cpp + new
    AlgoPassThrough.hpp: a stage that would only copy its input is skipped
    and the current image is forwarded (20 stages; off under
    ALGO_RETAIN_ALL_STAGES). AVX2: corner defocus vectorised, interimage
    seed/snapshot copies removed, floor passes folded (stages 9, 12, 13),
    stage 13 prints in place; new AlgoApplyDensityMatrixFloored in both
    engines. Byte-identical to 2026-10-03 on 33 configurations. Portra
    1080p a further -16 % on the review host (not an i7-7700K).
  * 2026-10-04: DATABASE. The seven Лихачев combined-MTF stocks
    (VERICOLOR III, CENTURIA SUPER 400/1600, VX 100, CHROME R100,
    EKTACHROME 64, KODACHROME 64) now carry the curve's roll-off exponent
    (mtf_rolloff_q, mtf_measured) and, on the five estimated ones, f50
    re-solved with it. VISIBLE: less modulation above f50 on these seven.
  * 2026-10-04: DEFECT FIXED IN THE GENERATED C++. FilmMtfKernel was a
    22-row literal in cpp_codegen while the Python table had 71 rows: 44 of
    the 70 stocks with a measured roll-off (FUJI VELVIA 50, KODAK TRI-X,
    T-MAX 100/400, the AGFA APX / OPTIMA / VISTA families, most FUJI
    negatives and slides) rendered the single-Gaussian fallback in BOTH C++
    engines while Python rendered the measured law. The tables are now
    emitted from the Python dicts (79 rows). VISIBLE on those 44 stocks in
    C++: the measured tail above f50, as Python already had it.
  * 2026-10-04: doc/DB_FIELD_USAGE.md (generated by field_usage.py): every
    database field with its Python / Scalar / AVX2 readers.
  * 2026-10-05: NEW GENERATED HEADER film_profile_serial.hpp (archive 2,
    with the database): SerializeFilmProfile / DeserializeFilmProfile /
    ValidateFilmProfileBuffer for ONE film::FilmProfile -- a contiguous
    little-endian buffer for GPU transfer, deserialized back INTO
    film::FilmProfile. No new data structure: serial_codegen.py derives the
    member tables from the struct definitions in film_profiles.hpp on every
    build. Carried: every numeric / bool / enum / array / vector / record
    member (read today or not) and the string KEYS the engines read; not
    carried: unread text and provenance. kMaxSerializedFilmProfileSize =
    81456 (KODAK_TMAX_P3200) on that day -- see 2026-10-06 below.
  * 2026-10-06: SERIALIZATION carries EVERY non-informational member of
    film::FilmProfile (groups B and C: planned / not-yet-read and Python-read
    fields, strings included, populated or empty); only 27 informational
    members are excluded (provenance, param_sources, description / era /
    source strings, taking_filter.designation, the speed label).
    kMaxSerializedFilmProfileSize = 81680 (KODAK_TMAX_P3200), 40 sections;
    film_serial_check.py: 222 profiles, 976 770 bit-exact checks, 0 failures.
  * 2026-10-06: MAXIMUM-FLOW ALIGNMENT. C++ now reads the per-record halation
    radius scales (G2) and the measured taking-filter transmission (G3), and
    gains the controls spectralTaking (G4, bit 47) and grainTemporalMode (G6,
    bit 48) the Python reference already had.
  * 2026-10-06: THE OWNER'S FFT IN BOTH ENGINES. Flare, halation, emulsion
    MTF, DIR coupler, scan MTF + misregistration, duplication and reseau
    apply film_sim's frequency-domain transfers EXACTLY (AlgoFrequency.hpp);
    the separable approximations, the FilmMtfKernel fits and their sub-pixel
    gates are gone from the engines. VISIBLE in C++: edges, halos and fine
    detail now match Python -- chain_parity compares every pixel, worst
    1.75e-5 display-linear over 222 stocks (it was 0.10 at edges). Whole-frame
    AVX2 time +2 % to +15 % on the review host (not an i7-7700K); halation
    about 2x faster, MTF / coupler / scan slower.
  * 2026-10-06: DATABASE. 18 adjacency pairs (A4/T2 stocks with a measured q)
    re-solved against the exact law the renderers now apply (owner-approved);
    each renders its sheet's printed overshoot peak. VISIBLE: the low-frequency
    edge lift on those 18 stocks moves by up to 0.025 in modulation.
  * 2026-10-06: UI documentation revision 14 (new group Spectral & Temporal).

Full accounts: doc/RESULT_2026-10-01d_kinetics_dyes_mtf.md,
doc/RESULT_2026-10-01e_queue_followups_hie_scala_apd.md,
doc/RESULT_2026-10-01f_interimage_neutral_scala.md,
doc/RESULT_2026-10-02_scan_balance_smallframe_reversal_test.md,
doc/RESULT_2026-10-03_control_clamp_dupe_avx2_review.md,
doc/RESULT_2026-10-04_passthrough_mtfq_fieldusage.md,
doc/RESULT_2026-10-05_film_serial.md,
doc/RESULT_2026-10-06_fft_alignment_serial.md.

Regenerated together from one build: film_profiles.*, film_schema_version.h,
film_enum.hpp, film_names.txt, film_display_order.txt, film_id_migration.txt,
film_params_mask.hpp, film_profile_serial.hpp, LoadFilmDataBase.*, film_profiles_data_01..39.cpp,
algo_control_enums.py, doc/FilmControlMatrix.md, doc/FilmActiveProfiles.md.

NO TEST CODE IN ARCHIVES 1-4 (owner instruction); the harness ships only in 7. AlgoControlEnums.hpp
carries the owner's Splice & Tear block verbatim. Films are in alphabetical
order in every generated list.
"""


def _zip(name: str, root: Path, files: list[Path]) -> Path:
    OUT.mkdir(parents=True, exist_ok=True)
    z = OUT / name
    with zipfile.ZipFile(z, "w", zipfile.ZIP_DEFLATED) as zf:
        for f in sorted(files):
            zf.write(f, f.relative_to(root).as_posix())
    return z


def _is_test_source(name: str) -> bool:
    """True for a file that is a test or a profiling harness, not production.

    ⚠ `profall.cpp` IS ON THIS LIST AND IT DOES NOT MATCH `test_`. It is a
    profiling driver with its own `main`, so shipping it in an archive whose
    stated contents are "the production algorithm source" would put a second
    entry point in the build. Matching on the prefix alone would have missed
    it, which is why this is a function rather than a `startswith` at the
    call site.
    """
    # ⚠ `e2e.cpp` JOINED THE LIST ON 2026-09-18e. It is the whole-chain dump
    # the Python reference is compared against -- a third entry point with its
    # own `main`, writing /tmp/e2e_cpp.bin -- and it had been shipping inside
    # both engine archives since the list was written, because it matches
    # neither `test_` nor `profall.cpp`. The owner's instruction this delivery
    # is that no test code appears in the C++ or Python packages at all.
    return (name.startswith("test_")
            or name in ("profall.cpp", "e2e.cpp"))


def stage_engine(kind: str) -> Path:
    """One engine tree in the include/ + src/ layout the owner's CMake expects.

    ⚠ THE AVX2 TREE IS THE SCALAR TREE WITH THE 18 VECTOR TWINS OVERLAID, which
    is exactly how the project is organised: the twins replace the per-stage
    .cpp files and AlgoTypes.hpp, and every other header is shared. Copying the
    shared set first and the twins second is what makes the overlay correct --
    the same ordering `interimage_parity.stage_avx2_tree` relies on, and for the
    same reason.
    """
    dst = OUT / "stage" / kind
    if dst.exists():
        shutil.rmtree(dst)
    (dst / "include").mkdir(parents=True)
    (dst / "src").mkdir(parents=True)
    # ⚠ film_schema_version.h JOINS THE SKIP SET ON 2026-09-18e for the same
    # reason every other name here is on it: it is the DATABASE's header and
    # ships in archive 2. film_profiles.hpp includes it, so an engine building
    # against archive 2 has it; a second copy inside archives 3 and 4 would be
    # two files carrying one version literal, which is the one thing that
    # header exists to prevent.
    skip = {"film_profiles.hpp", "film_profiles_detail.hpp", "film_enum.hpp",
            "film_schema_version.h", "film_profile_serial.hpp",
            "LoadFilmDataBase.h", "LoadFilmDataBase.cpp", "film_profiles.cpp"}
    for p in sorted(CPP.iterdir()):
        if not p.is_file() or p.name in skip:
            continue
        if p.name.startswith("film_profiles_data_"):
            continue
        # ⚠ NO TEST SOURCES IN A PRODUCTION ARCHIVE. Owner directive
        # 2026-09-11: "Please do not include C++ or C/C++ header test files in
        # any of the five primary project archives." The engine tree carries
        # thirteen of them beside the production stages -- test_*.cpp plus
        # profall.cpp, which is a profiling harness rather than a stage -- and
        # they compile against headers this archive does ship, so a reader
        # would reasonably take them for part of the build. They go in the
        # separate optional archive instead.
        if _is_test_source(p.name):
            continue
        if p.suffix in (".hpp", ".h"):
            shutil.copy(p, dst / "include" / p.name)
        elif p.suffix == ".cpp":
            shutil.copy(p, dst / "src" / p.name)
        elif p.suffix == ".txt":
            # ⚠ TXT GOES IN include/, ON THE OWNER'S INSTRUCTION, and it is
            # not an arbitrary placement: film_names.txt and
            # film_display_order.txt are read at runtime beside the generated
            # database headers, so they belong where the headers are rather
            # than beside the sources that never open them.
            shutil.copy(p, dst / "include" / p.name)
    if kind == "AVX2":
        for p in sorted((CPP / "AVX2").iterdir()):
            if not p.is_file() or _is_test_source(p.name):
                continue
            sub = "include" if p.suffix in (".hpp", ".h", ".txt") else "src"
            shutil.copy(p, dst / sub / p.name)
    for extra in ("CMakeLists.txt",):
        src = Path("/root/work/deliver") / kind / extra
        if src.is_file():
            shutil.copy(src, dst / extra)
    return dst


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    _manifest = MANIFEST.format(stamp=STAMP)
    if os.environ.get("FILMSIM_NO_TESTS"):
        # Six-archive delivery: say so, rather than list an archive not sent.
        _manifest = _manifest.replace("SEVEN ARCHIVES -- ", "SIX ARCHIVES -- ", 1)
        _manifest = _manifest.replace(
            "  7  cpp_tests ", "  7  (not shipped in this delivery) cpp_tests ", 1)
    (OUT / "MANIFEST.txt").write_text(_manifest, encoding="utf-8")

    # ---- 1. python generator ----------------------------------------------
    # ⚠ NO C++ IN THIS ARCHIVE. Owner directive, 2026-09-10d: "don't put C++
    # code into archive with python". Until that date this archive also
    # carried the 24 `film_profiles_data_*.cpp` slot files plus every entry
    # in DB_FILES -- about 2 MB of generated C++, byte-for-byte duplicating
    # archive 2 -- on the argument that `cpp_parity.py`,
    # `interimage_parity.py`, `spectral_mono_parity.py` and
    # `field_coverage.py` compile against them and so would run out of the
    # box.
    #
    # ⚠ THE COST, STATED SO IT IS NOT A SURPRISE: those four audits now need
    # archive 2 unpacked beside this one before they will run. They fail with
    # a missing-file error, which is loud and immediate rather than a wrong
    # result. `build.py` is unaffected -- it generates the C++ itself before
    # running them.
    #
    # The directive is right on the larger point. Five archives exist so that
    # each drops into exactly ONE place in the owner's tree, and an archive
    # carrying another archive's payload turns every delivery into a merge
    # and invites two divergent copies of the same generated file. The
    # convenience was the exception; the separation is the rule.
    py = [p for g in PY_GLOBS for p in HERE.glob(g)]
    py = [p for p in dict.fromkeys(py) if p.is_file()]
    # ⚠ AND NO TEST APPARATUS ON THE PYTHON SIDE EITHER, 2026-09-18e. There
    # are no test_*.py modules in this generator and never have been, but
    # `make_test_chart.py` writes the synthetic ramp-and-disc frame the engines
    # are rendered against. It is testing apparatus rather than a generator
    # source, and the owner's instruction this delivery admits no test code in
    # the Python package. `build.py`, `verify.py` and the parity harnesses
    # stay: they are the build GATE, invoked by build.py itself, and removing
    # them would ship a generator that cannot check its own output.
    py = [p for p in py
          if not (p.name.startswith("test_") or p.name == "make_test_chart.py")]
    # ⚠ THE MEASURED INFLUENCE TABLE SHIPS WITH ITS GENERATOR. It is the only
    # .json in this archive and it is not configuration: it is the result of a
    # ~15 minute render sweep that `gen_realism_score.py` refuses to run
    # without, so a generator archive lacking it cannot reproduce
    # doc/REALISM_SCORE.md at all.
    _infl = HERE / "realism_influence.json"
    if _infl.is_file():
        py.append(_infl)
    # The hold-out residuals travel with the generator too: the Markdown in
    # archive 5 prints the worst 40 rows and the full set lives here.
    _hold = HERE / "holdout_predictions.json"
    if _hold.is_file():
        py.append(_hold)
    _cxx = [p for p in py if p.suffix in (".cpp", ".hpp", ".h", ".hxx", ".cc")]
    if _cxx:
        raise RuntimeError(
            "archive 1 would ship C++ (%s ...). PY_GLOBS has widened, and "
            "the owner's 2026-09-10d directive is that the generator archive "
            "carries no C++ at all."
            % ", ".join(p.name for p in _cxx[:3]))
    z1 = _zip(f"1_python_generator_{STAMP}.zip", HERE, py)

    # ---- 2. generated database --------------------------------------------
    db_stage = OUT / "stage" / "FilmProfile"
    if db_stage.exists():
        shutil.rmtree(db_stage)
    (db_stage / "include").mkdir(parents=True)
    (db_stage / "src").mkdir(parents=True)
    for n in DB_FILES:
        p = HERE / n
        if not p.is_file():
            continue
        sub = "include" if p.suffix in (".hpp", ".h") else "src"
        if p.suffix == ".txt":
            sub = "src"
        shutil.copy(p, db_stage / sub / n)
    for p in sorted(HERE.glob("film_profiles_data_*.cpp")):
        shutil.copy(p, db_stage / "src" / p.name)
    cm = Path("/root/work/deliver/FilmProfile/CMakeLists.txt")
    if cm.is_file():
        shutil.copy(cm, db_stage / "CMakeLists.txt")
    z2 = _zip(f"2_generated_database_{STAMP}.zip", db_stage,
              [p for p in db_stage.rglob("*") if p.is_file()])

    # ---- 3 and 4. the two engines, never merged ----------------------------
    sc = stage_engine("Scalar")
    av = stage_engine("AVX2")
    z3 = _zip(f"3_algorithm_scalar_{STAMP}.zip", sc,
              [p for p in sc.rglob("*") if p.is_file()])
    z4 = _zip(f"4_algorithm_avx2_{STAMP}.zip", av,
              [p for p in av.rglob("*") if p.is_file()])

    # ---- 5. documentation --------------------------------------------------
    # ⚠ BOTH CASES. `FilmDatabase_Charecteristics.MD` and its Russian twin
    # are spelled with an UPPERCASE extension, and this glob is
    # case-sensitive on Linux -- so until 2026-09-10 the two largest
    # requirement documents in the project were silently absent from
    # every documentation archive ever shipped.
    docs = sorted(set((HERE / "doc").rglob("*.md"))
                  | set((HERE / "doc").rglob("*.MD"))) + \
        [p for p in (HERE / "doc").rglob("*.txt") if p.is_file()]
    # ⚠ ROOTED AT THE GENERATOR, NOT AT ITS PARENT, so entries read
    # `doc/NAME.md` and unzip straight over the owner's doc tree. Rooting at
    # the parent prefixed every entry with the working directory's own name,
    # which made the archive un-unzippable in place.
    man = HERE / "doc" / "MANIFEST.txt"
    shutil.copy(OUT / "MANIFEST.txt", man)
    docs += [man]
    z5 = _zip(f"5_documentation_md_{STAMP}.zip", HERE,
              [p for p in dict.fromkeys(docs) if p.is_file()])

    # ---- 6. UI mockup and the two parameter references ---------------------
    # ⚠ NO SOURCE, NO DATABASE, NO PROJECT MARKDOWN, and the generator that
    # BUILDS the two PDFs is deliberately not here either: it imports
    # `algo_control_enums` and `film_profiles`, so shipping it would put a
    # dependency on archives 1 and 2 inside an archive whose whole point is
    # that it stands alone on the documentation shelf. What ships is the
    # rendered output and the mockup it describes.
    ui = Path("/root/work/ui")
    ui_files = [ui / n for n in
                ("FilmSimulator_Mockup_v6.html",
                 "FilmSimulation_EffectControls_EN.pdf",
                 "FilmSimulation_EffectControls_RU.pdf",
                 "README.txt")]
    missing = [f.name for f in ui_files if not f.is_file()]
    if missing:
        raise RuntimeError("archive 6 is missing %s" % ", ".join(missing))
    z6 = _zip(f"6_ui_mockup_and_pdf_{STAMP}.zip", ui, ui_files)

    # ---- 7. C++ test harnesses, optional ------------------------------------
    # ⚠ ADDED 2026-09-28. Archives 3 and 4 exclude every test_*.cpp by owner
    # directive, and until today the harnesses therefore reached the owner's
    # disk in no archive at all -- which is how `test_stage_dump.cpp` and
    # `test_scratch_guard.cpp` were lost between sessions, and why three verify
    # guards and stage_parity can no longer run. This archive holds ONLY the C++
    # harnesses, flat, and nothing else: it changes no other archive's layout
    # and mixes no Python into C++.
    tests = sorted(p for p in CPP.iterdir()
                   if p.is_file() and p.suffix == ".cpp"
                   and p.name.startswith("test_"))
    avx_tests = (sorted(p for p in (CPP / "AVX2").iterdir()
                        if p.is_file() and p.name.startswith("test_"))
                 if (CPP / "AVX2").is_dir() else [])
    zips = [z1, z2, z3, z4, z5, z6]
    # ⚠ 2026-10-01e: the owner asked for SIX archives; FILMSIM_NO_TESTS=1 skips 7.
    if (tests or avx_tests) and not os.environ.get("FILMSIM_NO_TESTS"):
        tstage = OUT / "stage" / "cpp_tests"
        if tstage.exists():
            shutil.rmtree(tstage)
        tstage.mkdir(parents=True)
        for p in tests:
            shutil.copy(p, tstage / p.name)
        if avx_tests:
            (tstage / "AVX2").mkdir()
            for p in avx_tests:
                shutil.copy(p, tstage / "AVX2" / p.name)
        zips.append(_zip(f"7_cpp_tests_{STAMP}.zip", tstage,
                         [p for p in tstage.rglob("*") if p.is_file()]))

    for z in zips:
        with zipfile.ZipFile(z) as zf:
            print(f"  {z.name:44s} {z.stat().st_size/1024:9.1f} kB  "
                  f"{len(zf.namelist()):4d} files")
    print(f"[OK] {len(zips)} archives in {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
