; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24215.1 

include listing.inc

INCLUDELIB OLDNAMES

EXTRN	__imp_FlsAlloc:PROC
EXTRN	__imp_FlsFree:PROC
EXTRN	__imp_FlsSetValue:PROC
EXTRN	__imp_FlsGetValue:PROC
PUBLIC	DllMain
; Function compile flags: /Ogtp
; File e:\work\marat\adobe\premier_plugin.dev\imagelabcorei7\src\dllmain.cpp
;	COMDAT DllMain
_TEXT	SEGMENT
__formal$ = 8
ul_reason_for_call$ = 16
__formal$ = 24
DllMain	PROC						; COMDAT

; 24   : 	
; 25   : 	switch (ul_reason_for_call)
; 26   :     {
; 27   : 		case DLL_PROCESS_ATTACH:
; 28   : //			tlsIdx = TlsAlloc();
; 29   : //			if (TLS_OUT_OF_INDEXES == tlsIdx)
; 30   : //				return FALSE;
; 31   : 			// no break!!!	
; 32   : 		break;
; 33   : 
; 34   : 		case DLL_THREAD_ATTACH:
; 35   : //			if (true == ImageLabHDR_AllocSystemMemory(&pMemoryBlock))
; 36   : //			{
; 37   : //				TlsSetValue(tlsIdx, pMemoryBlock);
; 38   : //			}
; 39   : 		break;
; 40   : 
; 41   : 		case DLL_THREAD_DETACH:
; 42   : //			pMemoryBlock = reinterpret_cast<PImageLabHDR_SystemMemoryBlock>(TlsGetValue(tlsIdx));
; 43   : //			if (nullptr != pMemoryBlock)
; 44   : //			{
; 45   : //				TlsSetValue(tlsIdx, nullptr);
; 46   : //				ImageLabHDR_FreeSystemMemory(pMemoryBlock);
; 47   : //				pMemoryBlock = nullptr;
; 48   : //			}
; 49   : 		break;
; 50   : 
; 51   : 		case DLL_PROCESS_DETACH:
; 52   : //			pMemoryBlock = reinterpret_cast<PImageLabHDR_SystemMemoryBlock>(TlsGetValue(tlsIdx));
; 53   : //			if (nullptr != pMemoryBlock)
; 54   : //			{
; 55   : //				TlsSetValue(tlsIdx, nullptr);
; 56   : //				ImageLabHDR_FreeSystemMemory(pMemoryBlock);
; 57   : //				pMemoryBlock = nullptr;
; 58   : //			}
; 59   : //			TlsFree(tlsIdx);
; 60   : //			tlsIdx = ULONG_MAX;
; 61   : 		break;
; 62   : 
; 63   : 		default:
; 64   : 		break;
; 65   :     }
; 66   : 
; 67   :     return TRUE;

	mov	eax, 1

; 68   : }

	ret	0
DllMain	ENDP
_TEXT	ENDS
END
