#ifndef __IMAGE_LAB_LIGHTROOM_PRESETS_ENUMS_FILTER__
#define __IMAGE_LAB_LIGHTROOM_PRESETS_ENUMS_FILTER__


typedef enum {
    LR_PRESET_INPUT,
    LR_PRESET_TOTAL_PARAMS
}Item;


#endif // __IMAGE_LAB_LIGHTROOM_PRESETS_ENUMS_FILTER__