#ifndef __IMAGE_LAB_CHROMATIC_ABERRATION_FILTER_ENUMERATORS__
#define __IMAGE_LAB_CHROMATIC_ABERRATION_FILTER_ENUMERATORS__

#include "AE_Effect.h"

typedef enum {
    eCHROMATIC_ABERRATION_INPUT,
    eCHROMATIC_ABERRATION_TOTAL_CONTROLS
}eAVERAGE_FILTER_ITEMS;


#endif // __IMAGE_LAB_CHROMATIC_ABERRATION_FILTER_ENUMERATORS__