#ifndef __IMAGE_LAB_VIDEO_STABILIZATION_ENUMS_FILTER__
#define __IMAGE_LAB_VIDEO_STABILIZATION_ENUMS_FILTER__

#include "AE_Effect.h"

typedef enum {
    eIMAGE_SHARPENING_INPUT,
    eIMAGE_SHARPENING_TOTAL_CONTROLS
}eAVERAGE_FILTER_ITEMS;



#endif // __IMAGE_LAB_VIDEO_STABILIZATION_ENUMS_FILTER__