#ifndef __IMAGE_LAB2_COLOR_ENGINE_CCT_LUT__
#define __IMAGE_LAB2_COLOR_ENGINE_CCT_LUT__

#include "CCT_LUT_CIE_1931_2DEG.hpp"
#include "CCT_LUT_CIE_1964_10DEG.hpp"

#endif // __IMAGE_LAB2_COLOR_ENGINE_CCT_LUT__
