#pragma once

typedef enum
{
	eNOISE_CLEAN_NONE = 0,
	eNOISE_CLEAN_BILATERAL_LUMA,
	eNOISE_CLEAN_BILATERAL_RGB,
	eNOISE_CLEAN_PERONA_MALIK,
	eNOISE_CLEAN_BLIND_DENOISE,
	eNOISE_CLEAN_TOTAL_EFFECTS
}eNCLEAN_TYPE;