#ifndef __IMAGE_LAB_IMAGE_COLOR_TEMPERATURE_CONSTANTS_PROC__
#define __IMAGE_LAB_IMAGE_COLOR_TEMPERATURE_CONSTANTS_PROC__

template<typename T>
constexpr T tWhitePoint{ 6500 };

#endif /* __IMAGE_LAB_IMAGE_COLOR_TEMPERATURE_CONSTANTS_PROC__ */