#ifndef __IMAGE_LAB_AI_IMAGE_DENOISE_ENUMERATORS__
#define __IMAGE_LAB_AI_IMAGE_DENOISE_ENUMERATORS__


#include "AE_Effect.h"

typedef enum {
    eIMAGE_AI_DENOISE_INPUT,
    eIMAGE_AI_DENOISE_TOTAL_CONTROLS
}eAVERAGE_FILTER_ITEMS;



#endif // __IMAGE_LAB_AI_IMAGE_DENOISE_ENUMERATORS__