#ifndef __IMAGE_LAB_IMAGE_GEOMETRY_ENUMERATORS_FILTER__
#define __IMAGE_LAB_IMAGE_GEOMETRY_ENUMERATORS_FILTER__

#include "AE_Effect.h"

typedef enum {
    eIMAGE_GEOMETRY_INPUT,
    eIMAGE_GEOMETRY_TOTAL_CONTROLS
}eAVERAGE_FILTER_ITEMS;



#endif // __IMAGE_LAB_IMAGE_GEOMETRY_ENUMERATORS_FILTER__