import datetime
from colour.models.rgb.transfer_functions.arri import DATA_ALEXA_LOG_C_CURVE_CONVERSION as D
tbl = D["SUP 3.x"]["Linear Scene Exposure Factor"]
eis = [160, 200, 250, 320, 400, 500, 640, 800, 1000, 1280, 1600]
now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
def fnum(v): return repr(float(v))
L=[]; w=L.append
w("/*")
w(" * ARRI_LogC3_EI.hpp")
w(" *")
w(" * !!! GENERATED FILE - DO NOT EDIT MANUALLY !!!")
w(" *")
w(" * Per-Exposure-Index (EI) parameters for the ARRI LogC3 (LogC V3) curve,")
w(' * firmware SUP 3.x, method "Linear Scene Exposure Factor" (scene-referred).')
w(" * Correct decode for illuminant / CCT / white-balance estimation: yields")
w(" * scene-linear values (18%% grey -> ~0.18).")
w(" *")
w(" * Decode (encoded t in [0,1] -> linear x), with break = e*cut + f :")
w(" *     x = (t > break) ? (pow(10,(t-d)/c) - b) / a")
w(" *                     : (t - f) / e")
w(" *")
w(" * NOTE: the branch threshold is computed as e*cut+f at full precision")
w(" * (not a stored rounded value); this matches ARRI's definition and keeps")
w(" * the two curve segments continuous at the break.")
w(" *")
w(" * Valid EI range: 160 .. 1600. The compact parametric form does NOT hold")
w(" * above EI 1600 (soft shoulder). If EI is unknown, ARRI recommends EI 800")
w(" * (< ~10%% exposure-value deviation across EI 200..1600).")
w(" *")
w(" * Constants: ARRI ALEXA LogC Curve - Usage in VFX white paper, as")
w(" * tabulated in colour-science (authoritative reproduction).")
w(" * Generated on: " + now)
w(" * Standard    : C++14 (no newer features used)")
w(" */")
w("")
w("#ifndef __GENERATED_ARRI_LOGC3_EI_HPP__")
w("#define __GENERATED_ARRI_LOGC3_EI_HPP__")
w("")
w("#include <array>")
w("#include <cstddef>")
w("#include <cmath>")
w("")
w("namespace ARRI_LogC3")
w("{")
w("    // Parameters for one Exposure Index (fields per ARRI VFX white paper).")
w("    struct Params")
w("    {")
w("        int    ei;")
w("        double cut;")
w("        double a;")
w("        double b;")
w("        double c;")
w("        double d;")
w("        double e;")
w("        double f;")
w("    };")
w("")
w("    constexpr std::size_t COUNT = " + str(len(eis)) + "u;")
w("")
w("    // Ordered by ascending EI. Index 7 == EI 800 (the recommended default).")
w("    constexpr std::array<Params, COUNT> TABLE =")
w("    { {")
for ei in eis:
    cut,a,b,c,d,e,f,_ = tbl[ei]
    w("        {{ {:>4d}, {}, {}, {}, {}, {}, {}, {} }},".format(
        ei, fnum(cut), fnum(a), fnum(b), fnum(c), fnum(d), fnum(e), fnum(f)))
w("    } };")
w("")
w("    // Exact EI, else nearest tabulated EI. EI<=0 -> EI 800 (index 7).")
w("    inline const Params& params_for_EI(int ei) noexcept")
w("    {")
w("        std::size_t best = 7u;")
w("        if (ei > 0)")
w("        {")
w("            int bestDiff = -1;")
w("            for (std::size_t i = 0u; i < COUNT; ++i)")
w("            {")
w("                const int diff = (TABLE[i].ei > ei) ? (TABLE[i].ei - ei)")
w("                                                    : (ei - TABLE[i].ei);")
w("                if (bestDiff < 0 || diff < bestDiff) { bestDiff = diff; best = i; }")
w("            }")
w("        }")
w("        return TABLE[best];")
w("    }")
w("")
w("    // Decode LogC3 encoded t (normalized [0,1]) -> scene-linear, in type T.")
w("    template<typename T>")
w("    inline T decode(T t, const Params& p) noexcept")
w("    {")
w("        const T brk = static_cast<T>(p.e) * static_cast<T>(p.cut)")
w("                    + static_cast<T>(p.f);")
w("        if (t > brk)")
w("            return (std::pow(static_cast<T>(10),")
w("                             (t - static_cast<T>(p.d)) / static_cast<T>(p.c))")
w("                    - static_cast<T>(p.b)) / static_cast<T>(p.a);")
w("        return (t - static_cast<T>(p.f)) / static_cast<T>(p.e);")
w("    }")
w("")
w("    template<typename T>")
w("    inline T decode(T t, int ei) noexcept { return decode<T>(t, params_for_EI(ei)); }")
w("")
w("} // namespace ARRI_LogC3")
w("")
w("#endif // __GENERATED_ARRI_LOGC3_EI_HPP__")
open("ARRI_LogC3_EI.hpp","w").write("\n".join(L)+"\n")
print("regenerated")
