#ifndef __IMAGE_LAB_IMAGE_DEHAZE_ENUMERATORS__
#define __IMAGE_LAB_IMAGE_DEHAZE_ENUMERATORS__


#include "AE_Effect.h"

typedef enum {
    eIMAGE_DEHAZE_INPUT,
    eIMAGE_DEHAZE_TOTAL_CONTROLS
}eAVERAGE_FILTER_ITEMS;



#endif // __IMAGE_LAB_IMAGE_DEHAZE_ENUMERATORS__