#ifndef __IMAGE_LAB_FUZZYL_MEDIAN_FILTER_ENUMERATORS__
#define __IMAGE_LAB_FUZZYL_MEDIAN_FILTER_ENUMERATORS__

#include "AE_Effect.h"

typedef enum {
    eFUZZY_MEDIAN_FILTER_INPUT,
    eFUZZY_MEDIAN_FILTER_RADIUS,
    eFUZZY_MEDIAN_TOTAL_CONTROLS
}eAVERAGE_FILTER_ITEMS;


#endif // __IMAGE_LAB_FUZZYL_MEDIAN_FILTER_ENUMERATORS__