#ifndef __IMAGE_LAB2_ALGO_ADOBE_CONTROL_ENUMERATORS__
#define __IMAGE_LAB2_ALGO_ADOBE_CONTROL_ENUMERATORS__

#include "CompileTimeUtils.hpp"

enum class FilmSimulationCtrl : int32_t
{
    VIDEO_INPUT,
    SETUP_BUTTON, // button for run dialog control
    GROUP_START_FILM_PROPERTIES,
    FILM_STOCK,
    FILM_FORMAT,
    PROCESS_VARIANT,
    GROUP_STOP_FILM_PROPERTIES,
    GROUP_START_EXPOSURE_AND_TONE,
    EXPOSURE,
    EXPOSURE_TIME,
    MID_GRAY_TARGET,
    BLACK_POINT_STRETCH,
    GROUP_STOP_EXPOSURE_AND_TONE,
    GROUP_START_DEVELOPMENT,
    DEVELOPMENT_ENABLE,
    DEVELOPMENT_TIME,
    DEVELOPMENT_TEMPERATURE,
    YEARS_OF_DARK_STORAGE,
    GROUP_STOP_DEVELOPMENT,
    GROUP_START_COLOR_WHITE_BALANCE,
    SCENE_COLOUR_TEMPERATURE,
    WHITE_BALANCE_STRENGTH,
    GROUP_STOP_COLOR_WHITE_BALANCE,
    GROUP_START_PRINT_AND_DUPLICATION,
    PRINT_STOCK,
    DUPLICATION_GENERATION,
    INTERMEDIATE_STOCK,
    PRINT_GRAIN,
    GROUP_STOP_PRINT_AND_DUPLICATION,
    GROUP_START_EMULSION_CHARACTER,
    GRAIN,
    HALATION,
    DIR_COUPLERS,
    MISREGISTRATION,
    COATING_UNEVENNESS,
    RESEAU_RECONSTRUCTION,
    GROUP_STOP_EMULSION_CHARACTER,
    GROUP_START_LENS_AND_READER,
    VEILING_FLARE,
    CORNER_FALLOFF,
    SCANNER_SPECULARITY,
    GROUP_STOP_LENS_AND_READER,
    GROUP_START_FILM_DAMAGE_AND_AGE,
    ENABLE_FILM_DAMAGE,
    OVERALL_STRENGHT,
//    DAMAGE_SEED,
    DUST,
    DEBRIS,
    FIBRES,
    CLUMPING,
    GATE_DIRT,
    GATE_WAVE,
    SPLICE_AND_TEAR_EVENTS,
    TRANSPORT_SCRATCHES,
    HANDLING_SCRATCHES,
    PROCESSING_QUALITY,
    DRYING_MARKS,
    STORAGE_SEVERITY,
    COLOUR_VEIL,
    PRINTER_FLICKER,
    SCANNER_ARTIFACTS,
    TOTAL_PARAMS
};

constexpr char itemNames[][32] = {
    " ",
    "Film Stock",
    "Film Stock",
    "Film Format",
    "Process Variant",
    "Exposure & Tone",
    "Exposure",
    "Exposure Time",
    "Mid-Gray Target",
    "Black Point Stretch",
    "Development And Storage",
    "Development Enable",
    "Development Time",
    "Development Temperature",
    "Years of Dark Storage",
    "Colour & White Balance",
    "Scene Colour Temperature",
    "White Balance Strength",
    "Print & Duplication",
    "Print Stock",
    "Duplication Generation",
    "Intermediate Stock",
    "Print Grain",
    "Emulsion Character",
    "Grain",
    "Halation",
    "DIR Couplers",
    "Misregistration",
    "Coating Unevenness",
    "Reseau Reconstruction",
    "Lens and Reader",
    "Veiling Flare",
    "Corner Falloff",
    "Scanner Specularity",
    "Film Damage and Age",
    "Enable Film Damage",
    "Overall Strength",
    "Damage Seed",
    "Dust",
    "Debris",
    "Fibres",
    "Clumping",
    "Gate Dirt",
    "Gate Wave",
    "Splice and Tear Events",
    "Transport Scratches",
    "Handling Scratches",
    "Processing Quality",
    "Drying Marks",
    "Storage Severity",
    "Colour Veil",
    "Printer Flicker",
    "Scanner Artifacts"
};


#endif // __IMAGE_LAB2_ALGO_ADOBE_CONTROL_ENUMERATORS__