#pragma once

#include "CompileTimeUtils.hpp"

enum class FilmSimulationCtrl : int32_t
{
    VIDEO_INPUT,
    SETUP_BUTTON, // button for run dialog control
    FILM_STOCK,
    PRINT_STOCK,
    FILM_FORMAT,
    GENERATIONS,
    EXPOSURE_STOPS,
    SCENE_KELVIN,
    WB_STRENGTH,
    GREY_TARGET,
    GRAIN_SCALE,
    HALATION_SCALE,
    COUPLER_SCALE,
    SCANNER_F50,
    MISREG_SCALE,
    FLARE,
    PRINT_GRAIN,
    RESEAU,
    FILM_DAMAGE,
    DAMAGE_ENABLE,
    DAMAGE_PRESET,
    DUST_RATE_HZ,
    DUST_SIZE_UM,
    BLOB_RATE_HZ,
    SCRATCH_RATE_HZ,
    SCRATCH_EMULSION_BIAS,
    SPLISE_INTERVALS,
    FLICKER_STOPS,
    FLICKER_BASE_HZ,
    FLOCKER_COLOUR_SPREAD,
    WEAVE_AMP_XUM,
    WEAVE_AMP_YUM,
    WEAVE_HZ_CORNER,
    HAIR_RATE_HZ,
    GATE_DEFECT_RATE_HZ,
    DAMAGE_STRENGTH,
    DAMAGE_SEED,
    DITHER_OUTPUT,
    TOTAL_PARAMS
};