// Generated by cpp_codegen.py -- do not edit by hand.
// Physical film stock parameters. Regenerate after changing film_profiles.py.
//
// schema_version 2 (2026-07 domain review). Mirrors
// film_profiles.SCHEMA_VERSION; see kSchemaVersion below.
//
// FEATURE FLAGS ARE DERIVED AND NON-AUTHORITATIVE (DM-20). The Feature
// bitmask is a convenience summary of the numeric fields for UI and tooling.
// A renderer must key its behaviour on the numeric fields themselves
// (halation gains, coupler strengths, has_reseau, ...), never on the flags.
// The Python validate_all() only warns on flag/numeric disagreements.
//
// Densitometry (DM-06/DM-18): every curve and granularity figure is expressed
// in the metric named by its density_metric field -- "status_m" for colour
// negative, "status_a" for colour reversal and print stocks, "visual_iso"
// for B&W silver. Do not mix metrics when comparing stocks.
//
// Trim semantics (DM-06): for reversal stocks the curve abscissa is
//     x = -log10(relative exposure) - trim.
// The stored trim is a *static* calibration value (currently 0.0 for every
// stock); the reference renderer refines it per render with a per-channel
// anchor solve (solve_anchors in film_sim.py), and a C++ port should do the
// same or accept mid-grey landing slightly off target.
//
// Reference formulae, so a C++ port cannot drift from the Python original:
//
//   Characteristic curve, with sp(x,k) = k*log1p(exp(x/k)):
//       D(x) = dmin + gamma * ( sp(x - toe_x, toe_k)
//                             - sp(x - shoulder_x, shoulder_k) )
//       negative stocks: x =  log10(relative exposure)
//       reversal stocks: x = -log10(relative exposure) - trim
//
//   Modulation transfer, f in cycles/mm (legacy Gaussian core; see MTFSpec
//   for the optional v2 tail term):
//       MTF(f) = exp(-ln2 * (f/f50)^2) * lift(f)
//       lift(f) = 1 + adjacency * (G(0.4*adjacency_um) - G(2.0*adjacency_um))
//       G(sigma_um) = exp(-2*pi^2 * (sigma_um/1000)^2 * f^2)
//
//   Grain power spectrum shape, f_hi = 1000/(2*clump_um):
//       H(f) = exp(-(f/f_hi)^2) * (1 + clump_gain*exp(-(f/(f_hi/6))^2)), H(0)=0
//     then scaled so that sigma(D) through a 48 um aperture equals
//     rms_granularity/1000 at density 1.0, and modulated per pixel by
//       sqrt(max(D - dmin, 0) + fog_grain)
//     (the legacy law; GrainSpec sigma_shape_* describes the v2 refinement).
//
//   All spatial quantities are converted to pixels with
//       px_per_mm = image_width_px / format_width_mm
//   which is what makes a profile look identical at any scan resolution.
#pragma once

#include <array>
#include <cstdint>
#include <string>
#include <vector>

namespace film {

/// Data-model schema version, mirrored from film_profiles.SCHEMA_VERSION.
constexpr int kSchemaVersion = 2;

/// Whether the developed film is a negative (needs printing) or already a
/// positive. Reversal stocks skip the print stage entirely.
enum class StockKind : std::uint8_t {
    Negative = 0,
    Reversal = 1
};

/// Optional per-stock behaviour. Bitmask: test with has(), never by name.
///
/// DERIVED AND NON-AUTHORITATIVE (DM-20): a summary of the numeric fields.
/// Renderers must key on the numeric fields, never on these flags.
enum class Feature : std::uint32_t {
    None               = 0,
    Halation           = 1u << 0,  ///< weak or absent anti-halation layer
    StrongDirCouplers  = 1u << 1,  ///< modern stock, strong inter-image effect
    UnevenEmulsion     = 1u << 2,  ///< loose QC, slow large-scale sensitivity drift
    OrthoResponse      = 1u << 3,  ///< reduced red sensitivity
    NoRemjet           = 1u << 4,  ///< remjet removed: extreme halation
    ThreeStrip         = 1u << 5,  ///< beam-splitter camera, three separate records
    TabularGrain       = 1u << 6,  ///< T-grain crystals rather than cubic
    MosaicReseau       = 1u << 7,  ///< additive colour via a physical filter grid
    NitrateBase        = 1u << 8   ///< cellulose nitrate support, pre-1951
};

inline Feature operator|(Feature a, Feature b) {
    return static_cast<Feature>(static_cast<std::uint32_t>(a) |
                               static_cast<std::uint32_t>(b));
}
inline bool has(Feature set, Feature flag) {
    return (static_cast<std::uint32_t>(set) &
            static_cast<std::uint32_t>(flag)) != 0u;
}

using Matrix3 = std::array<std::array<float, 3>, 3>;
using Vec3    = std::array<float, 3>;

/// One channel of a characteristic (Hurter-Driffield) curve. See the formula
/// block at the top of this file.
///
/// Monotonic provided shoulder_x > toe_x and shoulder_k <= 2 * toe_k.
/// For reversal stocks toe_x governs the *highlight* end, not the shadow end.
struct ToneCurve {
    float dmin;        ///< base + fog density, dimensionless
    float gamma;       ///< straight-line slope, density per decade of exposure
    float toe_x;       ///< toe position, in the curve's own x units
    float toe_k;       ///< toe softness
    float shoulder_x;  ///< shoulder position
    float shoulder_k;  ///< shoulder softness

    /// Asymptotic maximum density.
    float dmax() const { return dmin + gamma * (shoulder_x - toe_x); }
    /// Exposure range between toe and shoulder, in stops.
    float latitudeStops() const { return (shoulder_x - toe_x) * 3.321928f; }
};

/// Three characteristic curves, one per dye layer. Their divergence in the toe
/// and shoulder (crossover) is what produces a stock's colour signature -- it
/// is the real mechanism behind "Fuji cyan shadows", not an output tint.
struct RGBCurves {
    ToneCurve r;
    ToneCurve g;
    ToneCurve b;
};

/// Silver-halide grain description. Grain variance scales as sqrt(density)
/// because developed crystal counts are Poisson distributed; the renderer
/// applies that, this struct describes the emulsion.
///
/// Schema-v2 fields (DM-09/DM-10) follow the v1 block; their defaults in the
/// database were chosen so that ignoring them reproduces v1 output exactly.
struct GrainSpec {
    float rms_granularity;  ///< sigma(D)*1000 through a 48 um aperture at D=1.0
    float clump_um_r;       ///< mean developed clump diameter, micrometres
    float clump_um_g;       ///< micrometres
    float clump_um_b;       ///< micrometres
    float clump_gain;       ///< low-frequency lobe: cubic ~1.0, tabular ~0.2
    float fog_grain;        ///< grain floor at zero exposure, fraction of D=1.0
    float anisotropy;       ///< vertical/horizontal correlation, 1.0 = isotropic
    // -- schema v2 ----------------------------------------------------------
    float rms_r;            ///< per-channel RMS, same metric as rms_granularity;
                            ///< 0 = use rms_granularity (v1 rule). Colour
                            ///< negative: b ~1.3x, r ~1.1x of green. [tier 2]
    float rms_g;            ///< 0 = use rms_granularity
    float rms_b;            ///< 0 = use rms_granularity
    float sigma_shape_toe;  ///< sigma multiplier at D = dmin. The triple
                            ///< (0,1,0) means "legacy sqrt(D-dmin) law";
                            ///< negatives ~0.4/1.0/1.2 monotone, reversal
                            ///< ~0.7/1.0/0.5 turning over past mid. [tier 3]
    float sigma_shape_mid;  ///< sigma multiplier at D = 1.0
    float sigma_shape_dmax; ///< sigma multiplier at D = dmax
    float size_sigma_log;   ///< log-normal grain-size dispersion: 0.35 typical
                            ///< cubic, 0.55 fast/pushed, 0.25 T-grain. [tier 3]
    float cluster_um;       ///< super-clump correlation length, um; 0 = disabled
    float dye_cloud_um;     ///< dye-cloud diameter, um; 0 for B&W silver,
                            ///< ~1.5-2.5 for colour stocks. [tier 2]
};

/// Per-layer modulation transfer. Blue is the top layer and therefore
/// sharpest; red sits at the bottom of the stack behind two layers of gelatin
/// and is the softest. That ordering is physical, not stylistic.
///
/// Schema-v2 fields (DM-11): datasheet resolving power (0 = not published --
/// deliberately not invented) and an optional non-Gaussian tail,
///   MTF(f) = a*exp(-ln2*(f/f50)^2) + (1-a)*exp(-(f/f50)^p)
/// with a = mtf_tail_a (1.0 = pure Gaussian legacy) and p = mtf_tail_f_exp.
struct MTFSpec {
    float f50_r;         ///< cycles/mm at 50% modulation
    float f50_g;         ///< cycles/mm
    float f50_b;         ///< cycles/mm
    float adjacency;     ///< development adjacency overshoot, 0 disables
    float adjacency_um;  ///< spatial scale of that overshoot, micrometres
    // -- schema v2 ----------------------------------------------------------
    float resolving_power_lp_mm_lowc;   ///< lp/mm at 1.6:1 TOC; 0 = unknown
    float resolving_power_lp_mm_highc;  ///< lp/mm at 1000:1 TOC; 0 = unknown
    float mtf_tail_a;                   ///< Gaussian-core weight; 1.0 = legacy
    float mtf_tail_f_exp;               ///< tail exponent; 0.0 = unused
};

/// Base-reflection glow. Must be added to linear exposure before the
/// characteristic curve, never to output pixels afterwards, and must conserve
/// energy: light scattered away from a point is removed from it.
struct HalationSpec {
    Vec3  radii_um;          ///< three Gaussian sigmas, micrometres, small to large
    Vec3  weights;           ///< relative energy, normalised by the renderer
    float gain_r;            ///< red penetrates deepest, so dominates
    float gain_g;
    float gain_b;
    float threshold_stops;   ///< soft knee position above mid grey
};

/// Development-Inhibitor-Releasing coupler behaviour: raises saturation without
/// raising gamma, and adds a local adjacency edge effect. Zero for Kodachrome,
/// whose dyes were formed in the processing machine rather than in the film, and
/// zero for every pre-1950 stock because the chemistry did not exist yet.
struct CouplerSpec {
    float strength;       ///< cross-layer inhibition, 0 disables
    float radius_um;      ///< inhibitor diffusion distance, micrometres
    float edge_strength;  ///< short-range adjacency component
    float edge_um;        ///< micrometres
};

/// Additive colour filter grid ruled onto the film base (Dufaycolor and kin).
///
/// Not a variant of the layered model but a different imaging system: one
/// panchromatic emulsion behind a microscopic colour grid. Consequences the
/// layered path cannot express -- colour resolution capped by the grid pitch
/// rather than the emulsion, a single grain field with no inter-layer effects of
/// any kind, about two stops lost to filter absorption, and the grid itself
/// faintly visible as texture.
///
/// Geometry for pattern "dufay": continuous red lines with blue and green
/// squares chequered between them, each colour about a third of the area.
/// Applied to linear EXPOSURE (the light passes the grid before reaching the
/// emulsion); reconstructed at viewing time by a mask-weighted local average,
/// num = blur(record * mask_c), den = blur(mask_c), out_c = num / den.
///
/// Requires at least 3 pixels per cell to represent at all; below that the
/// reference implementation disables the mosaic and warns rather than emit
/// aliasing noise.
struct ReseauSpec {
    float lines_per_mm;   ///< grid pitch on the film
    /// What each filter passes: rows in R/G/B filter order, columns in R/G/B
    /// light order, so filter_matrix[0][1] is green light through the red filter.
    /// The off-diagonal terms are why additive colour looks pastel -- ruled
    /// gelatin filters have broad overlapping passbands. Model them as pure and
    /// the process comes out more saturated than Kodachrome, which is backwards.
    Matrix3 filter_matrix;
    std::string pattern;           ///< only "dufay" is defined
    float reconstruction_pitches;  ///< reconstruction blur radius, in grid pitches
};

/// Per-stock temporal behaviour for moving-image rendering (schema v2, DM-13).
///
/// ALL VALUES ARE TIER-3 ESTIMATES: era-typical figures for the camera /
/// printer / projector chain a stock normally passed through, not
/// measurements of a specific emulsion. Still renders ignore this struct.
struct TemporalSpec {
    float weave_amp_x_um;   ///< RMS horizontal gate weave, um on the negative
                            ///< (silent era ~20, 1950s ~10, modern ~3)
    float weave_amp_y_um;   ///< RMS vertical gate weave, micrometres
    float weave_hz_corner;  ///< corner frequency of the weave spectrum, Hz
    float flicker_pct;      ///< RMS exposure flicker, percent (early 4-6,
                            ///< 1950s ~1.5, modern ~0.2)
    float flicker_hz;       ///< corner frequency of the flicker spectrum, Hz
    float grain_frame_correlation;      ///< 0 = fresh grain field every frame
    float dirt_events_per_frame;        ///< expected visible dirt events/frame
    float scratch_persistence_frames;   ///< mean running-scratch lifetime
    float fps_native;       ///< native shooting/projection frame rate
};

/// Schwarzschild reciprocity failure (schema v2, DM-07). Effective exposure
/// past onset: E_eff = I * t^p, p <= 1. p = 1.0 means no failure (correct for
/// normal cine exposure times and the v1 behaviour). Tier-2/3 estimates
/// except where a datasheet documents them (Acros: no correction to 120 s).
struct ReciprocitySpec {
    float schwarzschild_p_r;  ///< per-channel exponent; 1.0 = no failure
    float schwarzschild_p_g;
    float schwarzschild_p_b;  ///< channel spread = long-exposure colour cast
    float onset_s;            ///< seconds below which no correction applies
};

/// Storage-age damage model (schema v2, DM-01). ALL ZEROS = FRESH STOCK.
/// Data hooks only for now: every profile ships fresh and the reference
/// renderer does not yet consume this struct.
struct AgingSpec {
    float dye_fade_c;          ///< fractional cyan dye fade, 0-1
    float dye_fade_m;          ///< magenta (usually survives longest)
    float dye_fade_y;          ///< yellow
    float base_yellowing_d;    ///< base yellowing, blue-density lift
    float dmin_lift;           ///< uniform fog growth, density
    float shrinkage_pct;       ///< base shrinkage, percent
    float scratch_rate_base_per_m;      ///< base-side scratches per metre
    float scratch_rate_emulsion_per_m;  ///< emulsion-side scratches per metre
    float dust_area_ppm;       ///< dust coverage, ppm of frame area
    float mottle_amplitude;    ///< storage mottle amplitude, density fraction
    float mottle_scale_mm;     ///< storage mottle spatial scale, millimetres
};

/// Where a profile's numbers come from (schema v2, DM-19). Machine-readable
/// form of the [T1]/[T2]/[T3] tags in the descriptions.
struct Provenance {
    int tier;  ///< 1 datasheet-grounded, 2 partially grounded, 3 reconstruction
    std::vector<std::string> sources;  ///< full citations, "Document title,
                                       ///< Publisher, year"; or an explicit
                                       ///< "No official manufacturer
                                       ///< datasheet available" placeholder
    std::string fitted_from;   ///< "datasheet_curve"|"secondary_sources"|"analogy"
    std::string last_reviewed; ///< ISO date of the last data review
};

/// Complete film stock.
struct FilmProfile {
    std::string name;
    std::vector<std::string> aliases;  ///< catalogue numbers and common names
    std::string description;
    std::string era;
    StockKind kind;
    bool  is_monochrome;      ///< single silver image instead of three dye layers
    int   exposure_index;     ///< ISO / EI rating
    int   balance_kelvin;     ///< colour temperature the stock is balanced for
    RGBCurves    curves;
    GrainSpec    grain;
    MTFSpec      mtf;
    HalationSpec halation;
    CouplerSpec  couplers;
    /// 3x3 applied to *linear exposure*: the spectral sensitivity of each
    /// record. Identity for an integral tripack; strongly off-diagonal for a
    /// Technicolor beam-splitter camera, whose broad overlapping taking filters
    /// are the origin of its famous reds. It must be applied before the
    /// characteristic curve -- the curve is nonlinear, so a later matrix cannot
    /// reproduce it.
    Matrix3 taking_matrix;
    /// 3x3 applied to the *density* vector: impure dye absorption plus scanner
    /// crosstalk. Negative off-diagonals sharpen colour separation
    /// (Kodachrome, Technicolor imbibition dyes); positive off-diagonals muddy
    /// it (ORWOcolor). Row-major, near identity.
    Matrix3 dye_matrix;
    /// Scene RGB to single-layer exposure weights for monochrome stocks.
    /// NOT video luma -- panchromatic film has its own spectral sensitivity,
    /// which is why B&W renders red dark and blue sky light.
    Vec3 spectral_weights;
    /// Residual film base cast after printer lights neutralise the mask.
    Vec3 base_tint;
    /// RMS channel registration error on the negative, micrometres, so it
    /// scales with resolution like every other spatial quantity. Tens of
    /// micrometres for three-strip Technicolor: hence its coloured fringing.
    float misregistration_um;
    /// Print stock used when the caller does not choose one. Ignored for
    /// reversal stocks.
    std::string default_print;
    /// Gauge this stock was sold on. Used when the host does not specify one.
    /// Every spatial quantity here is physical (um, cycles/mm), so this is the
    /// number that converts emulsion physics into pixels.
    std::string default_format;
    /// True if this stock uses an additive colour filter grid, in which case
    /// `reseau` is meaningful and the layered colour path does not apply.
    bool has_reseau;
    ReseauSpec reseau;
    /// Veiling flare fraction of the *lens* normally used with this stock, not a
    /// property of the emulsion. Uncoated pre-1940 glass scattered 6-14% of
    /// incoming light into a broad haze across the frame; anti-reflection
    /// coating cut that below 1%. Stored here because era of stock and era of
    /// glass go together in practice. It lifts the black floor and compresses
    /// contrast globally, and nothing in the emulsion model substitutes for it:
    /// without it a 1930s stock still renders with modern blacks.
    /// Monochrome image tone: >0 warm/brown-black, <0 cool/blue-black.
    /// Applied after the printer-light solve, weighted toward the light tones.
    float silver_tone;
    float default_flare;
    Feature features;  ///< DERIVED, non-authoritative -- see enum note
    // -- schema v2 (2026-07 domain review) ------------------------------------
    TemporalSpec    temporal;     ///< gate weave / flicker / dirt (tier 3)
    ReciprocitySpec reciprocity;  ///< Schwarzschild failure (tier 2/3)
    AgingSpec       aging;        ///< storage damage hooks; all zeros = fresh
    Provenance      provenance;   ///< sources and confidence tier
    /// Static reversal exposure trim in x = -log10(E) - trim. 0.0 for every
    /// stock: the reference renderer solves per-channel trims per render.
    float trim;
    /// Densitometry of the curve/grain numbers: "status_m" (colour negative),
    /// "status_a" (colour reversal), "visual_iso" (B&W silver).
    std::string density_metric;
    /// "scan" when calibrated against the SCAN_DI transform, "print" when the
    /// default_print is a real print stock (Technicolor).
    std::string referred;
    /// Curve-abscissa position of metered mid-grey. 0.0 = mid grey at
    /// logE = 0, the convention the reference renderer bakes in.
    float speed_point_x;
    /// How exposure_index was assigned: "iso6" (B&W), "iso5800" (colour
    /// negative), "iso2240" (colour reversal), "manufacturer_ei" (historic).
    std::string speed_criterion;
    /// Orange-mask encoding: "dmin_ladder" (per-channel dmin IS the mask,
    /// r << g << b), "neutral_dmin" (mask in base_tint/dye data), "none"
    /// (B&W and reversal). Documents the audit split; render output unchanged.
    std::string mask_encoding;
    /// Callier coefficient (specular/diffuse density seen by a condenser):
    /// 1.0 dye images, ~1.3 B&W silver negative, ~1.25 B&W reversal.
    float callier_q;

    bool isReversal() const { return kind == StockKind::Reversal; }
};

/// Positive stock, or a digital-intermediate print-emulating transform.
/// System gamma is negative gamma times print gamma: ~0.6 * 1.75 for a scan
/// look, ~0.6 * 2.7 for a theatrical release print.
struct PrintStock {
    std::string name;
    std::string description;
    RGBCurves curves;
    float mtf_f50;         ///< cycles/mm, print plus scanner optics combined
    float grain_rms;       ///< print stock adds its own finer grain
    float grain_clump_um;  ///< micrometres
    Matrix3 dye_matrix;    ///< print dye impurity / gamut
    // -- schema v2 (DM-15): additive printer-light calibration ---------------
    float printer_light_r;   ///< lamp points; 25.0 = LAD-neutral mid-scale
    float printer_light_g;
    float printer_light_b;
    float log_e_per_point;   ///< logE per printer point (0.025 = 1/12 stop)
    std::string density_metric;  ///< print stocks are read in Status A
};

/// Film gauge geometry (schema v2, DM-17). width_mm is the v1 field; grain,
/// halation, MTF and registration scale from it plus the render width in px.
struct FilmFormat {
    std::string name;
    float width_mm;            ///< image width on the negative, millimetres
    float height_mm;           ///< image height, millimetres
    float anamorphic_squeeze;  ///< horizontal squeeze factor; 1.0 = spherical
    float perf_pitch_mm;       ///< perforation pitch; 0 = not perforated
};

/// @return All supported film stocks.
std::vector<FilmProfile> GetFilmDatabase();

/// @return All supported print stocks / print transforms.
std::vector<PrintStock> GetPrintStocks();

/// @return All supported film gauges.
std::vector<FilmFormat> GetFilmFormats();

}  // namespace film
