// ---------------------------------------------------------------------------
//  Copyright (c) 2026 Marat Shchuchinsky. All rights reserved.
//
//  PROPRIETARY. The schema, the derived values, the provenance records and the
//  documentation in this database are the intellectual property of Marat
//  Shchuchinsky, and represent substantial investment in obtaining, verifying
//  and presenting the contents.
//
//  No part of this database, nor any individual value, fragment, extract or
//  derivative work, may be copied, reproduced, distributed, published,
//  transmitted, modified, incorporated into another work or otherwise used, in
//  whole or in part, without the prior written permission of Marat
//  Shchuchinsky. Unauthorised use, reproduction, distribution or disclosure of
//  any portion is strictly prohibited.
//
//  Published manufacturer data cited in this file remains the property of the
//  respective rights holders; every such value carries its own source record.
// ---------------------------------------------------------------------------
// GENERATED by cpp_codegen.py on 2026-09-23  16:48:33Z -- DO NOT EDIT BY HAND.
// schema_version 51
//
// The film database's schema version, and nothing else.
//
// WHY THIS IS ITS OWN FILE. The request was for a C/C++-callable inline API
// returning the schema version, in the generated database headers. It cannot
// live in film_profiles.hpp and still be callable from C: that header is C++
// throughout -- <array>, <string>, <vector>, classes, namespaces -- so a C
// translation unit cannot include it at all, and an API a C compiler can
// never reach is not a C-compatible API. This header includes <stdint.h>
// only, compiles clean as C99 and as C++, and film_profiles.hpp includes it,
// so both languages get the same function reading the same literal.

#ifndef FILM_SCHEMA_VERSION_H
#define FILM_SCHEMA_VERSION_H

#include <stdint.h>

/* THE VERSION LITERAL APPEARS EXACTLY ONCE IN THE PROJECT'S C++ SIDE, and it
 * is this enumerator. The C++ constant below and both accessors read it, so a
 * version can never be half bumped. An unscoped enumerator rather than a
 * macro because a macro has no type and no scope and a debugger cannot see
 * it; and rather than a constexpr because this line must also be legal C. */
enum { kFilmDatabaseSchemaVersionValue = 51 };

/* The C entry point, and the one a C++ caller wanting extern "C" linkage or a
 * plain function pointer should use. `static inline` gives a checked return
 * type where a macro would give none. */
static inline int32_t FilmDatabaseSchemaVersion(void)
{
    return (int32_t)kFilmDatabaseSchemaVersionValue;
}

#ifdef __cplusplus

namespace film {

/// Data-model schema version, mirrored from film_profiles.SCHEMA_VERSION.
constexpr std::int32_t kSchemaVersion =
    static_cast<std::int32_t>(kFilmDatabaseSchemaVersionValue);

/// @return The schema version of the database compiled into this header.
///
/// Header-only by design: a caller that linked an older database object file
/// against a newer header would otherwise get the header's idea of the
/// version and the object file's idea of the layout, which is the single
/// mismatch a version check exists to catch. Being constexpr it also answers
/// at COMPILE time, so a consumer can refuse to build against a database too
/// old for it instead of finding out at run time:
///
///     static_assert(film::GetFilmDatabaseSchemaVersion() >= 44,
///                   "this code needs the v44 antihalation carriers");
constexpr std::int32_t GetFilmDatabaseSchemaVersion() noexcept
{
    return kSchemaVersion;
}

}  // namespace film

#endif  /* __cplusplus */

#endif  /* FILM_SCHEMA_VERSION_H */
