// ---------------------------------------------------------------------------
//  Copyright (c) 2026 Marat Shchuchinsky. All rights reserved.
//
//  PROPRIETARY. The schema, the derived values, the provenance records and the
//  documentation in this database are the intellectual property of Marat
//  Shchuchinsky, and represent substantial investment in obtaining, verifying
//  and presenting the contents.
//
//  No part of this database, nor any individual value, fragment, extract or
//  derivative work, may be copied, reproduced, distributed, published,
//  transmitted, modified, incorporated into another work or otherwise used, in
//  whole or in part, without the prior written permission of Marat
//  Shchuchinsky. Unauthorised use, reproduction, distribution or disclosure of
//  any portion is strictly prohibited.
//
//  Published manufacturer data cited in this file remains the property of the
//  respective rights holders; every such value carries its own source record.
// ---------------------------------------------------------------------------
// Generated by cpp_codegen.py on 2026-10-08  04:47:02Z -- DO NOT EDIT BY HAND.
// film_profiles schema version 61; 225 profiles.
//
// Film profile indices. Values are positions in the std::vector returned by
// film::GetFilmDatabase(), so a value here may be used directly as that
// vector's subscript, and it matches line (value + 1) of film_names.txt.
//
// Underlying type is fixed at int32_t so the values are stable across
// compilers and safe to serialise into project files and plugin parameters.
// Appending a stock renumbers nothing; INSERTING one renumbers everything
// after it, which would invalidate saved projects -- add at the end.
#pragma once

#include <cstdint>

namespace film {

enum class eFILM_PROFILE : int32_t
{
    eAGFA_APX_25                      = 0,
    eAGFA_APX_100                     = 1,
    eAGFA_APX_400                     = 2,
    eAGFA_AVIPHOT_PAN_20              = 3,
    eAGFA_AVIPHOT_PAN_400S            = 4,
    eAGFA_NEG_TYPE_3                  = 5,
    eAGFA_NEG_TYPE_B_1943             = 6,
    eAGFA_NEU_1936                    = 7,
    eAGFA_OPTIMA_100                  = 8,
    eAGFA_OPTIMA_200                  = 9,
    eAGFA_OPTIMA_400                  = 10,
    eAGFA_PORTRAIT_160                = 11,
    eAGFA_RSX_II_50                   = 12,
    eAGFA_RSX_II_100                  = 13,
    eAGFA_RSX_II_200                  = 14,
    eAGFA_SCALA_200X                  = 15,
    eAGFA_ULTRA_50                    = 16,
    eAGFA_VISTA_200                   = 17,
    eAGFA_VISTA_PLUS_200              = 18,
    eAGFA_VISTA_PLUS_400              = 19,
    eANSCOCOLOR_NEG_843               = 20,
    eCINESTILL_800T                   = 21,
    eDUFAYCOLOR_1937                  = 22,
    eEASTMAN_5247_1974                = 23,
    eEASTMAN_5247_1983                = 24,
    eEASTMAN_5250_1959                = 25,
    eEASTMAN_5254_1968                = 26,
    eEASTMAN_5293_250T_1982           = 27,
    eEASTMAN_5294_1983                = 28,
    eEASTMAN_DOUBLE_X_5222            = 29,
    eEASTMAN_EKTACHROME_5239          = 30,
    eEASTMAN_EKTACHROME_7239          = 31,
    eEASTMAN_EXR_50D_5245             = 32,
    eEASTMAN_EXR_100T_5248            = 33,
    eEASTMAN_EXR_200T_5293            = 34,
    eEASTMAN_EXR_500T_5296            = 35,
    eEASTMAN_ORTHO_1930               = 36,
    eEASTMAN_PLUS_X_5231              = 37,
    eEASTMAN_SUPER_XX_1938            = 38,
    eEASTMAN_TRI_X_5223               = 39,
    eEASTMANCOLOR_5248_1953           = 40,
    eEKTACHROME_64                    = 41,
    eEKTACHROME_160T                  = 42,
    eEKTACHROME_X                     = 43,
    eFERRANIA_ORTO_50                 = 44,
    eFERRANIA_P30                     = 45,
    eFERRANIA_P30_MK2                 = 46,
    eFERRANIA_P33_160                 = 47,
    eFERRANIACOLOR_NEG_82             = 48,
    eFERRANIACOLOR_REVERSAL_1950      = 49,
    eFOMAPAN_400_ACTION               = 50,
    eFUJI_ASTIA_100F                  = 51,
    eFUJI_ETERNA_VIVID_500T_8547      = 52,
    eFUJI_F125_8530                   = 53,
    eFUJI_NEOPAN_400                  = 54,
    eFUJI_NEOPAN_1600                 = 55,
    eFUJI_NEOPAN_ACROS_100            = 56,
    eFUJI_NEOPAN_SS                   = 57,
    eFUJI_PROVIA_100F                 = 58,
    eFUJI_PROVIA_400F                 = 59,
    eFUJI_PROVIA_400X                 = 60,
    eFUJI_SENSIA_100                  = 61,
    eFUJI_SENSIA_100_2005             = 62,
    eFUJI_SENSIA_200                  = 63,
    eFUJI_SENSIA_400                  = 64,
    eFUJI_SUPER_F125_8532             = 65,
    eFUJI_VELVIA_50                   = 66,
    eFUJI_VELVIA_100                  = 67,
    eFUJI_VELVIA_100F                 = 68,
    eFUJICHROME_64T_II                = 69,
    eFUJICOLOR_A250                   = 70,
    eFUJICOLOR_NEXIA_400              = 71,
    eFUJICOLOR_NEXIA_800              = 72,
    eFUJICOLOR_NEXIA_A200             = 73,
    eFUJICOLOR_NPL_160                = 74,
    eFUJICOLOR_PORTRAIT_NPZ_800       = 75,
    eFUJICOLOR_PRO_160C               = 76,
    eFUJICOLOR_PRO_160S               = 77,
    eFUJICOLOR_PRO_400H               = 78,
    eFUJICOLOR_PRO_800Z               = 79,
    eFUJICOLOR_SUPER_F500_8572        = 80,
    eFUJICOLOR_SUPERIA_100            = 81,
    eFUJICOLOR_SUPERIA_200            = 82,
    eFUJICOLOR_SUPERIA_1600           = 83,
    eFUJICOLOR_SUPERIA_REALA          = 84,
    eFUJICOLOR_SUPERIA_XTRA_400       = 85,
    eFUJICOLOR_SUPERIA_XTRA_800       = 86,
    eFUJICOLOR_TRUE_DEFINITION_400    = 87,
    eGENERIC_BW                       = 88,
    eGENERIC_COLOR                    = 89,
    eGEVACHROME_600                   = 90,
    eGEVACHROME_605                   = 91,
    eGEVACHROME_902                   = 92,
    eGEVACOLOR_1952                   = 93,
    eGEVACOLOR_NEG_652                = 94,
    eGEVACOLOR_NEG_682                = 95,
    eGEVAERT_PANCHRO_1950             = 96,
    eILFORD_DELTA_3200                = 97,
    eILFORD_FP4                       = 98,
    eILFORD_HP3                       = 99,
    eILFORD_HP4                       = 100,
    eILFORD_HP5_PLUS_400              = 101,
    eILFORD_HPS                       = 102,
    eILFORD_PAN_F                     = 103,
    eILFORD_XP1_400                   = 104,
    eKENTMERE_PAN_100                 = 105,
    eKENTMERE_PAN_400                 = 106,
    eKODACHROME_64                    = 107,
    eKODACHROME_1938                  = 108,
    eKODACHROME_TYPE_A_1938           = 109,
    eKODAK_8374                       = 110,
    eKODAK_BW400CN                    = 111,
    eKODAK_COMMERCIAL_1956            = 112,
    eKODAK_EKTACHROME_100_EPN         = 113,
    eKODAK_EKTACHROME_100D_5285       = 114,
    eKODAK_EKTAPAN_100                = 115,
    eKODAK_EKTAPRESS_PJ100            = 116,
    eKODAK_EKTAPRESS_PJ400            = 117,
    eKODAK_EKTAPRESS_PJ800            = 118,
    eKODAK_EKTAR_100                  = 119,
    eKODAK_EKTAR_125                  = 120,
    eKODAK_GOLD_100                   = 121,
    eKODAK_GOLD_200                   = 122,
    eKODAK_HIE                        = 123,
    eKODAK_ORTHO_X_SHEET_1952         = 124,
    eKODAK_PANATOMIC_X                = 125,
    eKODAK_PANATOMIC_X_SHEET_1952     = 126,
    eKODAK_PLUS_X_125                 = 127,
    eKODAK_PORTRA_100T                = 128,
    eKODAK_PORTRA_160                 = 129,
    eKODAK_PORTRA_160NC               = 130,
    eKODAK_PORTRA_160VC               = 131,
    eKODAK_PORTRA_400                 = 132,
    eKODAK_PORTRA_400NC               = 133,
    eKODAK_PORTRA_400VC               = 134,
    eKODAK_PORTRA_800                 = 135,
    eKODAK_PORTRAIT_PANCHROMATIC_1956 = 136,
    eKODAK_PRO_100T_PRT               = 137,
    eKODAK_PROFOTO_100                = 138,
    eKODAK_RECORDING_2475             = 139,
    eKODAK_ROYAL_ORTHO_1956           = 140,
    eKODAK_ROYAL_PAN_4141             = 141,
    eKODAK_ROYAL_X_PAN_4166           = 142,
    eKODAK_SUPER_PANCHRO_PRESS_B_1956 = 143,
    eKODAK_SUPER_SPEED_ORTHO_1956     = 144,
    eKODAK_SUPER_XX_PAN_4142          = 145,
    eKODAK_T400CN                     = 146,
    eKODAK_TECHNICAL_PAN              = 147,
    eKODAK_TMAX_100                   = 148,
    eKODAK_TMAX_400                   = 149,
    eKODAK_TMAX_P3200                 = 150,
    eKODAK_TRI_X_320TXP               = 151,
    eKODAK_TRI_X_400TX                = 152,
    eKODAK_TRI_X_REVERSAL_200         = 153,
    eKODAK_TRI_X_SHEET_1952           = 154,
    eKODAK_ULTRA_COLOR_100UC          = 155,
    eKODAK_ULTRA_COLOR_400UC          = 156,
    eKODAK_ULTRAMAX_400               = 157,
    eKODAK_ULTRAMAX_800               = 158,
    eKODAK_VERICHROME_1952            = 159,
    eKODAK_VERICHROME_PAN             = 160,
    eKODAK_VERICOLOR_III_160          = 161,
    eKODAK_VISION2_50D_5201           = 162,
    eKODAK_VISION2_200T_5217          = 163,
    eKODAK_VISION2_250D_5205          = 164,
    eKODAK_VISION2_500T_5218          = 165,
    eKODAK_VISION3_50D_5203           = 166,
    eKODAK_VISION3_200T_5213          = 167,
    eKODAK_VISION3_250D_5207          = 168,
    eKODAK_VISION3_500T_5219          = 169,
    eKODAK_VISION3_500T_5219_AHU      = 170,
    eKODAK_VISION_200T_5274           = 171,
    eKODAK_VISION_250D_5246           = 172,
    eKODAK_VISION_500T_5279           = 173,
    eKONICA_CENTURIA_SUPER_400        = 174,
    eKONICA_CENTURIA_SUPER_1600       = 175,
    eKONICA_CHROME_CENTURIA_100       = 176,
    eKONICA_CHROME_R100               = 177,
    eKONICA_IMPRESA_50                = 178,
    eKONICA_INFRARED_750              = 179,
    eKONICA_VX_100                    = 180,
    eLUMIERE_LUMICHROME               = 181,
    eORWO_CHROM_UT18                  = 182,
    eORWOCOLOR_NC3                    = 183,
    eORWOCOLOR_NC19                   = 184,
    eORWOCOLOR_NC21                   = 185,
    ePOLAROID_42                      = 186,
    ePOLAROID_46L                     = 187,
    ePOLAROID_47                      = 188,
    ePOLAROID_51                      = 189,
    ePOLAROID_52                      = 190,
    ePOLAROID_55_PN_NEG               = 191,
    ePOLAROID_146L                    = 192,
    ePOLAROID_410                     = 193,
    ePOLAROID_664                     = 194,
    ePOLAROID_667                     = 195,
    ePOLAROID_SX70                    = 196,
    eROLLEI_INFRARED_400              = 197,
    eROLLEI_PAN_25                    = 198,
    eROLLEI_R3                        = 199,
    eROLLEI_RETRO_400                 = 200,
    eROLLEI_SUPERPAN_200              = 201,
    eSOVIET_PANCHROM_1939             = 202,
    eSUPER_ANSCOCHROME_1957           = 203,
    eSVEMA_CND_32                     = 204,
    eSVEMA_CND_64                     = 205,
    eSVEMA_CNL_32                     = 206,
    eSVEMA_CNL_65                     = 207,
    eSVEMA_CO_32D                     = 208,
    eSVEMA_CO_90L                     = 209,
    eSVEMA_CO_T_90LM                  = 210,
    eSVEMA_DS_2                       = 211,
    eSVEMA_DS_4                       = 212,
    eSVEMA_DS_5M                      = 213,
    eSVEMA_FOTO_32                    = 214,
    eSVEMA_FOTO_65                    = 215,
    eSVEMA_FOTO_130                   = 216,
    eSVEMA_FOTO_250                   = 217,
    eSVEMA_LN_3                       = 218,
    eSVEMA_LN_8                       = 219,
    eSVEMA_LN_9                       = 220,
    eSVEMA_LN_9S                      = 221,
    eTASMA_FN_64                      = 222,
    eTASMA_OCH_45                     = 223,
    eTECHNICOLOR_THREE_STRIP          = 224,
    eTOTAL_FILMS_PROFILES = 225
};

// ---------------------------------------------------------------------------
// Batch Position (AlgoControls::batchPosition) -- control range.
//
// COPIED AT GENERATION TIME FROM AlgoControlEnums.hpp (BatchPositionMin / Max /
// Def / Step), which is the single authority for every control range; they are
// repeated here so that code holding only the database headers -- a host that
// greys controls from film_params_mask.hpp -- can size the slider without
// pulling in the engine's control header. AlgoControl.cpp static_asserts that
// the two sets agree, so a hand edit to either fails the compile.
//
// The unit is a FRACTION of the distance from the stored value to the edge of
// the stock's own published acceptance band: -1 the lower edge, 0 as stored,
// +1 the upper edge. The control acts only on stocks that carry such a band --
// bit eCTRL_BIT_BATCH_POSITION of kFilmControlAvailability, 10 of 225
// stocks in this database -- and must be hidden or disabled on the rest.
// ---------------------------------------------------------------------------
constexpr double eBATCH_POSITION_MIN  = -1.0;
constexpr double eBATCH_POSITION_MAX  = 1.0;
constexpr double eBATCH_POSITION_DEF  = 0.0;
constexpr double eBATCH_POSITION_STEP = 0.05;

}  // namespace film
