// Generated by cpp_codegen.py on 2026-08-04  06:43:57Z -- DO NOT EDIT BY HAND.
// film_profiles schema version 5; 93 profiles.
//
// Film profile indices. Values are positions in the std::vector returned by
// film::GetFilmDatabase(), so a value here may be used directly as that
// vector's subscript, and it matches line (value + 1) of film_names.txt.
//
// Underlying type is fixed at int32_t so the values are stable across
// compilers and safe to serialise into project files and plugin parameters.
// Appending a stock renumbers nothing; INSERTING one renumbers everything
// after it, which would invalidate saved projects -- add at the end.
#pragma once

#include <cstdint>

namespace film {

enum class eFILM_PROFILE : int32_t
{
    eAGFACOLOR_NEG_TYPE_B_1943   = 0,
    eAGFACOLOR_NEU_1936          = 1,
    eAGFA_APX_100                = 2,
    eAGFA_APX_25                 = 3,
    eAGFA_APX_400                = 4,
    eAGFA_OPTIMA_100             = 5,
    eAGFA_VISTA_200              = 6,
    eCINESTILL_800T              = 7,
    eDUFAYCOLOR_1937             = 8,
    eEASTMAN_5247_1974           = 9,
    eEASTMAN_5250_1959           = 10,
    eEASTMAN_5254_1968           = 11,
    eEASTMAN_5294_1983           = 12,
    eEASTMAN_DOUBLE_X_5222       = 13,
    eEASTMAN_EKTACHROME_5239     = 14,
    eEASTMAN_EKTACHROME_7239     = 15,
    eEASTMAN_EXR_100T_5248       = 16,
    eEASTMAN_EXR_200T_5293       = 17,
    eEASTMAN_EXR_500T_5296       = 18,
    eEASTMAN_EXR_50D_5245        = 19,
    eEASTMAN_ORTHO_1930          = 20,
    eEASTMAN_PLUS_X_5231         = 21,
    eEASTMAN_SUPER_XX_1938       = 22,
    eEIGHT_MM_BW                 = 23,
    eEIGHT_MM_COLOR              = 24,
    eEKTACHROME_160T             = 25,
    eEKTACHROME_64               = 26,
    eFERRANIA_P30                = 27,
    eFOMAPAN_400_ACTION          = 28,
    eFUJICOLOR_A250              = 29,
    eFUJICOLOR_SUPER_F500_8572   = 30,
    eFUJI_ETERNA_VIVID_500T_8547 = 31,
    eFUJI_F125_8530              = 32,
    eFUJI_F125_8630              = 33,
    eFUJI_NEOPAN_1600            = 34,
    eFUJI_NEOPAN_ACROS_100       = 35,
    eFUJI_PROVIA_400X            = 36,
    eFUJI_SENSIA_100             = 37,
    eFUJI_VELVIA_50              = 38,
    eGEVACHROME_902              = 39,
    eGEVACOLOR_1952              = 40,
    eGEVACOLOR_NEG_682           = 41,
    eGEVAERT_PANCHRO_1950        = 42,
    eILFORD_DELTA_3200           = 43,
    eILFORD_HP3                  = 44,
    eILFORD_HP5_PLUS_400         = 45,
    eILFORD_HPS                  = 46,
    eKENTMERE_PAN_100            = 47,
    eKENTMERE_PAN_400            = 48,
    eKODACHROME_64               = 49,
    eKODAK_EKTACHROME_100D_5285  = 50,
    eKODAK_PORTRA_400            = 51,
    eKODAK_TRI_X_REVERSAL_200    = 52,
    eKODAK_VISION2_200T_5217     = 53,
    eKODAK_VISION2_250D_5205     = 54,
    eKODAK_VISION2_500T_5218     = 55,
    eKODAK_VISION3_200T_5213     = 56,
    eKODAK_VISION3_250D_5207     = 57,
    eKODAK_VISION3_500T_5219     = 58,
    eKODAK_VISION3_50D_5203      = 59,
    eKODAK_VISION_200T_5274      = 60,
    eKODAK_VISION_250D_5246      = 61,
    eKODAK_VISION_500T_5279      = 62,
    eKONICA_CENTURIA_SUPER_1600  = 63,
    eKONICA_CENTURIA_SUPER_400   = 64,
    eKONICA_CHROME_CENTURIA_100  = 65,
    eKONICA_CHROME_R100          = 66,
    eKONICA_IMPRESA_50           = 67,
    eKONICA_INFRARED_750         = 68,
    eKONICA_VX_100               = 69,
    eLUMIERE_LUMICHROME          = 70,
    eORWOCOLOR_NC21              = 71,
    eORWOCOLOR_NC24              = 72,
    eORWO_CHROM_UT18             = 73,
    ePOLAROID_664                = 74,
    ePOLAROID_667                = 75,
    ePOLAROID_SX70               = 76,
    eROLLEI_INFRARED_400         = 77,
    eROLLEI_R3                   = 78,
    eROLLEI_RETRO_400            = 79,
    eSOVIET_PANCHROM_1939        = 80,
    eSVEMA_DS_4                  = 81,
    eSVEMA_FN_64                 = 82,
    eSVEMA_FN_64_16MM            = 83,
    eSVEMA_FN_64_8MM             = 84,
    eSVEMA_FOTO_130              = 85,
    eSVEMA_FOTO_250              = 86,
    eSVEMA_FOTO_32               = 87,
    eSVEMA_TSNL_32               = 88,
    eSVEMA_TSNL_65               = 89,
    eTASMA_FN_64                 = 90,
    eTASMA_OCH_45                = 91,
    eTECHNICOLOR_THREE_STRIP     = 92,
    eTOTAL_FILMS_PROFILES = 93
};

}  // namespace film
