// ---------------------------------------------------------------------------
//  Copyright (c) 2026 Marat Shchuchinsky. All rights reserved.
//
//  PROPRIETARY. The schema, the derived values, the provenance records and the
//  documentation in this database are the intellectual property of Marat
//  Shchuchinsky, and represent substantial investment in obtaining, verifying
//  and presenting the contents.
//
//  No part of this database, nor any individual value, fragment, extract or
//  derivative work, may be copied, reproduced, distributed, published,
//  transmitted, modified, incorporated into another work or otherwise used, in
//  whole or in part, without the prior written permission of Marat
//  Shchuchinsky. Unauthorised use, reproduction, distribution or disclosure of
//  any portion is strictly prohibited.
//
//  Published manufacturer data cited in this file remains the property of the
//  respective rights holders; every such value carries its own source record.
// ---------------------------------------------------------------------------
// Generated by cpp_codegen.py on 2026-10-02  08:28:55Z -- DO NOT EDIT BY HAND.
// film_profiles schema version 61; 222 profiles.
//
// Film profile indices. Values are positions in the std::vector returned by
// film::GetFilmDatabase(), so a value here may be used directly as that
// vector's subscript, and it matches line (value + 1) of film_names.txt.
//
// Underlying type is fixed at int32_t so the values are stable across
// compilers and safe to serialise into project files and plugin parameters.
// Appending a stock renumbers nothing; INSERTING one renumbers everything
// after it, which would invalidate saved projects -- add at the end.
#pragma once

#include <cstdint>

namespace film {

enum class eFILM_PROFILE : int32_t
{
    eAGFA_APX_25                      = 0,
    eAGFA_APX_100                     = 1,
    eAGFA_APX_400                     = 2,
    eAGFA_AVIPHOT_PAN_20              = 3,
    eAGFA_NEG_TYPE_3                  = 4,
    eAGFA_NEG_TYPE_B_1943             = 5,
    eAGFA_NEU_1936                    = 6,
    eAGFA_OPTIMA_100                  = 7,
    eAGFA_OPTIMA_200                  = 8,
    eAGFA_OPTIMA_400                  = 9,
    eAGFA_PORTRAIT_160                = 10,
    eAGFA_RSX_II_50                   = 11,
    eAGFA_RSX_II_100                  = 12,
    eAGFA_RSX_II_200                  = 13,
    eAGFA_SCALA_200X                  = 14,
    eAGFA_ULTRA_50                    = 15,
    eAGFA_VISTA_200                   = 16,
    eAGFA_VISTA_PLUS_200              = 17,
    eAGFA_VISTA_PLUS_400              = 18,
    eANSCOCOLOR_NEG_843               = 19,
    eCINESTILL_800T                   = 20,
    eDUFAYCOLOR_1937                  = 21,
    eEASTMAN_5247_1974                = 22,
    eEASTMAN_5247_1983                = 23,
    eEASTMAN_5250_1959                = 24,
    eEASTMAN_5254_1968                = 25,
    eEASTMAN_5293_250T_1982           = 26,
    eEASTMAN_5294_1983                = 27,
    eEASTMAN_DOUBLE_X_5222            = 28,
    eEASTMAN_EKTACHROME_5239          = 29,
    eEASTMAN_EKTACHROME_7239          = 30,
    eEASTMAN_EXR_50D_5245             = 31,
    eEASTMAN_EXR_100T_5248            = 32,
    eEASTMAN_EXR_200T_5293            = 33,
    eEASTMAN_EXR_500T_5296            = 34,
    eEASTMAN_ORTHO_1930               = 35,
    eEASTMAN_PLUS_X_5231              = 36,
    eEASTMAN_SUPER_XX_1938            = 37,
    eEASTMAN_TRI_X_5223               = 38,
    eEASTMANCOLOR_5248_1953           = 39,
    eEKTACHROME_64                    = 40,
    eEKTACHROME_160T                  = 41,
    eEKTACHROME_X                     = 42,
    eFERRANIA_ORTO_50                 = 43,
    eFERRANIA_P30                     = 44,
    eFERRANIA_P30_MK2                 = 45,
    eFERRANIA_P33_160                 = 46,
    eFERRANIACOLOR_NEG_82             = 47,
    eFERRANIACOLOR_REVERSAL_1950      = 48,
    eFOMAPAN_400_ACTION               = 49,
    eFUJI_ASTIA_100F                  = 50,
    eFUJI_ETERNA_VIVID_500T_8547      = 51,
    eFUJI_F125_8530                   = 52,
    eFUJI_NEOPAN_400                  = 53,
    eFUJI_NEOPAN_1600                 = 54,
    eFUJI_NEOPAN_ACROS_100            = 55,
    eFUJI_NEOPAN_SS                   = 56,
    eFUJI_PROVIA_100F                 = 57,
    eFUJI_PROVIA_400F                 = 58,
    eFUJI_PROVIA_400X                 = 59,
    eFUJI_SENSIA_100                  = 60,
    eFUJI_SENSIA_100_2005             = 61,
    eFUJI_SENSIA_200                  = 62,
    eFUJI_SENSIA_400                  = 63,
    eFUJI_SUPER_F125_8532             = 64,
    eFUJI_VELVIA_50                   = 65,
    eFUJI_VELVIA_100                  = 66,
    eFUJI_VELVIA_100F                 = 67,
    eFUJICHROME_64T_II                = 68,
    eFUJICOLOR_A250                   = 69,
    eFUJICOLOR_NEXIA_400              = 70,
    eFUJICOLOR_NEXIA_800              = 71,
    eFUJICOLOR_NEXIA_A200             = 72,
    eFUJICOLOR_NPL_160                = 73,
    eFUJICOLOR_PORTRAIT_NPZ_800       = 74,
    eFUJICOLOR_PRO_160C               = 75,
    eFUJICOLOR_PRO_160S               = 76,
    eFUJICOLOR_PRO_400H               = 77,
    eFUJICOLOR_PRO_800Z               = 78,
    eFUJICOLOR_SUPER_F500_8572        = 79,
    eFUJICOLOR_SUPERIA_100            = 80,
    eFUJICOLOR_SUPERIA_200            = 81,
    eFUJICOLOR_SUPERIA_1600           = 82,
    eFUJICOLOR_SUPERIA_REALA          = 83,
    eFUJICOLOR_SUPERIA_XTRA_400       = 84,
    eFUJICOLOR_SUPERIA_XTRA_800       = 85,
    eFUJICOLOR_TRUE_DEFINITION_400    = 86,
    eGENERIC_BW                       = 87,
    eGENERIC_COLOR                    = 88,
    eGEVACHROME_600                   = 89,
    eGEVACHROME_605                   = 90,
    eGEVACHROME_902                   = 91,
    eGEVACOLOR_1952                   = 92,
    eGEVACOLOR_NEG_652                = 93,
    eGEVACOLOR_NEG_682                = 94,
    eGEVAERT_PANCHRO_1950             = 95,
    eILFORD_DELTA_3200                = 96,
    eILFORD_FP4                       = 97,
    eILFORD_HP3                       = 98,
    eILFORD_HP4                       = 99,
    eILFORD_HP5_PLUS_400              = 100,
    eILFORD_HPS                       = 101,
    eILFORD_PAN_F                     = 102,
    eILFORD_XP1_400                   = 103,
    eKENTMERE_PAN_100                 = 104,
    eKENTMERE_PAN_400                 = 105,
    eKODACHROME_64                    = 106,
    eKODACHROME_1938                  = 107,
    eKODACHROME_TYPE_A_1938           = 108,
    eKODAK_8374                       = 109,
    eKODAK_BW400CN                    = 110,
    eKODAK_COMMERCIAL_1956            = 111,
    eKODAK_EKTACHROME_100_EPN         = 112,
    eKODAK_EKTACHROME_100D_5285       = 113,
    eKODAK_EKTAPAN_100                = 114,
    eKODAK_EKTAPRESS_PJ100            = 115,
    eKODAK_EKTAPRESS_PJ400            = 116,
    eKODAK_EKTAPRESS_PJ800            = 117,
    eKODAK_EKTAR_100                  = 118,
    eKODAK_EKTAR_125                  = 119,
    eKODAK_GOLD_100                   = 120,
    eKODAK_GOLD_200                   = 121,
    eKODAK_HIE                        = 122,
    eKODAK_ORTHO_X_SHEET_1952         = 123,
    eKODAK_PANATOMIC_X                = 124,
    eKODAK_PANATOMIC_X_SHEET_1952     = 125,
    eKODAK_PLUS_X_125                 = 126,
    eKODAK_PORTRA_100T                = 127,
    eKODAK_PORTRA_160                 = 128,
    eKODAK_PORTRA_160NC               = 129,
    eKODAK_PORTRA_160VC               = 130,
    eKODAK_PORTRA_400                 = 131,
    eKODAK_PORTRA_400NC               = 132,
    eKODAK_PORTRA_400VC               = 133,
    eKODAK_PORTRA_800                 = 134,
    eKODAK_PORTRAIT_PANCHROMATIC_1956 = 135,
    eKODAK_PRO_100T_PRT               = 136,
    eKODAK_PROFOTO_100                = 137,
    eKODAK_RECORDING_2475             = 138,
    eKODAK_ROYAL_ORTHO_1956           = 139,
    eKODAK_ROYAL_PAN_4141             = 140,
    eKODAK_ROYAL_X_PAN_4166           = 141,
    eKODAK_SUPER_PANCHRO_PRESS_B_1956 = 142,
    eKODAK_SUPER_SPEED_ORTHO_1956     = 143,
    eKODAK_SUPER_XX_PAN_4142          = 144,
    eKODAK_T400CN                     = 145,
    eKODAK_TECHNICAL_PAN              = 146,
    eKODAK_TMAX_100                   = 147,
    eKODAK_TMAX_400                   = 148,
    eKODAK_TMAX_P3200                 = 149,
    eKODAK_TRI_X_320TXP               = 150,
    eKODAK_TRI_X_400TX                = 151,
    eKODAK_TRI_X_REVERSAL_200         = 152,
    eKODAK_TRI_X_SHEET_1952           = 153,
    eKODAK_ULTRA_COLOR_100UC          = 154,
    eKODAK_ULTRA_COLOR_400UC          = 155,
    eKODAK_ULTRAMAX_400               = 156,
    eKODAK_ULTRAMAX_800               = 157,
    eKODAK_VERICHROME_1952            = 158,
    eKODAK_VERICHROME_PAN             = 159,
    eKODAK_VERICOLOR_III_160          = 160,
    eKODAK_VISION2_50D_5201           = 161,
    eKODAK_VISION2_200T_5217          = 162,
    eKODAK_VISION2_250D_5205          = 163,
    eKODAK_VISION2_500T_5218          = 164,
    eKODAK_VISION3_50D_5203           = 165,
    eKODAK_VISION3_200T_5213          = 166,
    eKODAK_VISION3_250D_5207          = 167,
    eKODAK_VISION3_500T_5219          = 168,
    eKODAK_VISION3_500T_5219_AHU      = 169,
    eKODAK_VISION_200T_5274           = 170,
    eKODAK_VISION_250D_5246           = 171,
    eKODAK_VISION_500T_5279           = 172,
    eKONICA_CENTURIA_SUPER_400        = 173,
    eKONICA_CENTURIA_SUPER_1600       = 174,
    eKONICA_CHROME_CENTURIA_100       = 175,
    eKONICA_CHROME_R100               = 176,
    eKONICA_IMPRESA_50                = 177,
    eKONICA_INFRARED_750              = 178,
    eKONICA_VX_100                    = 179,
    eLUMIERE_LUMICHROME               = 180,
    eORWO_CHROM_UT18                  = 181,
    eORWOCOLOR_NC3                    = 182,
    eORWOCOLOR_NC19                   = 183,
    eORWOCOLOR_NC21                   = 184,
    ePOLAROID_42                      = 185,
    ePOLAROID_46L                     = 186,
    ePOLAROID_47                      = 187,
    ePOLAROID_51                      = 188,
    ePOLAROID_52                      = 189,
    ePOLAROID_55_PN_NEG               = 190,
    ePOLAROID_146L                    = 191,
    ePOLAROID_410                     = 192,
    ePOLAROID_664                     = 193,
    ePOLAROID_667                     = 194,
    ePOLAROID_SX70                    = 195,
    eROLLEI_INFRARED_400              = 196,
    eROLLEI_R3                        = 197,
    eROLLEI_RETRO_400                 = 198,
    eSOVIET_PANCHROM_1939             = 199,
    eSUPER_ANSCOCHROME_1957           = 200,
    eSVEMA_CND_32                     = 201,
    eSVEMA_CND_64                     = 202,
    eSVEMA_CNL_32                     = 203,
    eSVEMA_CNL_65                     = 204,
    eSVEMA_CO_32D                     = 205,
    eSVEMA_CO_90L                     = 206,
    eSVEMA_CO_T_90LM                  = 207,
    eSVEMA_DS_2                       = 208,
    eSVEMA_DS_4                       = 209,
    eSVEMA_DS_5M                      = 210,
    eSVEMA_FOTO_32                    = 211,
    eSVEMA_FOTO_65                    = 212,
    eSVEMA_FOTO_130                   = 213,
    eSVEMA_FOTO_250                   = 214,
    eSVEMA_LN_3                       = 215,
    eSVEMA_LN_8                       = 216,
    eSVEMA_LN_9                       = 217,
    eSVEMA_LN_9S                      = 218,
    eTASMA_FN_64                      = 219,
    eTASMA_OCH_45                     = 220,
    eTECHNICOLOR_THREE_STRIP          = 221,
    eTOTAL_FILMS_PROFILES = 222
};

// ---------------------------------------------------------------------------
// Batch Position (AlgoControls::batchPosition) -- control range.
//
// COPIED AT GENERATION TIME FROM AlgoControlEnums.hpp (BatchPositionMin / Max /
// Def / Step), which is the single authority for every control range; they are
// repeated here so that code holding only the database headers -- a host that
// greys controls from film_params_mask.hpp -- can size the slider without
// pulling in the engine's control header. AlgoControl.cpp static_asserts that
// the two sets agree, so a hand edit to either fails the compile.
//
// The unit is a FRACTION of the distance from the stored value to the edge of
// the stock's own published acceptance band: -1 the lower edge, 0 as stored,
// +1 the upper edge. The control acts only on stocks that carry such a band --
// bit eCTRL_BIT_BATCH_POSITION of kFilmControlAvailability, 10 of 222
// stocks in this database -- and must be hidden or disabled on the rest.
// ---------------------------------------------------------------------------
constexpr double eBATCH_POSITION_MIN  = -1.0;
constexpr double eBATCH_POSITION_MAX  = 1.0;
constexpr double eBATCH_POSITION_DEF  = 0.0;
constexpr double eBATCH_POSITION_STEP = 0.05;

}  // namespace film
