// Generated by cpp_codegen.py -- do not edit by hand.
// generated: 2026-08-31  13:30:02Z
// schema_version 22
//
// INTERNAL header for the split film-profile table. The table is emitted as
// 16 translation units (film_profiles_data_01.cpp ..) because a single
// 676 KB braced-init-list function was beyond what VS2015 SP3 / ICC compile
// reliably -- their limits are per-function. Each slot appends a consecutive
// slice of the table; LoadFilmDataBase() calls them in numeric order, so
// vector index == eFILM_PROFILE value == film_names.txt line, unchanged.
//
// Nothing outside LoadFilmDataBase.cpp should include this header.
#pragma once
#include "film_profiles.hpp"

namespace film {
namespace detail {

void AppendProfiles_01(std::vector<FilmProfile>& v);
void AppendProfiles_02(std::vector<FilmProfile>& v);
void AppendProfiles_03(std::vector<FilmProfile>& v);
void AppendProfiles_04(std::vector<FilmProfile>& v);
void AppendProfiles_05(std::vector<FilmProfile>& v);
void AppendProfiles_06(std::vector<FilmProfile>& v);
void AppendProfiles_07(std::vector<FilmProfile>& v);
void AppendProfiles_08(std::vector<FilmProfile>& v);
void AppendProfiles_09(std::vector<FilmProfile>& v);
void AppendProfiles_10(std::vector<FilmProfile>& v);
void AppendProfiles_11(std::vector<FilmProfile>& v);
void AppendProfiles_12(std::vector<FilmProfile>& v);
void AppendProfiles_13(std::vector<FilmProfile>& v);
void AppendProfiles_14(std::vector<FilmProfile>& v);
void AppendProfiles_15(std::vector<FilmProfile>& v);
void AppendProfiles_16(std::vector<FilmProfile>& v);

}  // namespace detail
}  // namespace film
